package com.mobicart.dao;

import com.mobicart.dto.LabelsDto;
import com.mobicart.model.Labels;
import com.mobicart.model.LabelsExample;
import java.sql.SQLException;
import java.util.List;

public interface LabelsDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table labels
	 * @ibatorgenerated  Tue Jun 28 17:25:47 IST 2011
	 */
	int countLabelsByExample(LabelsExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table labels
	 * @ibatorgenerated  Tue Jun 28 17:25:47 IST 2011
	 */
	int deleteLabelsByExample(LabelsExample example) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table labels
	 * @ibatorgenerated  Tue Jun 28 17:25:47 IST 2011
	 */
	int deleteLabelsByPrimaryKey(Long labelId) throws SQLException;
	
	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table labels
	 * @ibatorgenerated  Tue Jun 28 17:25:47 IST 2011
	 */
	int deleteLabelsByMerchantId(Long merchantId) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table labels
	 * @ibatorgenerated  Tue Jun 28 17:25:47 IST 2011
	 */
	void insertLabels(Labels record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table labels
	 * @ibatorgenerated  Tue Jun 28 17:25:47 IST 2011
	 */
	void insertLabelsSelective(Labels record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table labels
	 * @ibatorgenerated  Tue Jun 28 17:25:47 IST 2011
	 */
	List selectLabelsByExampleWithBLOBs(LabelsExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table labels
	 * @ibatorgenerated  Tue Jun 28 17:25:47 IST 2011
	 */
	List selectLabelsByExampleWithoutBLOBs(LabelsExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table labels
	 * @ibatorgenerated  Tue Jun 28 17:25:47 IST 2011
	 */
	Labels selectLabelsByPrimaryKey(Long labelId) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table labels
	 * @ibatorgenerated  Tue Jun 28 17:25:47 IST 2011
	 */
	int updateLabelsByExampleSelective(Labels record, LabelsExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table labels
	 * @ibatorgenerated  Tue Jun 28 17:25:47 IST 2011
	 */
	int updateLabelsByExampleWithBLOBs(Labels record, LabelsExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table labels
	 * @ibatorgenerated  Tue Jun 28 17:25:47 IST 2011
	 */
	int updateLabelsByExampleWithoutBLOBs(Labels record, LabelsExample example)
			throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table labels
	 * @ibatorgenerated  Tue Jun 28 17:25:47 IST 2011
	 */
	int updateLabelsByPrimaryKeySelective(Labels record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table labels
	 * @ibatorgenerated  Tue Jun 28 17:25:47 IST 2011
	 */
	int updateLabelsByPrimaryKeyWithBLOBs(Labels record) throws SQLException;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table labels
	 * @ibatorgenerated  Tue Jun 28 17:25:47 IST 2011
	 */
	int updateLabelsByPrimaryKeyWithoutBLOBs(Labels record) throws SQLException;
	
	public List<LabelsDto> getAllIphoneLabels() throws SQLException;
	
	public List<LabelsDto> getAllWebLabels() throws SQLException;
	
	public List<LabelsDto> getAllIphoneLabelsByMerchantId(Long merchantId) throws SQLException;
	
	public List<LabelsDto> getAllWebLabelsByMerchantId(Long merchantId) throws SQLException;
	
	public Boolean isLabelInSync(Long merchantId,String dateAdded) throws SQLException;
	
	public String getWebKeyLabelValueByMerchantId(String labelKey, Long userId) throws SQLException;
	
}