package com.mobicart.model;

public class AppFeatures {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column app_features.app_id
	 * @ibatorgenerated  Tue Aug 03 16:33:41 IST 2010
	 */
	private Long appId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column app_features.feature_id
	 * @ibatorgenerated  Tue Aug 03 16:33:41 IST 2010
	 */
	private Long featureId;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column app_features.app_id
	 * @return  the value of app_features.app_id
	 * @ibatorgenerated  Tue Aug 03 16:33:41 IST 2010
	 */
	public Long getAppId() {
		return appId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column app_features.app_id
	 * @param appId  the value for app_features.app_id
	 * @ibatorgenerated  Tue Aug 03 16:33:41 IST 2010
	 */
	public void setAppId(Long appId) {
		this.appId = appId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column app_features.feature_id
	 * @return  the value of app_features.feature_id
	 * @ibatorgenerated  Tue Aug 03 16:33:41 IST 2010
	 */
	public Long getFeatureId() {
		return featureId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column app_features.feature_id
	 * @param featureId  the value for app_features.feature_id
	 * @ibatorgenerated  Tue Aug 03 16:33:41 IST 2010
	 */
	public void setFeatureId(Long featureId) {
		this.featureId = featureId;
	}
	

	public AppFeatures() {
		super();
	}

	public AppFeatures(Long appId, Long featureId) {
		super();
		this.appId = appId;
		this.featureId = featureId;
	}

}