package com.mobicart.model;


import com.mobicart.util.ColorUtils;
import com.thoughtworks.xstream.annotations.XStreamAlias;

@XStreamAlias("colorscheme")
public class ColorScheme {

	private Long id;
	private String sTitle;
	private String sType;
	private String sBgColor;
	private String sFgColor;
	private String sBgImage;
	private String sProductItemBgColor;
	private String sSearchButtonBgColor;
	private String sPriceTagBgColor;
	private String bgColorRGB;
	private String fgColorRGB;
	private String productItemBgColorRGB;
	private String searchButtonBgColorRGB;
	private String priceTagFgColorRGB;
	private String bgColorRGBGradient;
	private String fgColorRGBGradient;
	private String productItemBgColorRGBGradient;
	private String searchButtonBgColorRGBGradient;
	private String priceTagFgColorRGBGradient;
	private String priceTagFgColor;
	
	private String DefaultColor="FFFFFF";
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column color_schemes.id
	 * @param id  the value for color_schemes.id
	 * @ibatorgenerated  Sat Aug 07 17:53:59 IST 2010
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column color_schemes.s_title
	 * @return  the value of color_schemes.s_title
	 * @ibatorgenerated  Sat Aug 07 17:53:59 IST 2010
	 */
	public String getsTitle() {
		return sTitle;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column color_schemes.s_title
	 * @param sTitle  the value for color_schemes.s_title
	 * @ibatorgenerated  Sat Aug 07 17:53:59 IST 2010
	 */
	public void setsTitle(String sTitle) {
		this.sTitle = sTitle == null ? null : sTitle.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column color_schemes.s_bg_color
	 * @return  the value of color_schemes.s_bg_color
	 * @ibatorgenerated  Sat Aug 07 17:53:59 IST 2010
	 */
	public String getsBgColor() {
		return sBgColor;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column color_schemes.s_bg_color
	 * @param sBgColor  the value for color_schemes.s_bg_color
	 * @ibatorgenerated  Sat Aug 07 17:53:59 IST 2010
	 */
	public void setsBgColor(String sBgColor) {
		this.sBgColor = sBgColor == null ? null : sBgColor.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column color_schemes.s_fg_color
	 * @return  the value of color_schemes.s_fg_color
	 * @ibatorgenerated  Sat Aug 07 17:53:59 IST 2010
	 */
	public String getsFgColor() {
		return sFgColor;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column color_schemes.s_fg_color
	 * @param sFgColor  the value for color_schemes.s_fg_color
	 * @ibatorgenerated  Sat Aug 07 17:53:59 IST 2010
	 */
	public void setsFgColor(String sFgColor) {
		this.sFgColor = sFgColor == null ? null : sFgColor.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column color_schemes.s_bg_image
	 * @return  the value of color_schemes.s_bg_image
	 * @ibatorgenerated  Sat Aug 07 17:53:59 IST 2010
	 */
	public String getsBgImage() {
		return sBgImage;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column color_schemes.s_bg_image
	 * @param sBgImage  the value for color_schemes.s_bg_image
	 * @ibatorgenerated  Sat Aug 07 17:53:59 IST 2010
	 */
	public void setsBgImage(String sBgImage) {
		this.sBgImage = sBgImage == null ? null : sBgImage.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column color_schemes.s_product_item_bg_color
	 * @return  the value of color_schemes.s_product_item_bg_color
	 * @ibatorgenerated  Sat Aug 07 17:53:59 IST 2010
	 */
	public String getsProductItemBgColor() {
		return sProductItemBgColor;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column color_schemes.s_product_item_bg_color
	 * @param sProductItemBgColor  the value for color_schemes.s_product_item_bg_color
	 * @ibatorgenerated  Sat Aug 07 17:53:59 IST 2010
	 */
	public void setsProductItemBgColor(String sProductItemBgColor) {
		this.sProductItemBgColor = sProductItemBgColor == null ? null
				: sProductItemBgColor.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column color_schemes.s_search_button_bg_color
	 * @return  the value of color_schemes.s_search_button_bg_color
	 * @ibatorgenerated  Sat Aug 07 17:53:59 IST 2010
	 */
	public String getsSearchButtonBgColor() {
		return sSearchButtonBgColor;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column color_schemes.s_search_button_bg_color
	 * @param sSearchButtonBgColor  the value for color_schemes.s_search_button_bg_color
	 * @ibatorgenerated  Sat Aug 07 17:53:59 IST 2010
	 */
	public void setsSearchButtonBgColor(String sSearchButtonBgColor) {
		this.sSearchButtonBgColor = sSearchButtonBgColor == null ? null
				: sSearchButtonBgColor.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column color_schemes.s_price_tag_bg_color
	 * @return  the value of color_schemes.s_price_tag_bg_color
	 * @ibatorgenerated  Sat Aug 07 17:53:59 IST 2010
	 */
	public String getsPriceTagBgColor() {
		return (sPriceTagBgColor!=null)?sPriceTagBgColor:DefaultColor;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column color_schemes.s_price_tag_bg_color
	 * @param sPriceTagBgColor  the value for color_schemes.s_price_tag_bg_color
	 * @ibatorgenerated  Sat Aug 07 17:53:59 IST 2010
	 */
	public void setsPriceTagBgColor(String sPriceTagBgColor) {
		this.sPriceTagBgColor = sPriceTagBgColor == null ? sPriceTagBgColor: sPriceTagBgColor.trim();
	}

	public String getBgColorRGB() {
		bgColorRGB=ColorUtils.hexToRGB(sBgColor);
		return bgColorRGB;
	}

	public String getFgColorRGB() {
		fgColorRGB=ColorUtils.hexToRGB(sFgColor);
		return fgColorRGB;
	}

	public String getProductItemBgColorRGB() {
		productItemBgColorRGB=ColorUtils.hexToRGB(sProductItemBgColor);
		return productItemBgColorRGB;
	}

	public String getSearchButtonBgColorRGB() {
		searchButtonBgColorRGB=ColorUtils.hexToRGB(sSearchButtonBgColor);
		return searchButtonBgColorRGB;
	}

	public String getPriceTagFgColorRGB() {
		priceTagFgColorRGB=ColorUtils.hexToRGB(sPriceTagBgColor);
		return priceTagFgColorRGB;
	}

	
	
	public String getBgColorRGBGradient() {
		bgColorRGBGradient=ColorUtils.hexToRGBGradient(sBgColor);
		return bgColorRGBGradient;
	}

	public String getFgColorRGBGradient() {
		fgColorRGBGradient=ColorUtils.hexToRGBGradient(sFgColor);
		return fgColorRGBGradient;
	}

	public String getProductItemBgColorRGBGradient() {
		productItemBgColorRGBGradient=ColorUtils.hexToRGBGradient(sProductItemBgColor);
		return productItemBgColorRGBGradient;
	}

	public String getSearchButtonBgColorRGBGradient() {
		searchButtonBgColorRGBGradient=ColorUtils.hexToRGBGradient(sSearchButtonBgColor);
		return searchButtonBgColorRGBGradient;
	}

	public String getPriceTagFgColorRGBGradient() {
		priceTagFgColorRGBGradient=ColorUtils.hexToRGBGradient(sPriceTagBgColor);
		return priceTagFgColorRGBGradient;
	}
	
	public String getPriceTagFgColor() {
		return (priceTagFgColor!=null)?priceTagFgColor:DefaultColor;
	}

	public void setPriceTagFgColor(String priceTagFgColor) {
		this.priceTagFgColor = priceTagFgColor;
	}

	
	public String getsType() {
		return sType;
	}

	public void setsType(String sType) {
		this.sType = sType;
	}

	@Override
	public String toString() {
		return "ColorScheme [id=" + id + ", sType=" + sType 
		        + ", sBgColor="+ sBgColor 
		        + ", sFgColor=" + sFgColor
				+ ", sProductItemBgColor=" + sProductItemBgColor
				+ ", sSearchButtonBgColor=" + sSearchButtonBgColor
				+ ", sBgImage=" + sBgImage
				+ "]";
	}

		

	
	
	
	
	
}