package com.mobicart.model;

import java.math.BigDecimal;
import java.util.Date;

public class MerchantService {
	
	
	
	public MerchantService(){
		
	}
	
	public MerchantService(Long id){
		 this.id = id;
	}
	
	
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column merchant_services.id
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column merchant_services.merchant_id
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    private Long merchantId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column merchant_services.app_id
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    private Long appId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column merchant_services.store_id
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    private Long storeId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column merchant_services.s_service_type
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    private String sServiceType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column merchant_services.s_payment_status
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    private String sPaymentStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column merchant_services.f_amount
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    private BigDecimal fAmount;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column merchant_services.f_payment_fee
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    private BigDecimal fPaymentFee;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column merchant_services.txn_id
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    private String txnId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column merchant_services.payer_id
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    private String payerId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column merchant_services.d_payment_date
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    private Date dPaymentDate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column merchant_services.s_remarks
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    private String sRemarks;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column merchant_services.id
     *
     * @return the value of merchant_services.id
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column merchant_services.id
     *
     * @param id the value for merchant_services.id
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column merchant_services.merchant_id
     *
     * @return the value of merchant_services.merchant_id
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column merchant_services.merchant_id
     *
     * @param merchantId the value for merchant_services.merchant_id
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column merchant_services.app_id
     *
     * @return the value of merchant_services.app_id
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column merchant_services.app_id
     *
     * @param appId the value for merchant_services.app_id
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column merchant_services.store_id
     *
     * @return the value of merchant_services.store_id
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column merchant_services.store_id
     *
     * @param storeId the value for merchant_services.store_id
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column merchant_services.s_service_type
     *
     * @return the value of merchant_services.s_service_type
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    public String getsServiceType() {
        return sServiceType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column merchant_services.s_service_type
     *
     * @param sServiceType the value for merchant_services.s_service_type
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    public void setsServiceType(String sServiceType) {
        this.sServiceType = sServiceType == null ? null : sServiceType.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column merchant_services.s_payment_status
     *
     * @return the value of merchant_services.s_payment_status
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    public String getsPaymentStatus() {
        return sPaymentStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column merchant_services.s_payment_status
     *
     * @param sPaymentStatus the value for merchant_services.s_payment_status
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    public void setsPaymentStatus(String sPaymentStatus) {
        this.sPaymentStatus = sPaymentStatus == null ? null : sPaymentStatus.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column merchant_services.f_amount
     *
     * @return the value of merchant_services.f_amount
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    public BigDecimal getfAmount() {
        return fAmount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column merchant_services.f_amount
     *
     * @param fAmount the value for merchant_services.f_amount
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    public void setfAmount(BigDecimal fAmount) {
        this.fAmount = fAmount;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column merchant_services.f_payment_fee
     *
     * @return the value of merchant_services.f_payment_fee
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    public BigDecimal getfPaymentFee() {
        return fPaymentFee;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column merchant_services.f_payment_fee
     *
     * @param fPaymentFee the value for merchant_services.f_payment_fee
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    public void setfPaymentFee(BigDecimal fPaymentFee) {
        this.fPaymentFee = fPaymentFee;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column merchant_services.txn_id
     *
     * @return the value of merchant_services.txn_id
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    public String getTxnId() {
        return txnId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column merchant_services.txn_id
     *
     * @param txnId the value for merchant_services.txn_id
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    public void setTxnId(String txnId) {
        this.txnId = txnId == null ? null : txnId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column merchant_services.payer_id
     *
     * @return the value of merchant_services.payer_id
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    public String getPayerId() {
        return payerId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column merchant_services.payer_id
     *
     * @param payerId the value for merchant_services.payer_id
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    public void setPayerId(String payerId) {
        this.payerId = payerId == null ? null : payerId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column merchant_services.d_payment_date
     *
     * @return the value of merchant_services.d_payment_date
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    public Date getdPaymentDate() {
        return dPaymentDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column merchant_services.d_payment_date
     *
     * @param dPaymentDate the value for merchant_services.d_payment_date
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    public void setdPaymentDate(Date dPaymentDate) {
        this.dPaymentDate = dPaymentDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column merchant_services.s_remarks
     *
     * @return the value of merchant_services.s_remarks
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    public String getsRemarks() {
        return sRemarks;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column merchant_services.s_remarks
     *
     * @param sRemarks the value for merchant_services.s_remarks
     *
     * @ibatorgenerated Sat Apr 09 15:16:44 IST 2011
     */
    public void setsRemarks(String sRemarks) {
        this.sRemarks = sRemarks == null ? null : sRemarks.trim();
    }
}