package com.mobicart.model;

public class ProductCategory {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column product_categories.product_id
     *
     * @ibatorgenerated Mon Aug 16 19:46:37 IST 2010
     */
    private Long productId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column product_categories.category_id
     *
     * @ibatorgenerated Mon Aug 16 19:46:37 IST 2010
     */
    private Long categoryId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column product_categories.product_id
     *
     * @return the value of product_categories.product_id
     *
     * @ibatorgenerated Mon Aug 16 19:46:37 IST 2010
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column product_categories.product_id
     *
     * @param productId the value for product_categories.product_id
     *
     * @ibatorgenerated Mon Aug 16 19:46:37 IST 2010
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column product_categories.category_id
     *
     * @return the value of product_categories.category_id
     *
     * @ibatorgenerated Mon Aug 16 19:46:37 IST 2010
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column product_categories.category_id
     *
     * @param categoryId the value for product_categories.category_id
     *
     * @ibatorgenerated Mon Aug 16 19:46:37 IST 2010
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }
}