package com.mobicart.model;

import javax.xml.bind.annotation.XmlElement;

import org.codehaus.jackson.annotate.JsonWriteNullProperties;

@JsonWriteNullProperties(false)
public class ProductReview {

	private Long id;
	
	private Long productId;
	
	private String sReveiwerName;
	
	private String sReviewerEmail;
	@XmlElement(required = false)
	private String sReviewerLocation;
	
	private Integer iRating;
	
	private String sReview;
	
	private String localDatabaseUserEmail;

	private String localDatabaseUserName;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column product_reviews.id
	 * @return  the value of product_reviews.id
	 * @ibatorgenerated  Mon Dec 20 16:44:10 IST 2010
	 */
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method returns the value of the database column product_reviews.product_id
	 * @return  the value of product_reviews.product_id
	 */
	public Long getProductId() {
		return productId;
	}

	/**
	 *  This method sets the value of the database column product_reviews.product_id
	 * @param productId  the value for product_reviews.product_id
	 */
	public void setProductId(Long productId) {
		this.productId = productId;
	}

	/**
	 *  This method returns the value of the database column product_reviews.s_reveiwer_name
	 * @return  the value of product_reviews.s_reveiwer_name
	 */
	public String getsReveiwerName() {
		return sReveiwerName;
	}

	/**
	 *  This method sets the value of the database column product_reviews.s_reveiwer_name
	 * @param sReveiwerName  the value for product_reviews.s_reveiwer_name
	 */
	public void setsReveiwerName(String sReveiwerName) {
		this.sReveiwerName = sReveiwerName == null ? null : sReveiwerName
				.trim();
	}

	/**
	 *  This method returns the value of the database column product_reviews.s_reviewer_email
	 * @return  the value of product_reviews.s_reviewer_email
	 */
	public String getsReviewerEmail() {
		return sReviewerEmail;
	}

	/**
	 *  This method sets the value of the database column product_reviews.s_reviewer_email
	 * @param sReviewerEmail  the value for product_reviews.s_reviewer_email
	 */
	public void setsReviewerEmail(String sReviewerEmail) {
		this.sReviewerEmail = sReviewerEmail == null ? null : sReviewerEmail
				.trim();
	}

	/**
	 *  This method returns the value of the database column product_reviews.s_reviewer_location
	 * @return  the value of product_reviews.s_reviewer_location
	 */
	public String getsReviewerLocation() {
		return sReviewerLocation;
	}

	/**
	 *  This method sets the value of the database column product_reviews.s_reviewer_location
	 * @param sReviewerLocation  the value for product_reviews.s_reviewer_location
	 */
	public void setsReviewerLocation(String sReviewerLocation) {
		this.sReviewerLocation = sReviewerLocation == null ? null
				: sReviewerLocation.trim();
	}

	/**
	 *  This method returns the value of the database column product_reviews.i_rating
	 * @return  the value of product_reviews.i_rating
	 */
	public Integer getiRating() {
		return iRating;
	}

	/**
	 *  This method sets the value of the database column product_reviews.i_rating
	 * @param iRating  the value for product_reviews.i_rating
	 */
	public void setiRating(Integer iRating) {
		this.iRating = iRating;
	}

	/**
	 *  This method returns the value of the database column product_reviews.s_review
	 * @return  the value of product_reviews.s_review
	 */
	public String getsReview() {
		return sReview;
	}

	/**
	 *  This method sets the value of the database column product_reviews.s_review
	 * @param sReview  the value for product_reviews.s_review
	 */
	public void setsReview(String sReview) {
		this.sReview = sReview == null ? null : sReview.trim();
	}

	public String getLocalDatabaseUserEmail() {
		return localDatabaseUserEmail;
	}

	public void setLocalDatabaseUserEmail(String localDatabaseUserEmail) {
		this.localDatabaseUserEmail = localDatabaseUserEmail;
	}

	public String getLocalDatabaseUserName() {
		return localDatabaseUserName;
	}

	public void setLocalDatabaseUserName(String localDatabaseUserName) {
		this.localDatabaseUserName = localDatabaseUserName;
	}
	
	
}
