package com.mobicart.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.math.BigDecimal;

public class ProductExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table products
	 * @ibatorgenerated  Tue Dec 14 16:02:03 IST 2010
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table products
	 * @ibatorgenerated  Tue Dec 14 16:02:03 IST 2010
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table products
	 * @ibatorgenerated  Tue Dec 14 16:02:03 IST 2010
	 */
	public ProductExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table products
	 * @ibatorgenerated  Tue Dec 14 16:02:03 IST 2010
	 */
	protected ProductExample(ProductExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table products
	 * @ibatorgenerated  Tue Dec 14 16:02:03 IST 2010
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table products
	 * @ibatorgenerated  Tue Dec 14 16:02:03 IST 2010
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table products
	 * @ibatorgenerated  Tue Dec 14 16:02:03 IST 2010
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table products
	 * @ibatorgenerated  Tue Dec 14 16:02:03 IST 2010
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table products
	 * @ibatorgenerated  Tue Dec 14 16:02:03 IST 2010
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table products
	 * @ibatorgenerated  Tue Dec 14 16:02:03 IST 2010
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table products
	 * @ibatorgenerated  Tue Dec 14 16:02:03 IST 2010
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table products
	 * @ibatorgenerated  Tue Dec 14 16:02:03 IST 2010
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return this;
		}

		public Criteria andIdIn(List values) {
			addCriterion("id in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List values) {
			addCriterion("id not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return this;
		}

		public Criteria andUserIdEqualTo(Long value) {
			addCriterion("user_id =", value, "userId");
			return this;
		}

		public Criteria andUserIdNotEqualTo(Long value) {
			addCriterion("user_id <>", value, "userId");
			return this;
		}

		public Criteria andUserIdGreaterThan(Long value) {
			addCriterion("user_id >", value, "userId");
			return this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
			addCriterion("user_id >=", value, "userId");
			return this;
		}

		public Criteria andUserIdLessThan(Long value) {
			addCriterion("user_id <", value, "userId");
			return this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Long value) {
			addCriterion("user_id <=", value, "userId");
			return this;
		}

		public Criteria andUserIdIn(List values) {
			addCriterion("user_id in", values, "userId");
			return this;
		}

		public Criteria andUserIdNotIn(List values) {
			addCriterion("user_id not in", values, "userId");
			return this;
		}

		public Criteria andUserIdBetween(Long value1, Long value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return this;
		}

		public Criteria andUserIdNotBetween(Long value1, Long value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return this;
		}

		public Criteria andStoreIdIsNull() {
			addCriterion("store_id is null");
			return this;
		}

		public Criteria andStoreIdIsNotNull() {
			addCriterion("store_id is not null");
			return this;
		}

		public Criteria andStoreIdEqualTo(Long value) {
			addCriterion("store_id =", value, "storeId");
			return this;
		}

		public Criteria andStoreIdNotEqualTo(Long value) {
			addCriterion("store_id <>", value, "storeId");
			return this;
		}

		public Criteria andStoreIdGreaterThan(Long value) {
			addCriterion("store_id >", value, "storeId");
			return this;
		}

		public Criteria andStoreIdGreaterThanOrEqualTo(Long value) {
			addCriterion("store_id >=", value, "storeId");
			return this;
		}

		public Criteria andStoreIdLessThan(Long value) {
			addCriterion("store_id <", value, "storeId");
			return this;
		}

		public Criteria andStoreIdLessThanOrEqualTo(Long value) {
			addCriterion("store_id <=", value, "storeId");
			return this;
		}

		public Criteria andStoreIdIn(List values) {
			addCriterion("store_id in", values, "storeId");
			return this;
		}

		public Criteria andStoreIdNotIn(List values) {
			addCriterion("store_id not in", values, "storeId");
			return this;
		}

		public Criteria andStoreIdBetween(Long value1, Long value2) {
			addCriterion("store_id between", value1, value2, "storeId");
			return this;
		}

		public Criteria andStoreIdNotBetween(Long value1, Long value2) {
			addCriterion("store_id not between", value1, value2, "storeId");
			return this;
		}

		public Criteria andAppIdIsNull() {
			addCriterion("app_id is null");
			return this;
		}

		public Criteria andAppIdIsNotNull() {
			addCriterion("app_id is not null");
			return this;
		}

		public Criteria andAppIdEqualTo(Long value) {
			addCriterion("app_id =", value, "appId");
			return this;
		}

		public Criteria andAppIdNotEqualTo(Long value) {
			addCriterion("app_id <>", value, "appId");
			return this;
		}

		public Criteria andAppIdGreaterThan(Long value) {
			addCriterion("app_id >", value, "appId");
			return this;
		}

		public Criteria andAppIdGreaterThanOrEqualTo(Long value) {
			addCriterion("app_id >=", value, "appId");
			return this;
		}

		public Criteria andAppIdLessThan(Long value) {
			addCriterion("app_id <", value, "appId");
			return this;
		}

		public Criteria andAppIdLessThanOrEqualTo(Long value) {
			addCriterion("app_id <=", value, "appId");
			return this;
		}

		public Criteria andAppIdIn(List values) {
			addCriterion("app_id in", values, "appId");
			return this;
		}

		public Criteria andAppIdNotIn(List values) {
			addCriterion("app_id not in", values, "appId");
			return this;
		}

		public Criteria andAppIdBetween(Long value1, Long value2) {
			addCriterion("app_id between", value1, value2, "appId");
			return this;
		}

		public Criteria andAppIdNotBetween(Long value1, Long value2) {
			addCriterion("app_id not between", value1, value2, "appId");
			return this;
		}

		public Criteria andDepartmentIdIsNull() {
			addCriterion("department_id is null");
			return this;
		}

		public Criteria andDepartmentIdIsNotNull() {
			addCriterion("department_id is not null");
			return this;
		}

		public Criteria andDepartmentIdEqualTo(Long value) {
			addCriterion("department_id =", value, "departmentId");
			return this;
		}

		public Criteria andDepartmentIdNotEqualTo(Long value) {
			addCriterion("department_id <>", value, "departmentId");
			return this;
		}

		public Criteria andDepartmentIdGreaterThan(Long value) {
			addCriterion("department_id >", value, "departmentId");
			return this;
		}

		public Criteria andDepartmentIdGreaterThanOrEqualTo(Long value) {
			addCriterion("department_id >=", value, "departmentId");
			return this;
		}

		public Criteria andDepartmentIdLessThan(Long value) {
			addCriterion("department_id <", value, "departmentId");
			return this;
		}

		public Criteria andDepartmentIdLessThanOrEqualTo(Long value) {
			addCriterion("department_id <=", value, "departmentId");
			return this;
		}

		public Criteria andDepartmentIdIn(List values) {
			addCriterion("department_id in", values, "departmentId");
			return this;
		}

		public Criteria andDepartmentIdNotIn(List values) {
			addCriterion("department_id not in", values, "departmentId");
			return this;
		}

		public Criteria andDepartmentIdBetween(Long value1, Long value2) {
			addCriterion("department_id between", value1, value2,
					"departmentId");
			return this;
		}

		public Criteria andDepartmentIdNotBetween(Long value1, Long value2) {
			addCriterion("department_id not between", value1, value2,
					"departmentId");
			return this;
		}

		public Criteria andCategoryIdIsNull() {
			addCriterion("category_id is null");
			return this;
		}

		public Criteria andCategoryIdIsNotNull() {
			addCriterion("category_id is not null");
			return this;
		}

		public Criteria andCategoryIdEqualTo(Long value) {
			addCriterion("category_id =", value, "categoryId");
			return this;
		}

		public Criteria andCategoryIdNotEqualTo(Long value) {
			addCriterion("category_id <>", value, "categoryId");
			return this;
		}

		public Criteria andCategoryIdGreaterThan(Long value) {
			addCriterion("category_id >", value, "categoryId");
			return this;
		}

		public Criteria andCategoryIdGreaterThanOrEqualTo(Long value) {
			addCriterion("category_id >=", value, "categoryId");
			return this;
		}

		public Criteria andCategoryIdLessThan(Long value) {
			addCriterion("category_id <", value, "categoryId");
			return this;
		}

		public Criteria andCategoryIdLessThanOrEqualTo(Long value) {
			addCriterion("category_id <=", value, "categoryId");
			return this;
		}

		public Criteria andCategoryIdIn(List values) {
			addCriterion("category_id in", values, "categoryId");
			return this;
		}

		public Criteria andCategoryIdNotIn(List values) {
			addCriterion("category_id not in", values, "categoryId");
			return this;
		}

		public Criteria andCategoryIdBetween(Long value1, Long value2) {
			addCriterion("category_id between", value1, value2, "categoryId");
			return this;
		}

		public Criteria andCategoryIdNotBetween(Long value1, Long value2) {
			addCriterion("category_id not between", value1, value2,
					"categoryId");
			return this;
		}

		public Criteria andSNameIsNull() {
			addCriterion("s_name is null");
			return this;
		}

		public Criteria andSNameIsNotNull() {
			addCriterion("s_name is not null");
			return this;
		}

		public Criteria andSNameEqualTo(String value) {
			addCriterion("s_name =", value, "sName");
			return this;
		}

		public Criteria andSNameNotEqualTo(String value) {
			addCriterion("s_name <>", value, "sName");
			return this;
		}

		public Criteria andSNameGreaterThan(String value) {
			addCriterion("s_name >", value, "sName");
			return this;
		}

		public Criteria andSNameGreaterThanOrEqualTo(String value) {
			addCriterion("s_name >=", value, "sName");
			return this;
		}

		public Criteria andSNameLessThan(String value) {
			addCriterion("s_name <", value, "sName");
			return this;
		}

		public Criteria andSNameLessThanOrEqualTo(String value) {
			addCriterion("s_name <=", value, "sName");
			return this;
		}

		public Criteria andSNameLike(String value) {
			addCriterion("s_name like", value, "sName");
			return this;
		}

		public Criteria andSNameNotLike(String value) {
			addCriterion("s_name not like", value, "sName");
			return this;
		}

		public Criteria andSNameIn(List values) {
			addCriterion("s_name in", values, "sName");
			return this;
		}

		public Criteria andSNameNotIn(List values) {
			addCriterion("s_name not in", values, "sName");
			return this;
		}

		public Criteria andSNameBetween(String value1, String value2) {
			addCriterion("s_name between", value1, value2, "sName");
			return this;
		}

		public Criteria andSNameNotBetween(String value1, String value2) {
			addCriterion("s_name not between", value1, value2, "sName");
			return this;
		}

		public Criteria andFPriceIsNull() {
			addCriterion("f_price is null");
			return this;
		}

		public Criteria andFPriceIsNotNull() {
			addCriterion("f_price is not null");
			return this;
		}

		public Criteria andFPriceEqualTo(BigDecimal value) {
			addCriterion("f_price =", value, "fPrice");
			return this;
		}

		public Criteria andFPriceNotEqualTo(BigDecimal value) {
			addCriterion("f_price <>", value, "fPrice");
			return this;
		}

		public Criteria andFPriceGreaterThan(BigDecimal value) {
			addCriterion("f_price >", value, "fPrice");
			return this;
		}

		public Criteria andFPriceGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("f_price >=", value, "fPrice");
			return this;
		}

		public Criteria andFPriceLessThan(BigDecimal value) {
			addCriterion("f_price <", value, "fPrice");
			return this;
		}

		public Criteria andFPriceLessThanOrEqualTo(BigDecimal value) {
			addCriterion("f_price <=", value, "fPrice");
			return this;
		}

		public Criteria andFPriceIn(List values) {
			addCriterion("f_price in", values, "fPrice");
			return this;
		}

		public Criteria andFPriceNotIn(List values) {
			addCriterion("f_price not in", values, "fPrice");
			return this;
		}

		public Criteria andFPriceBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("f_price between", value1, value2, "fPrice");
			return this;
		}

		public Criteria andFPriceNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("f_price not between", value1, value2, "fPrice");
			return this;
		}

		public Criteria andSStatusIsNull() {
			addCriterion("s_status is null");
			return this;
		}

		public Criteria andSStatusIsNotNull() {
			addCriterion("s_status is not null");
			return this;
		}

		public Criteria andSStatusEqualTo(String value) {
			addCriterion("s_status =", value, "sStatus");
			return this;
		}

		public Criteria andSStatusNotEqualTo(String value) {
			addCriterion("s_status <>", value, "sStatus");
			return this;
		}

		public Criteria andSStatusGreaterThan(String value) {
			addCriterion("s_status >", value, "sStatus");
			return this;
		}

		public Criteria andSStatusGreaterThanOrEqualTo(String value) {
			addCriterion("s_status >=", value, "sStatus");
			return this;
		}

		public Criteria andSStatusLessThan(String value) {
			addCriterion("s_status <", value, "sStatus");
			return this;
		}

		public Criteria andSStatusLessThanOrEqualTo(String value) {
			addCriterion("s_status <=", value, "sStatus");
			return this;
		}

		public Criteria andSStatusLike(String value) {
			addCriterion("s_status like", value, "sStatus");
			return this;
		}

		public Criteria andSStatusNotLike(String value) {
			addCriterion("s_status not like", value, "sStatus");
			return this;
		}

		public Criteria andSStatusIn(List values) {
			addCriterion("s_status in", values, "sStatus");
			return this;
		}

		public Criteria andSStatusNotIn(List values) {
			addCriterion("s_status not in", values, "sStatus");
			return this;
		}

		public Criteria andSStatusBetween(String value1, String value2) {
			addCriterion("s_status between", value1, value2, "sStatus");
			return this;
		}

		public Criteria andSStatusNotBetween(String value1, String value2) {
			addCriterion("s_status not between", value1, value2, "sStatus");
			return this;
		}

		public Criteria andFDiscountIsNull() {
			addCriterion("f_discount is null");
			return this;
		}

		public Criteria andFDiscountIsNotNull() {
			addCriterion("f_discount is not null");
			return this;
		}

		public Criteria andFDiscountEqualTo(BigDecimal value) {
			addCriterion("f_discount =", value, "fDiscount");
			return this;
		}

		public Criteria andFDiscountNotEqualTo(BigDecimal value) {
			addCriterion("f_discount <>", value, "fDiscount");
			return this;
		}

		public Criteria andFDiscountGreaterThan(BigDecimal value) {
			addCriterion("f_discount >", value, "fDiscount");
			return this;
		}

		public Criteria andFDiscountGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("f_discount >=", value, "fDiscount");
			return this;
		}

		public Criteria andFDiscountLessThan(BigDecimal value) {
			addCriterion("f_discount <", value, "fDiscount");
			return this;
		}

		public Criteria andFDiscountLessThanOrEqualTo(BigDecimal value) {
			addCriterion("f_discount <=", value, "fDiscount");
			return this;
		}

		public Criteria andFDiscountIn(List values) {
			addCriterion("f_discount in", values, "fDiscount");
			return this;
		}

		public Criteria andFDiscountNotIn(List values) {
			addCriterion("f_discount not in", values, "fDiscount");
			return this;
		}

		public Criteria andFDiscountBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("f_discount between", value1, value2, "fDiscount");
			return this;
		}

		public Criteria andFDiscountNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("f_discount not between", value1, value2, "fDiscount");
			return this;
		}

		public Criteria andSProductUrlIsNull() {
			addCriterion("s_product_url is null");
			return this;
		}

		public Criteria andSProductUrlIsNotNull() {
			addCriterion("s_product_url is not null");
			return this;
		}

		public Criteria andSProductUrlEqualTo(String value) {
			addCriterion("s_product_url =", value, "sProductUrl");
			return this;
		}

		public Criteria andSProductUrlNotEqualTo(String value) {
			addCriterion("s_product_url <>", value, "sProductUrl");
			return this;
		}

		public Criteria andSProductUrlGreaterThan(String value) {
			addCriterion("s_product_url >", value, "sProductUrl");
			return this;
		}

		public Criteria andSProductUrlGreaterThanOrEqualTo(String value) {
			addCriterion("s_product_url >=", value, "sProductUrl");
			return this;
		}

		public Criteria andSProductUrlLessThan(String value) {
			addCriterion("s_product_url <", value, "sProductUrl");
			return this;
		}

		public Criteria andSProductUrlLessThanOrEqualTo(String value) {
			addCriterion("s_product_url <=", value, "sProductUrl");
			return this;
		}

		public Criteria andSProductUrlLike(String value) {
			addCriterion("s_product_url like", value, "sProductUrl");
			return this;
		}

		public Criteria andSProductUrlNotLike(String value) {
			addCriterion("s_product_url not like", value, "sProductUrl");
			return this;
		}

		public Criteria andSProductUrlIn(List values) {
			addCriterion("s_product_url in", values, "sProductUrl");
			return this;
		}

		public Criteria andSProductUrlNotIn(List values) {
			addCriterion("s_product_url not in", values, "sProductUrl");
			return this;
		}

		public Criteria andSProductUrlBetween(String value1, String value2) {
			addCriterion("s_product_url between", value1, value2, "sProductUrl");
			return this;
		}

		public Criteria andSProductUrlNotBetween(String value1, String value2) {
			addCriterion("s_product_url not between", value1, value2,
					"sProductUrl");
			return this;
		}

		public Criteria andSVideoTitleIsNull() {
			addCriterion("s_video_title is null");
			return this;
		}

		public Criteria andSVideoTitleIsNotNull() {
			addCriterion("s_video_title is not null");
			return this;
		}

		public Criteria andSVideoTitleEqualTo(String value) {
			addCriterion("s_video_title =", value, "sVideoTitle");
			return this;
		}

		public Criteria andSVideoTitleNotEqualTo(String value) {
			addCriterion("s_video_title <>", value, "sVideoTitle");
			return this;
		}

		public Criteria andSVideoTitleGreaterThan(String value) {
			addCriterion("s_video_title >", value, "sVideoTitle");
			return this;
		}

		public Criteria andSVideoTitleGreaterThanOrEqualTo(String value) {
			addCriterion("s_video_title >=", value, "sVideoTitle");
			return this;
		}

		public Criteria andSVideoTitleLessThan(String value) {
			addCriterion("s_video_title <", value, "sVideoTitle");
			return this;
		}

		public Criteria andSVideoTitleLessThanOrEqualTo(String value) {
			addCriterion("s_video_title <=", value, "sVideoTitle");
			return this;
		}

		public Criteria andSVideoTitleLike(String value) {
			addCriterion("s_video_title like", value, "sVideoTitle");
			return this;
		}

		public Criteria andSVideoTitleNotLike(String value) {
			addCriterion("s_video_title not like", value, "sVideoTitle");
			return this;
		}

		public Criteria andSVideoTitleIn(List values) {
			addCriterion("s_video_title in", values, "sVideoTitle");
			return this;
		}

		public Criteria andSVideoTitleNotIn(List values) {
			addCriterion("s_video_title not in", values, "sVideoTitle");
			return this;
		}

		public Criteria andSVideoTitleBetween(String value1, String value2) {
			addCriterion("s_video_title between", value1, value2, "sVideoTitle");
			return this;
		}

		public Criteria andSVideoTitleNotBetween(String value1, String value2) {
			addCriterion("s_video_title not between", value1, value2,
					"sVideoTitle");
			return this;
		}

		public Criteria andSVideoUrlIsNull() {
			addCriterion("s_video_url is null");
			return this;
		}

		public Criteria andSVideoUrlIsNotNull() {
			addCriterion("s_video_url is not null");
			return this;
		}

		public Criteria andSVideoUrlEqualTo(String value) {
			addCriterion("s_video_url =", value, "sVideoUrl");
			return this;
		}

		public Criteria andSVideoUrlNotEqualTo(String value) {
			addCriterion("s_video_url <>", value, "sVideoUrl");
			return this;
		}

		public Criteria andSVideoUrlGreaterThan(String value) {
			addCriterion("s_video_url >", value, "sVideoUrl");
			return this;
		}

		public Criteria andSVideoUrlGreaterThanOrEqualTo(String value) {
			addCriterion("s_video_url >=", value, "sVideoUrl");
			return this;
		}

		public Criteria andSVideoUrlLessThan(String value) {
			addCriterion("s_video_url <", value, "sVideoUrl");
			return this;
		}

		public Criteria andSVideoUrlLessThanOrEqualTo(String value) {
			addCriterion("s_video_url <=", value, "sVideoUrl");
			return this;
		}

		public Criteria andSVideoUrlLike(String value) {
			addCriterion("s_video_url like", value, "sVideoUrl");
			return this;
		}

		public Criteria andSVideoUrlNotLike(String value) {
			addCriterion("s_video_url not like", value, "sVideoUrl");
			return this;
		}

		public Criteria andSVideoUrlIn(List values) {
			addCriterion("s_video_url in", values, "sVideoUrl");
			return this;
		}

		public Criteria andSVideoUrlNotIn(List values) {
			addCriterion("s_video_url not in", values, "sVideoUrl");
			return this;
		}

		public Criteria andSVideoUrlBetween(String value1, String value2) {
			addCriterion("s_video_url between", value1, value2, "sVideoUrl");
			return this;
		}

		public Criteria andSVideoUrlNotBetween(String value1, String value2) {
			addCriterion("s_video_url not between", value1, value2, "sVideoUrl");
			return this;
		}

		public Criteria andSSaleLabelIsNull() {
			addCriterion("s_sale_label is null");
			return this;
		}

		public Criteria andSSaleLabelIsNotNull() {
			addCriterion("s_sale_label is not null");
			return this;
		}

		public Criteria andSSaleLabelEqualTo(String value) {
			addCriterion("s_sale_label =", value, "sSaleLabel");
			return this;
		}

		public Criteria andSSaleLabelNotEqualTo(String value) {
			addCriterion("s_sale_label <>", value, "sSaleLabel");
			return this;
		}

		public Criteria andSSaleLabelGreaterThan(String value) {
			addCriterion("s_sale_label >", value, "sSaleLabel");
			return this;
		}

		public Criteria andSSaleLabelGreaterThanOrEqualTo(String value) {
			addCriterion("s_sale_label >=", value, "sSaleLabel");
			return this;
		}

		public Criteria andSSaleLabelLessThan(String value) {
			addCriterion("s_sale_label <", value, "sSaleLabel");
			return this;
		}

		public Criteria andSSaleLabelLessThanOrEqualTo(String value) {
			addCriterion("s_sale_label <=", value, "sSaleLabel");
			return this;
		}

		public Criteria andSSaleLabelLike(String value) {
			addCriterion("s_sale_label like", value, "sSaleLabel");
			return this;
		}

		public Criteria andSSaleLabelNotLike(String value) {
			addCriterion("s_sale_label not like", value, "sSaleLabel");
			return this;
		}

		public Criteria andSSaleLabelIn(List values) {
			addCriterion("s_sale_label in", values, "sSaleLabel");
			return this;
		}

		public Criteria andSSaleLabelNotIn(List values) {
			addCriterion("s_sale_label not in", values, "sSaleLabel");
			return this;
		}

		public Criteria andSSaleLabelBetween(String value1, String value2) {
			addCriterion("s_sale_label between", value1, value2, "sSaleLabel");
			return this;
		}

		public Criteria andSSaleLabelNotBetween(String value1, String value2) {
			addCriterion("s_sale_label not between", value1, value2,
					"sSaleLabel");
			return this;
		}

		public Criteria andIAggregateQuantityIsNull() {
			addCriterion("i_aggregate_quantity is null");
			return this;
		}

		public Criteria andIAggregateQuantityIsNotNull() {
			addCriterion("i_aggregate_quantity is not null");
			return this;
		}

		public Criteria andIAggregateQuantityEqualTo(Integer value) {
			addCriterion("i_aggregate_quantity =", value, "iAggregateQuantity");
			return this;
		}

		public Criteria andIAggregateQuantityNotEqualTo(Integer value) {
			addCriterion("i_aggregate_quantity <>", value, "iAggregateQuantity");
			return this;
		}

		public Criteria andIAggregateQuantityGreaterThan(Integer value) {
			addCriterion("i_aggregate_quantity >", value, "iAggregateQuantity");
			return this;
		}

		public Criteria andIAggregateQuantityGreaterThanOrEqualTo(Integer value) {
			addCriterion("i_aggregate_quantity >=", value, "iAggregateQuantity");
			return this;
		}

		public Criteria andIAggregateQuantityLessThan(Integer value) {
			addCriterion("i_aggregate_quantity <", value, "iAggregateQuantity");
			return this;
		}

		public Criteria andIAggregateQuantityLessThanOrEqualTo(Integer value) {
			addCriterion("i_aggregate_quantity <=", value, "iAggregateQuantity");
			return this;
		}

		public Criteria andIAggregateQuantityIn(List values) {
			addCriterion("i_aggregate_quantity in", values,
					"iAggregateQuantity");
			return this;
		}

		public Criteria andIAggregateQuantityNotIn(List values) {
			addCriterion("i_aggregate_quantity not in", values,
					"iAggregateQuantity");
			return this;
		}

		public Criteria andIAggregateQuantityBetween(Integer value1,
				Integer value2) {
			addCriterion("i_aggregate_quantity between", value1, value2,
					"iAggregateQuantity");
			return this;
		}

		public Criteria andIAggregateQuantityNotBetween(Integer value1,
				Integer value2) {
			addCriterion("i_aggregate_quantity not between", value1, value2,
					"iAggregateQuantity");
			return this;
		}

		public Criteria andIPurchaseCountIsNull() {
			addCriterion("i_purchase_count is null");
			return this;
		}

		public Criteria andIPurchaseCountIsNotNull() {
			addCriterion("i_purchase_count is not null");
			return this;
		}

		public Criteria andIPurchaseCountEqualTo(Integer value) {
			addCriterion("i_purchase_count =", value, "iPurchaseCount");
			return this;
		}

		public Criteria andIPurchaseCountNotEqualTo(Integer value) {
			addCriterion("i_purchase_count <>", value, "iPurchaseCount");
			return this;
		}

		public Criteria andIPurchaseCountGreaterThan(Integer value) {
			addCriterion("i_purchase_count >", value, "iPurchaseCount");
			return this;
		}

		public Criteria andIPurchaseCountGreaterThanOrEqualTo(Integer value) {
			addCriterion("i_purchase_count >=", value, "iPurchaseCount");
			return this;
		}

		public Criteria andIPurchaseCountLessThan(Integer value) {
			addCriterion("i_purchase_count <", value, "iPurchaseCount");
			return this;
		}

		public Criteria andIPurchaseCountLessThanOrEqualTo(Integer value) {
			addCriterion("i_purchase_count <=", value, "iPurchaseCount");
			return this;
		}

		public Criteria andIPurchaseCountIn(List values) {
			addCriterion("i_purchase_count in", values, "iPurchaseCount");
			return this;
		}

		public Criteria andIPurchaseCountNotIn(List values) {
			addCriterion("i_purchase_count not in", values, "iPurchaseCount");
			return this;
		}

		public Criteria andIPurchaseCountBetween(Integer value1, Integer value2) {
			addCriterion("i_purchase_count between", value1, value2,
					"iPurchaseCount");
			return this;
		}

		public Criteria andIPurchaseCountNotBetween(Integer value1,
				Integer value2) {
			addCriterion("i_purchase_count not between", value1, value2,
					"iPurchaseCount");
			return this;
		}

		public Criteria andIViewCountIsNull() {
			addCriterion("i_view_count is null");
			return this;
		}

		public Criteria andIViewCountIsNotNull() {
			addCriterion("i_view_count is not null");
			return this;
		}

		public Criteria andIViewCountEqualTo(Integer value) {
			addCriterion("i_view_count =", value, "iViewCount");
			return this;
		}

		public Criteria andIViewCountNotEqualTo(Integer value) {
			addCriterion("i_view_count <>", value, "iViewCount");
			return this;
		}

		public Criteria andIViewCountGreaterThan(Integer value) {
			addCriterion("i_view_count >", value, "iViewCount");
			return this;
		}

		public Criteria andIViewCountGreaterThanOrEqualTo(Integer value) {
			addCriterion("i_view_count >=", value, "iViewCount");
			return this;
		}

		public Criteria andIViewCountLessThan(Integer value) {
			addCriterion("i_view_count <", value, "iViewCount");
			return this;
		}

		public Criteria andIViewCountLessThanOrEqualTo(Integer value) {
			addCriterion("i_view_count <=", value, "iViewCount");
			return this;
		}

		public Criteria andIViewCountIn(List values) {
			addCriterion("i_view_count in", values, "iViewCount");
			return this;
		}

		public Criteria andIViewCountNotIn(List values) {
			addCriterion("i_view_count not in", values, "iViewCount");
			return this;
		}

		public Criteria andIViewCountBetween(Integer value1, Integer value2) {
			addCriterion("i_view_count between", value1, value2, "iViewCount");
			return this;
		}

		public Criteria andIViewCountNotBetween(Integer value1, Integer value2) {
			addCriterion("i_view_count not between", value1, value2,
					"iViewCount");
			return this;
		}

		public Criteria andBStockControlIsNull() {
			addCriterion("b_stock_control is null");
			return this;
		}

		public Criteria andBStockControlIsNotNull() {
			addCriterion("b_stock_control is not null");
			return this;
		}

		public Criteria andBStockControlEqualTo(Boolean value) {
			addCriterion("b_stock_control =", value, "bStockControl");
			return this;
		}

		public Criteria andBStockControlNotEqualTo(Boolean value) {
			addCriterion("b_stock_control <>", value, "bStockControl");
			return this;
		}

		public Criteria andBStockControlGreaterThan(Boolean value) {
			addCriterion("b_stock_control >", value, "bStockControl");
			return this;
		}

		public Criteria andBStockControlGreaterThanOrEqualTo(Boolean value) {
			addCriterion("b_stock_control >=", value, "bStockControl");
			return this;
		}

		public Criteria andBStockControlLessThan(Boolean value) {
			addCriterion("b_stock_control <", value, "bStockControl");
			return this;
		}

		public Criteria andBStockControlLessThanOrEqualTo(Boolean value) {
			addCriterion("b_stock_control <=", value, "bStockControl");
			return this;
		}

		public Criteria andBStockControlIn(List values) {
			addCriterion("b_stock_control in", values, "bStockControl");
			return this;
		}

		public Criteria andBStockControlNotIn(List values) {
			addCriterion("b_stock_control not in", values, "bStockControl");
			return this;
		}

		public Criteria andBStockControlBetween(Boolean value1, Boolean value2) {
			addCriterion("b_stock_control between", value1, value2,
					"bStockControl");
			return this;
		}

		public Criteria andBStockControlNotBetween(Boolean value1,
				Boolean value2) {
			addCriterion("b_stock_control not between", value1, value2,
					"bStockControl");
			return this;
		}

		public Criteria andBUseOptionsIsNull() {
			addCriterion("b_use_options is null");
			return this;
		}

		public Criteria andBUseOptionsIsNotNull() {
			addCriterion("b_use_options is not null");
			return this;
		}

		public Criteria andBUseOptionsEqualTo(Boolean value) {
			addCriterion("b_use_options =", value, "bUseOptions");
			return this;
		}

		public Criteria andBUseOptionsNotEqualTo(Boolean value) {
			addCriterion("b_use_options <>", value, "bUseOptions");
			return this;
		}

		public Criteria andBUseOptionsGreaterThan(Boolean value) {
			addCriterion("b_use_options >", value, "bUseOptions");
			return this;
		}

		public Criteria andBUseOptionsGreaterThanOrEqualTo(Boolean value) {
			addCriterion("b_use_options >=", value, "bUseOptions");
			return this;
		}

		public Criteria andBUseOptionsLessThan(Boolean value) {
			addCriterion("b_use_options <", value, "bUseOptions");
			return this;
		}

		public Criteria andBUseOptionsLessThanOrEqualTo(Boolean value) {
			addCriterion("b_use_options <=", value, "bUseOptions");
			return this;
		}

		public Criteria andBUseOptionsIn(List values) {
			addCriterion("b_use_options in", values, "bUseOptions");
			return this;
		}

		public Criteria andBUseOptionsNotIn(List values) {
			addCriterion("b_use_options not in", values, "bUseOptions");
			return this;
		}

		public Criteria andBUseOptionsBetween(Boolean value1, Boolean value2) {
			addCriterion("b_use_options between", value1, value2, "bUseOptions");
			return this;
		}

		public Criteria andBUseOptionsNotBetween(Boolean value1, Boolean value2) {
			addCriterion("b_use_options not between", value1, value2,
					"bUseOptions");
			return this;
		}

		public Criteria andBTaxableIsNull() {
			addCriterion("b_taxable is null");
			return this;
		}

		public Criteria andBTaxableIsNotNull() {
			addCriterion("b_taxable is not null");
			return this;
		}

		public Criteria andBTaxableEqualTo(Boolean value) {
			addCriterion("b_taxable =", value, "bTaxable");
			return this;
		}

		public Criteria andBTaxableNotEqualTo(Boolean value) {
			addCriterion("b_taxable <>", value, "bTaxable");
			return this;
		}

		public Criteria andBTaxableGreaterThan(Boolean value) {
			addCriterion("b_taxable >", value, "bTaxable");
			return this;
		}

		public Criteria andBTaxableGreaterThanOrEqualTo(Boolean value) {
			addCriterion("b_taxable >=", value, "bTaxable");
			return this;
		}

		public Criteria andBTaxableLessThan(Boolean value) {
			addCriterion("b_taxable <", value, "bTaxable");
			return this;
		}

		public Criteria andBTaxableLessThanOrEqualTo(Boolean value) {
			addCriterion("b_taxable <=", value, "bTaxable");
			return this;
		}

		public Criteria andBTaxableIn(List values) {
			addCriterion("b_taxable in", values, "bTaxable");
			return this;
		}

		public Criteria andBTaxableNotIn(List values) {
			addCriterion("b_taxable not in", values, "bTaxable");
			return this;
		}

		public Criteria andBTaxableBetween(Boolean value1, Boolean value2) {
			addCriterion("b_taxable between", value1, value2, "bTaxable");
			return this;
		}

		public Criteria andBTaxableNotBetween(Boolean value1, Boolean value2) {
			addCriterion("b_taxable not between", value1, value2, "bTaxable");
			return this;
		}

		public Criteria andBFeaturedIsNull() {
			addCriterion("b_featured is null");
			return this;
		}

		public Criteria andBFeaturedIsNotNull() {
			addCriterion("b_featured is not null");
			return this;
		}

		public Criteria andBFeaturedEqualTo(Boolean value) {
			addCriterion("b_featured =", value, "bFeatured");
			return this;
		}

		public Criteria andBFeaturedNotEqualTo(Boolean value) {
			addCriterion("b_featured <>", value, "bFeatured");
			return this;
		}

		public Criteria andBFeaturedGreaterThan(Boolean value) {
			addCriterion("b_featured >", value, "bFeatured");
			return this;
		}

		public Criteria andBFeaturedGreaterThanOrEqualTo(Boolean value) {
			addCriterion("b_featured >=", value, "bFeatured");
			return this;
		}

		public Criteria andBFeaturedLessThan(Boolean value) {
			addCriterion("b_featured <", value, "bFeatured");
			return this;
		}

		public Criteria andBFeaturedLessThanOrEqualTo(Boolean value) {
			addCriterion("b_featured <=", value, "bFeatured");
			return this;
		}

		public Criteria andBFeaturedIn(List values) {
			addCriterion("b_featured in", values, "bFeatured");
			return this;
		}

		public Criteria andBFeaturedNotIn(List values) {
			addCriterion("b_featured not in", values, "bFeatured");
			return this;
		}

		public Criteria andBFeaturedBetween(Boolean value1, Boolean value2) {
			addCriterion("b_featured between", value1, value2, "bFeatured");
			return this;
		}

		public Criteria andBFeaturedNotBetween(Boolean value1, Boolean value2) {
			addCriterion("b_featured not between", value1, value2, "bFeatured");
			return this;
		}
	}
}