package com.mobicart.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;





public class PushNotificationExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table push_notification
     *
     * @ibatorgenerated Thu Feb 24 10:25:32 IST 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table push_notification
     *
     * @ibatorgenerated Thu Feb 24 10:25:32 IST 2011
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table push_notification
     *
     * @ibatorgenerated Thu Feb 24 10:25:32 IST 2011
     */
    public PushNotificationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table push_notification
     *
     * @ibatorgenerated Thu Feb 24 10:25:32 IST 2011
     */
    protected PushNotificationExample(PushNotificationExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table push_notification
     *
     * @ibatorgenerated Thu Feb 24 10:25:32 IST 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table push_notification
     *
     * @ibatorgenerated Thu Feb 24 10:25:32 IST 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table push_notification
     *
     * @ibatorgenerated Thu Feb 24 10:25:32 IST 2011
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table push_notification
     *
     * @ibatorgenerated Thu Feb 24 10:25:32 IST 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table push_notification
     *
     * @ibatorgenerated Thu Feb 24 10:25:32 IST 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table push_notification
     *
     * @ibatorgenerated Thu Feb 24 10:25:32 IST 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table push_notification
     *
     * @ibatorgenerated Thu Feb 24 10:25:32 IST 2011
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table push_notification
     *
     * @ibatorgenerated Thu Feb 24 10:25:32 IST 2011
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andAppIdIsNull() {
            addCriterion("app_id is null");
            return this;
        }

        public Criteria andAppIdIsNotNull() {
            addCriterion("app_id is not null");
            return this;
        }

        public Criteria andAppIdEqualTo(Long value) {
            addCriterion("app_id =", value, "appId");
            return this;
        }

        public Criteria andAppIdNotEqualTo(Long value) {
            addCriterion("app_id <>", value, "appId");
            return this;
        }

        public Criteria andAppIdGreaterThan(Long value) {
            addCriterion("app_id >", value, "appId");
            return this;
        }

        public Criteria andAppIdGreaterThanOrEqualTo(Long value) {
            addCriterion("app_id >=", value, "appId");
            return this;
        }

        public Criteria andAppIdLessThan(Long value) {
            addCriterion("app_id <", value, "appId");
            return this;
        }

        public Criteria andAppIdLessThanOrEqualTo(Long value) {
            addCriterion("app_id <=", value, "appId");
            return this;
        }

        public Criteria andAppIdIn(List<Long> values) {
            addCriterion("app_id in", values, "appId");
            return this;
        }

        public Criteria andAppIdNotIn(List<Long> values) {
            addCriterion("app_id not in", values, "appId");
            return this;
        }

        public Criteria andAppIdBetween(Long value1, Long value2) {
            addCriterion("app_id between", value1, value2, "appId");
            return this;
        }

        public Criteria andAppIdNotBetween(Long value1, Long value2) {
            addCriterion("app_id not between", value1, value2, "appId");
            return this;
        }

        
        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return this;
        }
        
        
        public Criteria andMessageIsNull() {
            addCriterion("message is null");
            return this;
        }

        public Criteria andMessageIsNotNull() {
            addCriterion("message is not null");
            return this;
        }

        public Criteria andMessageEqualTo(String value) {
            addCriterion("message =", value, "message");
            return this;
        }

        public Criteria andMessageNotEqualTo(String value) {
            addCriterion("message <>", value, "message");
            return this;
        }

        public Criteria andMessageGreaterThan(String value) {
            addCriterion("message >", value, "message");
            return this;
        }

        public Criteria andMessageGreaterThanOrEqualTo(String value) {
            addCriterion("message >=", value, "message");
            return this;
        }

        public Criteria andMessageLessThan(String value) {
            addCriterion("message <", value, "message");
            return this;
        }

        public Criteria andMessageLessThanOrEqualTo(String value) {
            addCriterion("message <=", value, "message");
            return this;
        }

        public Criteria andMessageLike(String value) {
            addCriterion("message like", value, "message");
            return this;
        }

        public Criteria andMessageNotLike(String value) {
            addCriterion("message not like", value, "message");
            return this;
        }

        public Criteria andMessageIn(List<String> values) {
            addCriterion("message in", values, "message");
            return this;
        }

        public Criteria andMessageNotIn(List<String> values) {
            addCriterion("message not in", values, "message");
            return this;
        }

        public Criteria andMessageBetween(String value1, String value2) {
            addCriterion("message between", value1, value2, "message");
            return this;
        }

        public Criteria andMessageNotBetween(String value1, String value2) {
            addCriterion("message not between", value1, value2, "message");
            return this;
        }

        
        public Criteria andSendToIsNull() {
            addCriterion("send_to is null");
            return this;
        }

        public Criteria andSendToIsNotNull() {
            addCriterion("send_to is not null");
            return this;
        }

        public Criteria andSendToEqualTo(String value) {
            addCriterion("send_to =", value, "sendTo");
            return this;
        }

        public Criteria andSendToNotEqualTo(String value) {
            addCriterion("send_to <>", value, "sendTo");
            return this;
        }

        public Criteria andSendToGreaterThan(String value) {
            addCriterion("send_to >", value, "sendTo");
            return this;
        }

        public Criteria andSendToGreaterThanOrEqualTo(String value) {
            addCriterion("send_to >=", value, "sendTo");
            return this;
        }

        public Criteria andSendToLessThan(String value) {
            addCriterion("send_to <", value, "sendTo");
            return this;
        }

        public Criteria andSendToLessThanOrEqualTo(String value) {
            addCriterion("send_to <=", value, "sendTo");
            return this;
        }

        public Criteria andSendToLike(String value) {
            addCriterion("send_to like", value, "sendTo");
            return this;
        }

        public Criteria andSendToNotLike(String value) {
            addCriterion("send_to not like", value, "sendTo");
            return this;
        }

        public Criteria andSendToIn(List<String> values) {
            addCriterion("send_to in", values, "sendTo");
            return this;
        }

        public Criteria andSendToNotIn(List<String> values) {
            addCriterion("send_to not in", values, "sendTo");
            return this;
        }

        public Criteria andSendToBetween(String value1, String value2) {
            addCriterion("send_to between", value1, value2, "sendTo");
            return this;
        }

        public Criteria andSendToNotBetween(String value1, String value2) {
            addCriterion("send_to not between", value1, value2, "sendTo");
            return this;
        }
        
        public Criteria andZipcodeIsNull() {
            addCriterion("zipcode is null");
            return this;
        }

        public Criteria andZipcodeIsNotNull() {
            addCriterion("zipcode is not null");
            return this;
        }

        public Criteria andZipcodeEqualTo(String value) {
            addCriterion("zipcode =", value, "zipcode");
            return this;
        }

        public Criteria andZipcodeNotEqualTo(String value) {
            addCriterion("zipcode <>", value, "zipcode");
            return this;
        }

        public Criteria andZipcodeGreaterThan(String value) {
            addCriterion("zipcode >", value, "zipcode");
            return this;
        }

        public Criteria andZipcodeGreaterThanOrEqualTo(String value) {
            addCriterion("zipcode >=", value, "zipcode");
            return this;
        }

        public Criteria andZipcodeLessThan(String value) {
            addCriterion("zipcode <", value, "zipcode");
            return this;
        }

        public Criteria andZipcodeLessThanOrEqualTo(String value) {
            addCriterion("zipcode <=", value, "zipcode");
            return this;
        }

        public Criteria andZipcodeLike(String value) {
            addCriterion("zipcode like", value, "zipcode");
            return this;
        }

        public Criteria andZipcodeNotLike(String value) {
            addCriterion("zipcode not like", value, "zipcode");
            return this;
        }

        public Criteria andZipcodeIn(List<String> values) {
            addCriterion("zipcode in", values, "zipcode");
            return this;
        }

        public Criteria andZipcodeNotIn(List<String> values) {
            addCriterion("zipcode not in", values, "zipcode");
            return this;
        }

        public Criteria andZipcodeBetween(String value1, String value2) {
            addCriterion("zipcode between", value1, value2, "zipcode");
            return this;
        }

        public Criteria andZipcodeNotBetween(String value1, String value2) {
            addCriterion("zipcode not between", value1, value2, "zipcode");
            return this;
        }
        
        
        public Criteria andRadiusIsNull() {
            addCriterion("radius is null");
            return this;
        }

        public Criteria andRadiusIsNotNull() {
            addCriterion("radius is not null");
            return this;
        }

        public Criteria andRadiusEqualTo(String value) {
            addCriterion("radius =", value, "radius");
            return this;
        }

        public Criteria andRadiusNotEqualTo(String value) {
            addCriterion("radius <>", value, "radius");
            return this;
        }

        public Criteria andRadiusGreaterThan(String value) {
            addCriterion("radius >", value, "radius");
            return this;
        }

        public Criteria andRadiusGreaterThanOrEqualTo(String value) {
            addCriterion("radius >=", value, "radius");
            return this;
        }

        public Criteria andRadiusLessThan(String value) {
            addCriterion("radius <", value, "radius");
            return this;
        }

        public Criteria andRadiusLessThanOrEqualTo(String value) {
            addCriterion("radius <=", value, "radius");
            return this;
        }

        public Criteria andRadiusLike(String value) {
            addCriterion("radius like", value, "radius");
            return this;
        }

        public Criteria andRadiusNotLike(String value) {
            addCriterion("radius not like", value, "radius");
            return this;
        }

        public Criteria andRadiusIn(List<String> values) {
            addCriterion("radius in", values, "radius");
            return this;
        }

        public Criteria andRadiusNotIn(List<String> values) {
            addCriterion("radius not in", values, "radius");
            return this;
        }

        public Criteria andRadiusBetween(String value1, String value2) {
            addCriterion("radius between", value1, value2, "radius");
            return this;
        }

        public Criteria andRadiusNotBetween(String value1, String value2) {
            addCriterion("radius not between", value1, value2, "radius");
            return this;
        }
        
        
 	   
        public Criteria andUnitsIsNull() {
            addCriterion("units is null");
            return this;
        }

        public Criteria andUnitsIsNotNull() {
            addCriterion("units is not null");
            return this;
        }

        public Criteria andUnitsEqualTo(String value) {
            addCriterion("units =", value, "units");
            return this;
        }

        public Criteria andUnitsNotEqualTo(String value) {
            addCriterion("units <>", value, "units");
            return this;
        }

        public Criteria andUnitsGreaterThan(String value) {
            addCriterion("units >", value, "units");
            return this;
        }

        public Criteria andUnitsGreaterThanOrEqualTo(String value) {
            addCriterion("units >=", value, "units");
            return this;
        }

        public Criteria andUnitsLessThan(String value) {
            addCriterion("units <", value, "units");
            return this;
        }

        public Criteria andUnitsLessThanOrEqualTo(String value) {
            addCriterion("units <=", value, "units");
            return this;
        }

        public Criteria andUnitsLike(String value) {
            addCriterion("units like", value, "units");
            return this;
        }

        public Criteria andUnitsNotLike(String value) {
            addCriterion("units not like", value, "units");
            return this;
        }

        public Criteria andUnitsIn(List<String> values) {
            addCriterion("units in", values, "units");
            return this;
        }

        public Criteria andUnitsNotIn(List<String> values) {
            addCriterion("units not in", values, "units");
            return this;
        }

        public Criteria andUnitsBetween(String value1, String value2) {
            addCriterion("units between", value1, value2, "units");
            return this;
        }

        public Criteria andUnitsNotBetween(String value1, String value2) {
            addCriterion("units not between", value1, value2, "units");
            return this;
        }
        
        
        public Criteria andDateIsNull() {
            addCriterion("date is null");
            return this;
        }

        public Criteria andDateIsNotNull() {
            addCriterion("date is not null");
            return this;
        }

        public Criteria andDateEqualTo(Date value) {
            addCriterion("date =", value, "date");
            return this;
        }

        public Criteria andDateNotEqualTo(Date value) {
            addCriterion("date <>", value, "date");
            return this;
        }

        public Criteria andDateGreaterThan(Date value) {
            addCriterion("date >", value, "date");
            return this;
        }

        public Criteria andDateGreaterThanOrEqualTo(Date value) {
            addCriterion("date >=", value, "date");
            return this;
        }

        public Criteria andDateLessThan(Date value) {
            addCriterion("date <", value, "date");
            return this;
        }

        public Criteria andDateLessThanOrEqualTo(Date value) {
            addCriterion("date <=", value, "date");
            return this;
        }

        public Criteria andDateIn(List<Date> values) {
            addCriterion("date in", values, "date");
            return this;
        }

        public Criteria andDateNotIn(List<Date> values) {
            addCriterion("date not in", values, "date");
            return this;
        }

        public Criteria andDateBetween(Date value1, Date value2) {
            addCriterion("date between", value1, value2, "date");
            return this;
        }

        public Criteria andDateNotBetween(Date value1, Date value2) {
            addCriterion("date not between", value1, value2, "date");
            return this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return this;
        }

        public Criteria andNotifiedCountIsNull() {
            addCriterion("notified_count is null");
            return this;
        }

        public Criteria andNotifiedCountIsNotNull() {
            addCriterion("notified_count is not null");
            return this;
        }

        public Criteria andNotifiedCountEqualTo(Integer value) {
            addCriterion("notified_count =", value, "notifiedCount");
            return this;
        }

        public Criteria andNotifiedCountNotEqualTo(Integer value) {
            addCriterion("notified_count <>", value, "notifiedCount");
            return this;
        }

        public Criteria andNotifiedCountGreaterThan(Integer value) {
            addCriterion("notified_count >", value, "notifiedCount");
            return this;
        }

        public Criteria andNotifiedCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("notified_count >=", value, "notifiedCount");
            return this;
        }

        public Criteria andNotifiedCountLessThan(Integer value) {
            addCriterion("notified_count <", value, "notifiedCount");
            return this;
        }

        public Criteria andNotifiedCountLessThanOrEqualTo(Integer value) {
            addCriterion("notified_count <=", value, "notifiedCount");
            return this;
        }

        public Criteria andNotifiedCountIn(List<Integer> values) {
            addCriterion("notified_count in", values, "notifiedCount");
            return this;
        }

        public Criteria andNotifiedCountNotIn(List<Integer> values) {
            addCriterion("notified_count not in", values, "notifiedCount");
            return this;
        }

        public Criteria andNotifiedCountBetween(Integer value1, Integer value2) {
            addCriterion("notified_count between", value1, value2, "notifiedCount");
            return this;
        }

        public Criteria andNotifiedCountNotBetween(Integer value1, Integer value2) {
            addCriterion("notified_count not between", value1, value2, "notifiedCount");
            return this;
        }
    }
}