package com.mobicart.model;

import java.math.BigDecimal;

public class Shipping {
 
    /**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column shipping.id
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	private Long id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column shipping.store_id
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	private Long storeId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column shipping.territory_id
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	private Long territoryId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column shipping.state_id
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	private Long stateId;
	
	
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column shipping.s_country
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	private String sCountry;
	
	
	private String sState;
	
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column shipping.f_alone
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	private BigDecimal fAlone;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column shipping.f_others
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	private BigDecimal fOthers;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column shipping.f_shipping_tax
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	private BigDecimal fShippingTax;


//	private Boolean bTaxShipping;
	

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column shipping.id
	 * @return  the value of shipping.id
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column shipping.id
	 * @param id  the value for shipping.id
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column shipping.store_id
	 * @return  the value of shipping.store_id
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	public Long getStoreId() {
		return storeId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column shipping.store_id
	 * @param storeId  the value for shipping.store_id
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	public void setStoreId(Long storeId) {
		this.storeId = storeId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column shipping.territory_id
	 * @return  the value of shipping.territory_id
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	public Long getTerritoryId() {
		return territoryId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column shipping.territory_id
	 * @param territoryId  the value for shipping.territory_id
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	public void setTerritoryId(Long territoryId) {
		this.territoryId = territoryId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column shipping.state_id
	 * @return  the value of shipping.state_id
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	public Long getStateId() {
		return stateId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column shipping.state_id
	 * @param stateId  the value for shipping.state_id
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	public void setStateId(Long stateId) {
		this.stateId = stateId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column shipping.s_country
	 * @return  the value of shipping.s_country
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	public String getsCountry() {
		return sCountry;
	}

	
	
	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column shipping.s_country
	 * @param sCountry  the value for shipping.s_country
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	public void setsCountry(String sCountry) {
		this.sCountry = sCountry == null ? null : sCountry.trim();
	}

	
	
	
	public String getsState() {
		return sState;
	}

	public void setsState(String sState) {
		this.sState = sState;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column shipping.f_alone
	 * @return  the value of shipping.f_alone
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	public BigDecimal getfAlone() {
		return fAlone;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column shipping.f_alone
	 * @param fAlone  the value for shipping.f_alone
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	public void setfAlone(BigDecimal fAlone) {
		this.fAlone = fAlone;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column shipping.f_others
	 * @return  the value of shipping.f_others
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	public BigDecimal getfOthers() {
		return fOthers;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column shipping.f_others
	 * @param fOthers  the value for shipping.f_others
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	public void setfOthers(BigDecimal fOthers) {
		this.fOthers = fOthers;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column shipping.f_shipping_tax
	 * @return  the value of shipping.f_shipping_tax
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	public BigDecimal getfShippingTax() {
		return fShippingTax;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column shipping.f_shipping_tax
	 * @param fShippingTax  the value for shipping.f_shipping_tax
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	public void setfShippingTax(BigDecimal fShippingTax) {
		this.fShippingTax = fShippingTax;
	}

    
       
  
	public Shipping() {
		super();

	}

	public Shipping(Long id) {
		super();
		this.id = id;
	}

	

    public Shipping(Long id, Long storeId, Long territoryId, Long stateId,
			String sCountry, String sState, BigDecimal fAlone,
			BigDecimal fOthers, BigDecimal fShippingTax) {
		super();
		this.id = id;
		this.storeId = storeId;
		this.territoryId = territoryId;
		this.stateId = stateId;
		this.sCountry = sCountry;
		this.sState = sState;
		this.fAlone = fAlone;
		this.fOthers = fOthers;
		this.fShippingTax = fShippingTax;
	}

    
    

	public static Shipping getDefaultValue(Long storeId, Long countryId, Long stateId){
		return new Shipping(0L,storeId,countryId,stateId,"Other","Other",BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO);
	}

	@Override
	public String toString() {
		return "Shipping [id=" + id + ", storeId=" + storeId + ", territoryId="
				+ territoryId + ", stateId=" + stateId + ", sCountry="
				+ sCountry + ", sState=" + sState + ", fAlone=" + fAlone
				+ ", fOthers=" + fOthers + ", fShippingTax=" + fShippingTax
				+ "]";
	}
	
	
	
    
}