package com.mobicart.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class StaticPageExample {

	/**
	 * This field corresponds to the database table static_pages
	 * @ibatorgenerated  Tue Oct 12 12:00:28 IST 2010
	 */
	protected String orderByClause;
	/**
	 * This field corresponds to the database table static_pages
	 * @ibatorgenerated  Tue Oct 12 12:00:28 IST 2010
	 */
	protected List oredCriteria;

	/**
	 *  This method corresponds to the database table static_pages
	 * @ibatorgenerated  Tue Oct 12 12:00:28 IST 2010
	 */
	public StaticPageExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 *  This method corresponds to the database table static_pages
	 * @ibatorgenerated  Tue Oct 12 12:00:28 IST 2010
	 */
	protected StaticPageExample(StaticPageExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 *  This method corresponds to the database table static_pages
	 * @ibatorgenerated  Tue Oct 12 12:00:28 IST 2010
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 *  This method corresponds to the database table static_pages
	 * @ibatorgenerated  Tue Oct 12 12:00:28 IST 2010
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 *  This method corresponds to the database table static_pages
	 * @ibatorgenerated  Tue Oct 12 12:00:28 IST 2010
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 *  This method corresponds to the database table static_pages
	 * @ibatorgenerated  Tue Oct 12 12:00:28 IST 2010
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 *  This method corresponds to the database table static_pages
	 * @ibatorgenerated  Tue Oct 12 12:00:28 IST 2010
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 *  This method corresponds to the database table static_pages
	 * @ibatorgenerated  Tue Oct 12 12:00:28 IST 2010
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 *  This method corresponds to the database table static_pages
	 * @ibatorgenerated  Tue Oct 12 12:00:28 IST 2010
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table static_pages
	 * @ibatorgenerated  Tue Oct 12 12:00:28 IST 2010
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return this;
		}

		public Criteria andIdIn(List values) {
			addCriterion("id in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List values) {
			addCriterion("id not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return this;
		}

		public Criteria andFeatureIdIsNull() {
			addCriterion("feature_id is null");
			return this;
		}

		public Criteria andFeatureIdIsNotNull() {
			addCriterion("feature_id is not null");
			return this;
		}

		public Criteria andFeatureIdEqualTo(Long value) {
			addCriterion("feature_id =", value, "featureId");
			return this;
		}

		public Criteria andFeatureIdNotEqualTo(Long value) {
			addCriterion("feature_id <>", value, "featureId");
			return this;
		}

		public Criteria andFeatureIdGreaterThan(Long value) {
			addCriterion("feature_id >", value, "featureId");
			return this;
		}

		public Criteria andFeatureIdGreaterThanOrEqualTo(Long value) {
			addCriterion("feature_id >=", value, "featureId");
			return this;
		}

		public Criteria andFeatureIdLessThan(Long value) {
			addCriterion("feature_id <", value, "featureId");
			return this;
		}

		public Criteria andFeatureIdLessThanOrEqualTo(Long value) {
			addCriterion("feature_id <=", value, "featureId");
			return this;
		}

		public Criteria andFeatureIdIn(List values) {
			addCriterion("feature_id in", values, "featureId");
			return this;
		}

		public Criteria andFeatureIdNotIn(List values) {
			addCriterion("feature_id not in", values, "featureId");
			return this;
		}

		public Criteria andFeatureIdBetween(Long value1, Long value2) {
			addCriterion("feature_id between", value1, value2, "featureId");
			return this;
		}

		public Criteria andFeatureIdNotBetween(Long value1, Long value2) {
			addCriterion("feature_id not between", value1, value2, "featureId");
			return this;
		}
		
		
		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return this;
		}

		public Criteria andUserIdEqualTo(Long value) {
			addCriterion("user_id =", value, "userId");
			return this;
		}

		public Criteria andUserIdNotEqualTo(Long value) {
			addCriterion("user_id <>", value, "userId");
			return this;
		}

		public Criteria andUserIdGreaterThan(Long value) {
			addCriterion("user_id >", value, "userId");
			return this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
			addCriterion("user_id >=", value, "userId");
			return this;
		}

		public Criteria andUserIdLessThan(Long value) {
			addCriterion("user_id <", value, "userId");
			return this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Long value) {
			addCriterion("user_id <=", value, "userId");
			return this;
		}

		public Criteria andUserIdIn(List values) {
			addCriterion("user_id in", values, "userId");
			return this;
		}

		public Criteria andUserIdNotIn(List values) {
			addCriterion("user_id not in", values, "userId");
			return this;
		}

		public Criteria andUserIdBetween(Long value1, Long value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return this;
		}

		public Criteria andUserIdNotBetween(Long value1, Long value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return this;
		}

		public Criteria andAppIdIsNull() {
			addCriterion("app_id is null");
			return this;
		}

		public Criteria andAppIdIsNotNull() {
			addCriterion("app_id is not null");
			return this;
		}

		public Criteria andAppIdEqualTo(Long value) {
			addCriterion("app_id =", value, "appId");
			return this;
		}

		public Criteria andAppIdNotEqualTo(Long value) {
			addCriterion("app_id <>", value, "appId");
			return this;
		}

		public Criteria andAppIdGreaterThan(Long value) {
			addCriterion("app_id >", value, "appId");
			return this;
		}

		public Criteria andAppIdGreaterThanOrEqualTo(Long value) {
			addCriterion("app_id >=", value, "appId");
			return this;
		}

		public Criteria andAppIdLessThan(Long value) {
			addCriterion("app_id <", value, "appId");
			return this;
		}

		public Criteria andAppIdLessThanOrEqualTo(Long value) {
			addCriterion("app_id <=", value, "appId");
			return this;
		}

		public Criteria andAppIdIn(List values) {
			addCriterion("app_id in", values, "appId");
			return this;
		}

		public Criteria andAppIdNotIn(List values) {
			addCriterion("app_id not in", values, "appId");
			return this;
		}

		public Criteria andAppIdBetween(Long value1, Long value2) {
			addCriterion("app_id between", value1, value2, "appId");
			return this;
		}

		public Criteria andAppIdNotBetween(Long value1, Long value2) {
			addCriterion("app_id not between", value1, value2, "appId");
			return this;
		}

		public Criteria andSNameIsNull() {
			addCriterion("s_name is null");
			return this;
		}

		public Criteria andSNameIsNotNull() {
			addCriterion("s_name is not null");
			return this;
		}

		public Criteria andSNameEqualTo(String value) {
			addCriterion("s_name =", value, "sName");
			return this;
		}

		public Criteria andSNameNotEqualTo(String value) {
			addCriterion("s_name <>", value, "sName");
			return this;
		}

		public Criteria andSNameGreaterThan(String value) {
			addCriterion("s_name >", value, "sName");
			return this;
		}

		public Criteria andSNameGreaterThanOrEqualTo(String value) {
			addCriterion("s_name >=", value, "sName");
			return this;
		}

		public Criteria andSNameLessThan(String value) {
			addCriterion("s_name <", value, "sName");
			return this;
		}

		public Criteria andSNameLessThanOrEqualTo(String value) {
			addCriterion("s_name <=", value, "sName");
			return this;
		}

		public Criteria andSNameLike(String value) {
			addCriterion("s_name like", value, "sName");
			return this;
		}

		public Criteria andSNameNotLike(String value) {
			addCriterion("s_name not like", value, "sName");
			return this;
		}

		public Criteria andSNameIn(List values) {
			addCriterion("s_name in", values, "sName");
			return this;
		}

		public Criteria andSNameNotIn(List values) {
			addCriterion("s_name not in", values, "sName");
			return this;
		}

		public Criteria andSNameBetween(String value1, String value2) {
			addCriterion("s_name between", value1, value2, "sName");
			return this;
		}

		public Criteria andSNameNotBetween(String value1, String value2) {
			addCriterion("s_name not between", value1, value2, "sName");
			return this;
		}

		public Criteria andSTitleIsNull() {
			addCriterion("s_title is null");
			return this;
		}

		public Criteria andSTitleIsNotNull() {
			addCriterion("s_title is not null");
			return this;
		}

		public Criteria andSTitleEqualTo(String value) {
			addCriterion("s_title =", value, "sTitle");
			return this;
		}

		public Criteria andSTitleNotEqualTo(String value) {
			addCriterion("s_title <>", value, "sTitle");
			return this;
		}

		public Criteria andSTitleGreaterThan(String value) {
			addCriterion("s_title >", value, "sTitle");
			return this;
		}

		public Criteria andSTitleGreaterThanOrEqualTo(String value) {
			addCriterion("s_title >=", value, "sTitle");
			return this;
		}

		public Criteria andSTitleLessThan(String value) {
			addCriterion("s_title <", value, "sTitle");
			return this;
		}

		public Criteria andSTitleLessThanOrEqualTo(String value) {
			addCriterion("s_title <=", value, "sTitle");
			return this;
		}

		public Criteria andSTitleLike(String value) {
			addCriterion("s_title like", value, "sTitle");
			return this;
		}

		public Criteria andSTitleNotLike(String value) {
			addCriterion("s_title not like", value, "sTitle");
			return this;
		}

		public Criteria andSTitleIn(List values) {
			addCriterion("s_title in", values, "sTitle");
			return this;
		}

		public Criteria andSTitleNotIn(List values) {
			addCriterion("s_title not in", values, "sTitle");
			return this;
		}

		public Criteria andSTitleBetween(String value1, String value2) {
			addCriterion("s_title between", value1, value2, "sTitle");
			return this;
		}

		public Criteria andSTitleNotBetween(String value1, String value2) {
			addCriterion("s_title not between", value1, value2, "sTitle");
			return this;
		}

		public Criteria andBEnabledIsNull() {
			addCriterion("b_enabled is null");
			return this;
		}

		public Criteria andBEnabledIsNotNull() {
			addCriterion("b_enabled is not null");
			return this;
		}

		public Criteria andBEnabledEqualTo(Boolean value) {
			addCriterion("b_enabled =", value, "bEnabled");
			return this;
		}

		public Criteria andBEnabledNotEqualTo(Boolean value) {
			addCriterion("b_enabled <>", value, "bEnabled");
			return this;
		}

		public Criteria andBEnabledGreaterThan(Boolean value) {
			addCriterion("b_enabled >", value, "bEnabled");
			return this;
		}

		public Criteria andBEnabledGreaterThanOrEqualTo(Boolean value) {
			addCriterion("b_enabled >=", value, "bEnabled");
			return this;
		}

		public Criteria andBEnabledLessThan(Boolean value) {
			addCriterion("b_enabled <", value, "bEnabled");
			return this;
		}

		public Criteria andBEnabledLessThanOrEqualTo(Boolean value) {
			addCriterion("b_enabled <=", value, "bEnabled");
			return this;
		}

		public Criteria andBEnabledIn(List values) {
			addCriterion("b_enabled in", values, "bEnabled");
			return this;
		}

		public Criteria andBEnabledNotIn(List values) {
			addCriterion("b_enabled not in", values, "bEnabled");
			return this;
		}

		public Criteria andBEnabledBetween(Boolean value1, Boolean value2) {
			addCriterion("b_enabled between", value1, value2, "bEnabled");
			return this;
		}

		public Criteria andBEnabledNotBetween(Boolean value1, Boolean value2) {
			addCriterion("b_enabled not between", value1, value2, "bEnabled");
			return this;
		}
	}
}