package com.mobicart.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class UserExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table users
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table users
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table users
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public UserExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table users
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	protected UserExample(UserExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table users
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table users
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table users
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table users
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table users
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table users
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table users
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table users
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List dateList = new ArrayList();
			Iterator iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(((Date) iter.next()).getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andUsernameIsNull() {
			addCriterion("username is null");
			return this;
		}

		public Criteria andUsernameIsNotNull() {
			addCriterion("username is not null");
			return this;
		}

		public Criteria andUsernameEqualTo(String value) {
			addCriterion("username =", value, "username");
			return this;
		}

		public Criteria andUsernameNotEqualTo(String value) {
			addCriterion("username <>", value, "username");
			return this;
		}

		public Criteria andUsernameGreaterThan(String value) {
			addCriterion("username >", value, "username");
			return this;
		}

		public Criteria andUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("username >=", value, "username");
			return this;
		}

		public Criteria andUsernameLessThan(String value) {
			addCriterion("username <", value, "username");
			return this;
		}

		public Criteria andUsernameLessThanOrEqualTo(String value) {
			addCriterion("username <=", value, "username");
			return this;
		}

		public Criteria andUsernameLike(String value) {
			addCriterion("username like", value, "username");
			return this;
		}

		public Criteria andUsernameNotLike(String value) {
			addCriterion("username not like", value, "username");
			return this;
		}

		public Criteria andUsernameIn(List values) {
			addCriterion("username in", values, "username");
			return this;
		}

		public Criteria andUsernameNotIn(List values) {
			addCriterion("username not in", values, "username");
			return this;
		}

		public Criteria andUsernameBetween(String value1, String value2) {
			addCriterion("username between", value1, value2, "username");
			return this;
		}

		public Criteria andUsernameNotBetween(String value1, String value2) {
			addCriterion("username not between", value1, value2, "username");
			return this;
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return this;
		}

		public Criteria andIdIn(List values) {
			addCriterion("id in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List values) {
			addCriterion("id not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("password is null");
			return this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("password is not null");
			return this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("password =", value, "password");
			return this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("password <>", value, "password");
			return this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("password >", value, "password");
			return this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("password >=", value, "password");
			return this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("password <", value, "password");
			return this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("password <=", value, "password");
			return this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("password like", value, "password");
			return this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("password not like", value, "password");
			return this;
		}

		public Criteria andPasswordIn(List values) {
			addCriterion("password in", values, "password");
			return this;
		}

		public Criteria andPasswordNotIn(List values) {
			addCriterion("password not in", values, "password");
			return this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("password between", value1, value2, "password");
			return this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("password not between", value1, value2, "password");
			return this;
		}

		public Criteria andSFirstNameIsNull() {
			addCriterion("s_first_name is null");
			return this;
		}

		public Criteria andSFirstNameIsNotNull() {
			addCriterion("s_first_name is not null");
			return this;
		}

		public Criteria andSFirstNameEqualTo(String value) {
			addCriterion("s_first_name =", value, "sFirstName");
			return this;
		}

		public Criteria andSFirstNameNotEqualTo(String value) {
			addCriterion("s_first_name <>", value, "sFirstName");
			return this;
		}

		public Criteria andSFirstNameGreaterThan(String value) {
			addCriterion("s_first_name >", value, "sFirstName");
			return this;
		}

		public Criteria andSFirstNameGreaterThanOrEqualTo(String value) {
			addCriterion("s_first_name >=", value, "sFirstName");
			return this;
		}

		public Criteria andSFirstNameLessThan(String value) {
			addCriterion("s_first_name <", value, "sFirstName");
			return this;
		}

		public Criteria andSFirstNameLessThanOrEqualTo(String value) {
			addCriterion("s_first_name <=", value, "sFirstName");
			return this;
		}

		public Criteria andSFirstNameLike(String value) {
			addCriterion("s_first_name like", value, "sFirstName");
			return this;
		}

		public Criteria andSFirstNameNotLike(String value) {
			addCriterion("s_first_name not like", value, "sFirstName");
			return this;
		}

		public Criteria andSFirstNameIn(List values) {
			addCriterion("s_first_name in", values, "sFirstName");
			return this;
		}

		public Criteria andSFirstNameNotIn(List values) {
			addCriterion("s_first_name not in", values, "sFirstName");
			return this;
		}

		public Criteria andSFirstNameBetween(String value1, String value2) {
			addCriterion("s_first_name between", value1, value2, "sFirstName");
			return this;
		}

		public Criteria andSFirstNameNotBetween(String value1, String value2) {
			addCriterion("s_first_name not between", value1, value2,
					"sFirstName");
			return this;
		}

		public Criteria andSLastNameIsNull() {
			addCriterion("s_last_name is null");
			return this;
		}

		public Criteria andSLastNameIsNotNull() {
			addCriterion("s_last_name is not null");
			return this;
		}

		public Criteria andSLastNameEqualTo(String value) {
			addCriterion("s_last_name =", value, "sLastName");
			return this;
		}

		public Criteria andSLastNameNotEqualTo(String value) {
			addCriterion("s_last_name <>", value, "sLastName");
			return this;
		}

		public Criteria andSLastNameGreaterThan(String value) {
			addCriterion("s_last_name >", value, "sLastName");
			return this;
		}

		public Criteria andSLastNameGreaterThanOrEqualTo(String value) {
			addCriterion("s_last_name >=", value, "sLastName");
			return this;
		}

		public Criteria andSLastNameLessThan(String value) {
			addCriterion("s_last_name <", value, "sLastName");
			return this;
		}

		public Criteria andSLastNameLessThanOrEqualTo(String value) {
			addCriterion("s_last_name <=", value, "sLastName");
			return this;
		}

		public Criteria andSLastNameLike(String value) {
			addCriterion("s_last_name like", value, "sLastName");
			return this;
		}

		public Criteria andSLastNameNotLike(String value) {
			addCriterion("s_last_name not like", value, "sLastName");
			return this;
		}

		public Criteria andSLastNameIn(List values) {
			addCriterion("s_last_name in", values, "sLastName");
			return this;
		}

		public Criteria andSLastNameNotIn(List values) {
			addCriterion("s_last_name not in", values, "sLastName");
			return this;
		}

		public Criteria andSLastNameBetween(String value1, String value2) {
			addCriterion("s_last_name between", value1, value2, "sLastName");
			return this;
		}

		public Criteria andSLastNameNotBetween(String value1, String value2) {
			addCriterion("s_last_name not between", value1, value2, "sLastName");
			return this;
		}

		public Criteria andDBirthdayIsNull() {
			addCriterion("d_birthday is null");
			return this;
		}

		public Criteria andDBirthdayIsNotNull() {
			addCriterion("d_birthday is not null");
			return this;
		}

		public Criteria andDBirthdayEqualTo(Date value) {
			addCriterionForJDBCDate("d_birthday =", value, "dBirthday");
			return this;
		}

		public Criteria andDBirthdayNotEqualTo(Date value) {
			addCriterionForJDBCDate("d_birthday <>", value, "dBirthday");
			return this;
		}

		public Criteria andDBirthdayGreaterThan(Date value) {
			addCriterionForJDBCDate("d_birthday >", value, "dBirthday");
			return this;
		}

		public Criteria andDBirthdayGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("d_birthday >=", value, "dBirthday");
			return this;
		}

		public Criteria andDBirthdayLessThan(Date value) {
			addCriterionForJDBCDate("d_birthday <", value, "dBirthday");
			return this;
		}

		public Criteria andDBirthdayLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("d_birthday <=", value, "dBirthday");
			return this;
		}

		public Criteria andDBirthdayIn(List values) {
			addCriterionForJDBCDate("d_birthday in", values, "dBirthday");
			return this;
		}

		public Criteria andDBirthdayNotIn(List values) {
			addCriterionForJDBCDate("d_birthday not in", values, "dBirthday");
			return this;
		}

		public Criteria andDBirthdayBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("d_birthday between", value1, value2,
					"dBirthday");
			return this;
		}

		public Criteria andDBirthdayNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("d_birthday not between", value1, value2,
					"dBirthday");
			return this;
		}

		public Criteria andSCompanyRegNoIsNull() {
			addCriterion("s_company_reg_no is null");
			return this;
		}

		public Criteria andSCompanyRegNoIsNotNull() {
			addCriterion("s_company_reg_no is not null");
			return this;
		}

		public Criteria andSCompanyRegNoEqualTo(String value) {
			addCriterion("s_company_reg_no =", value, "sCompanyRegNo");
			return this;
		}

		public Criteria andSCompanyRegNoNotEqualTo(String value) {
			addCriterion("s_company_reg_no <>", value, "sCompanyRegNo");
			return this;
		}

		public Criteria andSCompanyRegNoGreaterThan(String value) {
			addCriterion("s_company_reg_no >", value, "sCompanyRegNo");
			return this;
		}

		public Criteria andSCompanyRegNoGreaterThanOrEqualTo(String value) {
			addCriterion("s_company_reg_no >=", value, "sCompanyRegNo");
			return this;
		}

		public Criteria andSCompanyRegNoLessThan(String value) {
			addCriterion("s_company_reg_no <", value, "sCompanyRegNo");
			return this;
		}

		public Criteria andSCompanyRegNoLessThanOrEqualTo(String value) {
			addCriterion("s_company_reg_no <=", value, "sCompanyRegNo");
			return this;
		}

		public Criteria andSCompanyRegNoLike(String value) {
			addCriterion("s_company_reg_no like", value, "sCompanyRegNo");
			return this;
		}

		public Criteria andSCompanyRegNoNotLike(String value) {
			addCriterion("s_company_reg_no not like", value, "sCompanyRegNo");
			return this;
		}

		public Criteria andSCompanyRegNoIn(List values) {
			addCriterion("s_company_reg_no in", values, "sCompanyRegNo");
			return this;
		}

		public Criteria andSCompanyRegNoNotIn(List values) {
			addCriterion("s_company_reg_no not in", values, "sCompanyRegNo");
			return this;
		}

		public Criteria andSCompanyRegNoBetween(String value1, String value2) {
			addCriterion("s_company_reg_no between", value1, value2,
					"sCompanyRegNo");
			return this;
		}

		public Criteria andSCompanyRegNoNotBetween(String value1, String value2) {
			addCriterion("s_company_reg_no not between", value1, value2,
					"sCompanyRegNo");
			return this;
		}

		public Criteria andSTaxRegNoIsNull() {
			addCriterion("s_tax_reg_no is null");
			return this;
		}

		public Criteria andSTaxRegNoIsNotNull() {
			addCriterion("s_tax_reg_no is not null");
			return this;
		}

		public Criteria andSTaxRegNoEqualTo(String value) {
			addCriterion("s_tax_reg_no =", value, "sTaxRegNo");
			return this;
		}

		public Criteria andSTaxRegNoNotEqualTo(String value) {
			addCriterion("s_tax_reg_no <>", value, "sTaxRegNo");
			return this;
		}

		public Criteria andSTaxRegNoGreaterThan(String value) {
			addCriterion("s_tax_reg_no >", value, "sTaxRegNo");
			return this;
		}

		public Criteria andSTaxRegNoGreaterThanOrEqualTo(String value) {
			addCriterion("s_tax_reg_no >=", value, "sTaxRegNo");
			return this;
		}

		public Criteria andSTaxRegNoLessThan(String value) {
			addCriterion("s_tax_reg_no <", value, "sTaxRegNo");
			return this;
		}

		public Criteria andSTaxRegNoLessThanOrEqualTo(String value) {
			addCriterion("s_tax_reg_no <=", value, "sTaxRegNo");
			return this;
		}

		public Criteria andSTaxRegNoLike(String value) {
			addCriterion("s_tax_reg_no like", value, "sTaxRegNo");
			return this;
		}

		public Criteria andSTaxRegNoNotLike(String value) {
			addCriterion("s_tax_reg_no not like", value, "sTaxRegNo");
			return this;
		}

		public Criteria andSTaxRegNoIn(List values) {
			addCriterion("s_tax_reg_no in", values, "sTaxRegNo");
			return this;
		}

		public Criteria andSTaxRegNoNotIn(List values) {
			addCriterion("s_tax_reg_no not in", values, "sTaxRegNo");
			return this;
		}

		public Criteria andSTaxRegNoBetween(String value1, String value2) {
			addCriterion("s_tax_reg_no between", value1, value2, "sTaxRegNo");
			return this;
		}

		public Criteria andSTaxRegNoNotBetween(String value1, String value2) {
			addCriterion("s_tax_reg_no not between", value1, value2,
					"sTaxRegNo");
			return this;
		}

		public Criteria andSCompanyLogoIsNull() {
			addCriterion("s_company_logo is null");
			return this;
		}

		public Criteria andSCompanyLogoIsNotNull() {
			addCriterion("s_company_logo is not null");
			return this;
		}

		public Criteria andSCompanyLogoEqualTo(String value) {
			addCriterion("s_company_logo =", value, "sCompanyLogo");
			return this;
		}

		public Criteria andSCompanyLogoNotEqualTo(String value) {
			addCriterion("s_company_logo <>", value, "sCompanyLogo");
			return this;
		}

		public Criteria andSCompanyLogoGreaterThan(String value) {
			addCriterion("s_company_logo >", value, "sCompanyLogo");
			return this;
		}

		public Criteria andSCompanyLogoGreaterThanOrEqualTo(String value) {
			addCriterion("s_company_logo >=", value, "sCompanyLogo");
			return this;
		}

		public Criteria andSCompanyLogoLessThan(String value) {
			addCriterion("s_company_logo <", value, "sCompanyLogo");
			return this;
		}

		public Criteria andSCompanyLogoLessThanOrEqualTo(String value) {
			addCriterion("s_company_logo <=", value, "sCompanyLogo");
			return this;
		}

		public Criteria andSCompanyLogoLike(String value) {
			addCriterion("s_company_logo like", value, "sCompanyLogo");
			return this;
		}

		public Criteria andSCompanyLogoNotLike(String value) {
			addCriterion("s_company_logo not like", value, "sCompanyLogo");
			return this;
		}

		public Criteria andSCompanyLogoIn(List values) {
			addCriterion("s_company_logo in", values, "sCompanyLogo");
			return this;
		}

		public Criteria andSCompanyLogoNotIn(List values) {
			addCriterion("s_company_logo not in", values, "sCompanyLogo");
			return this;
		}

		public Criteria andSCompanyLogoBetween(String value1, String value2) {
			addCriterion("s_company_logo between", value1, value2,
					"sCompanyLogo");
			return this;
		}

		public Criteria andSCompanyLogoNotBetween(String value1, String value2) {
			addCriterion("s_company_logo not between", value1, value2,
					"sCompanyLogo");
			return this;
		}

		public Criteria andSPaypalAddressIsNull() {
			addCriterion("s_paypal_address is null");
			return this;
		}

		public Criteria andSPaypalAddressIsNotNull() {
			addCriterion("s_paypal_address is not null");
			return this;
		}

		public Criteria andSPaypalAddressEqualTo(String value) {
			addCriterion("s_paypal_address =", value, "sPaypalAddress");
			return this;
		}

		public Criteria andSPaypalAddressNotEqualTo(String value) {
			addCriterion("s_paypal_address <>", value, "sPaypalAddress");
			return this;
		}

		public Criteria andSPaypalAddressGreaterThan(String value) {
			addCriterion("s_paypal_address >", value, "sPaypalAddress");
			return this;
		}

		public Criteria andSPaypalAddressGreaterThanOrEqualTo(String value) {
			addCriterion("s_paypal_address >=", value, "sPaypalAddress");
			return this;
		}

		public Criteria andSPaypalAddressLessThan(String value) {
			addCriterion("s_paypal_address <", value, "sPaypalAddress");
			return this;
		}

		public Criteria andSPaypalAddressLessThanOrEqualTo(String value) {
			addCriterion("s_paypal_address <=", value, "sPaypalAddress");
			return this;
		}

		public Criteria andSPaypalAddressLike(String value) {
			addCriterion("s_paypal_address like", value, "sPaypalAddress");
			return this;
		}

		public Criteria andSPaypalAddressNotLike(String value) {
			addCriterion("s_paypal_address not like", value, "sPaypalAddress");
			return this;
		}

		public Criteria andSPaypalAddressIn(List values) {
			addCriterion("s_paypal_address in", values, "sPaypalAddress");
			return this;
		}

		public Criteria andSPaypalAddressNotIn(List values) {
			addCriterion("s_paypal_address not in", values, "sPaypalAddress");
			return this;
		}

		public Criteria andSPaypalAddressBetween(String value1, String value2) {
			addCriterion("s_paypal_address between", value1, value2,
					"sPaypalAddress");
			return this;
		}

		public Criteria andSPaypalAddressNotBetween(String value1, String value2) {
			addCriterion("s_paypal_address not between", value1, value2,
					"sPaypalAddress");
			return this;
		}

		public Criteria andSHeardFromIsNull() {
			addCriterion("s_heard_from is null");
			return this;
		}

		public Criteria andSHeardFromIsNotNull() {
			addCriterion("s_heard_from is not null");
			return this;
		}

		public Criteria andSHeardFromEqualTo(String value) {
			addCriterion("s_heard_from =", value, "sHeardFrom");
			return this;
		}

		public Criteria andSHeardFromNotEqualTo(String value) {
			addCriterion("s_heard_from <>", value, "sHeardFrom");
			return this;
		}

		public Criteria andSHeardFromGreaterThan(String value) {
			addCriterion("s_heard_from >", value, "sHeardFrom");
			return this;
		}

		public Criteria andSHeardFromGreaterThanOrEqualTo(String value) {
			addCriterion("s_heard_from >=", value, "sHeardFrom");
			return this;
		}

		public Criteria andSHeardFromLessThan(String value) {
			addCriterion("s_heard_from <", value, "sHeardFrom");
			return this;
		}

		public Criteria andSHeardFromLessThanOrEqualTo(String value) {
			addCriterion("s_heard_from <=", value, "sHeardFrom");
			return this;
		}

		public Criteria andSHeardFromLike(String value) {
			addCriterion("s_heard_from like", value, "sHeardFrom");
			return this;
		}

		public Criteria andSHeardFromNotLike(String value) {
			addCriterion("s_heard_from not like", value, "sHeardFrom");
			return this;
		}

		public Criteria andSHeardFromIn(List values) {
			addCriterion("s_heard_from in", values, "sHeardFrom");
			return this;
		}

		public Criteria andSHeardFromNotIn(List values) {
			addCriterion("s_heard_from not in", values, "sHeardFrom");
			return this;
		}

		public Criteria andSHeardFromBetween(String value1, String value2) {
			addCriterion("s_heard_from between", value1, value2, "sHeardFrom");
			return this;
		}

		public Criteria andSHeardFromNotBetween(String value1, String value2) {
			addCriterion("s_heard_from not between", value1, value2,
					"sHeardFrom");
			return this;
		}

		public Criteria andSCouponCodeIsNull() {
			addCriterion("s_coupon_code is null");
			return this;
		}

		public Criteria andSCouponCodeIsNotNull() {
			addCriterion("s_coupon_code is not null");
			return this;
		}

		public Criteria andSCouponCodeEqualTo(String value) {
			addCriterion("s_coupon_code =", value, "sCouponCode");
			return this;
		}

		public Criteria andSCouponCodeNotEqualTo(String value) {
			addCriterion("s_coupon_code <>", value, "sCouponCode");
			return this;
		}

		public Criteria andSCouponCodeGreaterThan(String value) {
			addCriterion("s_coupon_code >", value, "sCouponCode");
			return this;
		}

		public Criteria andSCouponCodeGreaterThanOrEqualTo(String value) {
			addCriterion("s_coupon_code >=", value, "sCouponCode");
			return this;
		}

		public Criteria andSCouponCodeLessThan(String value) {
			addCriterion("s_coupon_code <", value, "sCouponCode");
			return this;
		}

		public Criteria andSCouponCodeLessThanOrEqualTo(String value) {
			addCriterion("s_coupon_code <=", value, "sCouponCode");
			return this;
		}

		public Criteria andSCouponCodeLike(String value) {
			addCriterion("s_coupon_code like", value, "sCouponCode");
			return this;
		}

		public Criteria andSCouponCodeNotLike(String value) {
			addCriterion("s_coupon_code not like", value, "sCouponCode");
			return this;
		}

		public Criteria andSCouponCodeIn(List values) {
			addCriterion("s_coupon_code in", values, "sCouponCode");
			return this;
		}

		public Criteria andSCouponCodeNotIn(List values) {
			addCriterion("s_coupon_code not in", values, "sCouponCode");
			return this;
		}

		public Criteria andSCouponCodeBetween(String value1, String value2) {
			addCriterion("s_coupon_code between", value1, value2, "sCouponCode");
			return this;
		}

		public Criteria andSCouponCodeNotBetween(String value1, String value2) {
			addCriterion("s_coupon_code not between", value1, value2,
					"sCouponCode");
			return this;
		}

		public Criteria andSAffiliateCodeIsNull() {
			addCriterion("s_affiliate_code is null");
			return this;
		}

		public Criteria andSAffiliateCodeIsNotNull() {
			addCriterion("s_affiliate_code is not null");
			return this;
		}

		public Criteria andSAffiliateCodeEqualTo(String value) {
			addCriterion("s_affiliate_code =", value, "sAffiliateCode");
			return this;
		}

		public Criteria andSAffiliateCodeNotEqualTo(String value) {
			addCriterion("s_affiliate_code <>", value, "sAffiliateCode");
			return this;
		}

		public Criteria andSAffiliateCodeGreaterThan(String value) {
			addCriterion("s_affiliate_code >", value, "sAffiliateCode");
			return this;
		}

		public Criteria andSAffiliateCodeGreaterThanOrEqualTo(String value) {
			addCriterion("s_affiliate_code >=", value, "sAffiliateCode");
			return this;
		}

		public Criteria andSAffiliateCodeLessThan(String value) {
			addCriterion("s_affiliate_code <", value, "sAffiliateCode");
			return this;
		}

		public Criteria andSAffiliateCodeLessThanOrEqualTo(String value) {
			addCriterion("s_affiliate_code <=", value, "sAffiliateCode");
			return this;
		}

		public Criteria andSAffiliateCodeLike(String value) {
			addCriterion("s_affiliate_code like", value, "sAffiliateCode");
			return this;
		}

		public Criteria andSAffiliateCodeNotLike(String value) {
			addCriterion("s_affiliate_code not like", value, "sAffiliateCode");
			return this;
		}

		public Criteria andSAffiliateCodeIn(List values) {
			addCriterion("s_affiliate_code in", values, "sAffiliateCode");
			return this;
		}

		public Criteria andSAffiliateCodeNotIn(List values) {
			addCriterion("s_affiliate_code not in", values, "sAffiliateCode");
			return this;
		}

		public Criteria andSAffiliateCodeBetween(String value1, String value2) {
			addCriterion("s_affiliate_code between", value1, value2,
					"sAffiliateCode");
			return this;
		}

		public Criteria andSAffiliateCodeNotBetween(String value1, String value2) {
			addCriterion("s_affiliate_code not between", value1, value2,
					"sAffiliateCode");
			return this;
		}

		public Criteria andDJoinedOnIsNull() {
			addCriterion("d_joined_on is null");
			return this;
		}

		public Criteria andDJoinedOnIsNotNull() {
			addCriterion("d_joined_on is not null");
			return this;
		}

		public Criteria andDJoinedOnEqualTo(Date value) {
			addCriterion("d_joined_on =", value, "dJoinedOn");
			return this;
		}

		public Criteria andDJoinedOnNotEqualTo(Date value) {
			addCriterion("d_joined_on <>", value, "dJoinedOn");
			return this;
		}

		public Criteria andDJoinedOnGreaterThan(Date value) {
			addCriterion("d_joined_on >", value, "dJoinedOn");
			return this;
		}

		public Criteria andDJoinedOnGreaterThanOrEqualTo(Date value) {
			addCriterion("d_joined_on >=", value, "dJoinedOn");
			return this;
		}

		public Criteria andDJoinedOnLessThan(Date value) {
			addCriterion("d_joined_on <", value, "dJoinedOn");
			return this;
		}

		public Criteria andDJoinedOnLessThanOrEqualTo(Date value) {
			addCriterion("d_joined_on <=", value, "dJoinedOn");
			return this;
		}

		public Criteria andDJoinedOnIn(List values) {
			addCriterion("d_joined_on in", values, "dJoinedOn");
			return this;
		}

		public Criteria andDJoinedOnNotIn(List values) {
			addCriterion("d_joined_on not in", values, "dJoinedOn");
			return this;
		}

		public Criteria andDJoinedOnBetween(Date value1, Date value2) {
			addCriterion("d_joined_on between", value1, value2, "dJoinedOn");
			return this;
		}

		public Criteria andDJoinedOnNotBetween(Date value1, Date value2) {
			addCriterion("d_joined_on not between", value1, value2, "dJoinedOn");
			return this;
		}

		public Criteria andDUpdatedOnIsNull() {
			addCriterion("d_updated_on is null");
			return this;
		}

		public Criteria andDUpdatedOnIsNotNull() {
			addCriterion("d_updated_on is not null");
			return this;
		}

		public Criteria andDUpdatedOnEqualTo(Date value) {
			addCriterion("d_updated_on =", value, "dUpdatedOn");
			return this;
		}

		public Criteria andDUpdatedOnNotEqualTo(Date value) {
			addCriterion("d_updated_on <>", value, "dUpdatedOn");
			return this;
		}

		public Criteria andDUpdatedOnGreaterThan(Date value) {
			addCriterion("d_updated_on >", value, "dUpdatedOn");
			return this;
		}

		public Criteria andDUpdatedOnGreaterThanOrEqualTo(Date value) {
			addCriterion("d_updated_on >=", value, "dUpdatedOn");
			return this;
		}

		public Criteria andDUpdatedOnLessThan(Date value) {
			addCriterion("d_updated_on <", value, "dUpdatedOn");
			return this;
		}

		public Criteria andDUpdatedOnLessThanOrEqualTo(Date value) {
			addCriterion("d_updated_on <=", value, "dUpdatedOn");
			return this;
		}

		public Criteria andDUpdatedOnIn(List values) {
			addCriterion("d_updated_on in", values, "dUpdatedOn");
			return this;
		}

		public Criteria andDUpdatedOnNotIn(List values) {
			addCriterion("d_updated_on not in", values, "dUpdatedOn");
			return this;
		}

		public Criteria andDUpdatedOnBetween(Date value1, Date value2) {
			addCriterion("d_updated_on between", value1, value2, "dUpdatedOn");
			return this;
		}

		public Criteria andDUpdatedOnNotBetween(Date value1, Date value2) {
			addCriterion("d_updated_on not between", value1, value2,
					"dUpdatedOn");
			return this;
		}

		public Criteria andSActivationKeyIsNull() {
			addCriterion("s_activation_key is null");
			return this;
		}

		public Criteria andSActivationKeyIsNotNull() {
			addCriterion("s_activation_key is not null");
			return this;
		}

		public Criteria andSActivationKeyEqualTo(String value) {
			addCriterion("s_activation_key =", value, "sActivationKey");
			return this;
		}

		public Criteria andSActivationKeyNotEqualTo(String value) {
			addCriterion("s_activation_key <>", value, "sActivationKey");
			return this;
		}

		public Criteria andSActivationKeyGreaterThan(String value) {
			addCriterion("s_activation_key >", value, "sActivationKey");
			return this;
		}

		public Criteria andSActivationKeyGreaterThanOrEqualTo(String value) {
			addCriterion("s_activation_key >=", value, "sActivationKey");
			return this;
		}

		public Criteria andSActivationKeyLessThan(String value) {
			addCriterion("s_activation_key <", value, "sActivationKey");
			return this;
		}

		public Criteria andSActivationKeyLessThanOrEqualTo(String value) {
			addCriterion("s_activation_key <=", value, "sActivationKey");
			return this;
		}

		public Criteria andSActivationKeyLike(String value) {
			addCriterion("s_activation_key like", value, "sActivationKey");
			return this;
		}

		public Criteria andSActivationKeyNotLike(String value) {
			addCriterion("s_activation_key not like", value, "sActivationKey");
			return this;
		}

		public Criteria andSActivationKeyIn(List values) {
			addCriterion("s_activation_key in", values, "sActivationKey");
			return this;
		}

		public Criteria andSActivationKeyNotIn(List values) {
			addCriterion("s_activation_key not in", values, "sActivationKey");
			return this;
		}

		public Criteria andSActivationKeyBetween(String value1, String value2) {
			addCriterion("s_activation_key between", value1, value2,
					"sActivationKey");
			return this;
		}

		public Criteria andSActivationKeyNotBetween(String value1, String value2) {
			addCriterion("s_activation_key not between", value1, value2,
					"sActivationKey");
			return this;
		}

		public Criteria andBCustomCopyrightPageIsNull() {
			addCriterion("b_custom_copyright_page is null");
			return this;
		}

		public Criteria andBCustomCopyrightPageIsNotNull() {
			addCriterion("b_custom_copyright_page is not null");
			return this;
		}

		public Criteria andBCustomCopyrightPageEqualTo(Boolean value) {
			addCriterion("b_custom_copyright_page =", value,
					"bCustomCopyrightPage");
			return this;
		}

		public Criteria andBCustomCopyrightPageNotEqualTo(Boolean value) {
			addCriterion("b_custom_copyright_page <>", value,
					"bCustomCopyrightPage");
			return this;
		}

		public Criteria andBCustomCopyrightPageGreaterThan(Boolean value) {
			addCriterion("b_custom_copyright_page >", value,
					"bCustomCopyrightPage");
			return this;
		}

		public Criteria andBCustomCopyrightPageGreaterThanOrEqualTo(
				Boolean value) {
			addCriterion("b_custom_copyright_page >=", value,
					"bCustomCopyrightPage");
			return this;
		}

		public Criteria andBCustomCopyrightPageLessThan(Boolean value) {
			addCriterion("b_custom_copyright_page <", value,
					"bCustomCopyrightPage");
			return this;
		}

		public Criteria andBCustomCopyrightPageLessThanOrEqualTo(Boolean value) {
			addCriterion("b_custom_copyright_page <=", value,
					"bCustomCopyrightPage");
			return this;
		}

		public Criteria andBCustomCopyrightPageIn(List values) {
			addCriterion("b_custom_copyright_page in", values,
					"bCustomCopyrightPage");
			return this;
		}

		public Criteria andBCustomCopyrightPageNotIn(List values) {
			addCriterion("b_custom_copyright_page not in", values,
					"bCustomCopyrightPage");
			return this;
		}

		public Criteria andBCustomCopyrightPageBetween(Boolean value1,
				Boolean value2) {
			addCriterion("b_custom_copyright_page between", value1, value2,
					"bCustomCopyrightPage");
			return this;
		}

		public Criteria andBCustomCopyrightPageNotBetween(Boolean value1,
				Boolean value2) {
			addCriterion("b_custom_copyright_page not between", value1, value2,
					"bCustomCopyrightPage");
			return this;
		}

		public Criteria andSWebappUrlMappingIsNull() {
			addCriterion("s_webapp_url_mapping is null");
			return this;
		}

		public Criteria andSWebappUrlMappingIsNotNull() {
			addCriterion("s_webapp_url_mapping is not null");
			return this;
		}

		public Criteria andSWebappUrlMappingEqualTo(String value) {
			addCriterion("s_webapp_url_mapping =", value, "sWebappUrlMapping");
			return this;
		}

		public Criteria andSWebappUrlMappingNotEqualTo(String value) {
			addCriterion("s_webapp_url_mapping <>", value, "sWebappUrlMapping");
			return this;
		}

		public Criteria andSWebappUrlMappingGreaterThan(String value) {
			addCriterion("s_webapp_url_mapping >", value, "sWebappUrlMapping");
			return this;
		}

		public Criteria andSWebappUrlMappingGreaterThanOrEqualTo(String value) {
			addCriterion("s_webapp_url_mapping >=", value, "sWebappUrlMapping");
			return this;
		}

		public Criteria andSWebappUrlMappingLessThan(String value) {
			addCriterion("s_webapp_url_mapping <", value, "sWebappUrlMapping");
			return this;
		}

		public Criteria andSWebappUrlMappingLessThanOrEqualTo(String value) {
			addCriterion("s_webapp_url_mapping <=", value, "sWebappUrlMapping");
			return this;
		}

		public Criteria andSWebappUrlMappingLike(String value) {
			addCriterion("s_webapp_url_mapping like", value,
					"sWebappUrlMapping");
			return this;
		}

		public Criteria andSWebappUrlMappingNotLike(String value) {
			addCriterion("s_webapp_url_mapping not like", value,
					"sWebappUrlMapping");
			return this;
		}

		public Criteria andSWebappUrlMappingIn(List values) {
			addCriterion("s_webapp_url_mapping in", values, "sWebappUrlMapping");
			return this;
		}

		public Criteria andSWebappUrlMappingNotIn(List values) {
			addCriterion("s_webapp_url_mapping not in", values,
					"sWebappUrlMapping");
			return this;
		}

		public Criteria andSWebappUrlMappingBetween(String value1, String value2) {
			addCriterion("s_webapp_url_mapping between", value1, value2,
					"sWebappUrlMapping");
			return this;
		}

		public Criteria andSWebappUrlMappingNotBetween(String value1,
				String value2) {
			addCriterion("s_webapp_url_mapping not between", value1, value2,
					"sWebappUrlMapping");
			return this;
		}

		public Criteria andSWebappDomainNameIsNull() {
			addCriterion("s_webapp_domain_name is null");
			return this;
		}

		public Criteria andSWebappDomainNameIsNotNull() {
			addCriterion("s_webapp_domain_name is not null");
			return this;
		}

		public Criteria andSWebappDomainNameEqualTo(String value) {
			addCriterion("s_webapp_domain_name =", value, "sWebappDomainName");
			return this;
		}

		public Criteria andSWebappDomainNameNotEqualTo(String value) {
			addCriterion("s_webapp_domain_name <>", value, "sWebappDomainName");
			return this;
		}

		public Criteria andSWebappDomainNameGreaterThan(String value) {
			addCriterion("s_webapp_domain_name >", value, "sWebappDomainName");
			return this;
		}

		public Criteria andSWebappDomainNameGreaterThanOrEqualTo(String value) {
			addCriterion("s_webapp_domain_name >=", value, "sWebappDomainName");
			return this;
		}

		public Criteria andSWebappDomainNameLessThan(String value) {
			addCriterion("s_webapp_domain_name <", value, "sWebappDomainName");
			return this;
		}

		public Criteria andSWebappDomainNameLessThanOrEqualTo(String value) {
			addCriterion("s_webapp_domain_name <=", value, "sWebappDomainName");
			return this;
		}

		public Criteria andSWebappDomainNameLike(String value) {
			addCriterion("s_webapp_domain_name like", value,
					"sWebappDomainName");
			return this;
		}

		public Criteria andSWebappDomainNameNotLike(String value) {
			addCriterion("s_webapp_domain_name not like", value,
					"sWebappDomainName");
			return this;
		}

		public Criteria andSWebappDomainNameIn(List values) {
			addCriterion("s_webapp_domain_name in", values, "sWebappDomainName");
			return this;
		}

		public Criteria andSWebappDomainNameNotIn(List values) {
			addCriterion("s_webapp_domain_name not in", values,
					"sWebappDomainName");
			return this;
		}

		public Criteria andSWebappDomainNameBetween(String value1, String value2) {
			addCriterion("s_webapp_domain_name between", value1, value2,
					"sWebappDomainName");
			return this;
		}

		public Criteria andSWebappDomainNameNotBetween(String value1,
				String value2) {
			addCriterion("s_webapp_domain_name not between", value1, value2,
					"sWebappDomainName");
			return this;
		}

		public Criteria andBIphoneIsNull() {
			addCriterion("b_iphone is null");
			return this;
		}

		public Criteria andBIphoneIsNotNull() {
			addCriterion("b_iphone is not null");
			return this;
		}

		public Criteria andBIphoneEqualTo(Boolean value) {
			addCriterion("b_iphone =", value, "bIphone");
			return this;
		}

		public Criteria andBIphoneNotEqualTo(Boolean value) {
			addCriterion("b_iphone <>", value, "bIphone");
			return this;
		}

		public Criteria andBIphoneGreaterThan(Boolean value) {
			addCriterion("b_iphone >", value, "bIphone");
			return this;
		}

		public Criteria andBIphoneGreaterThanOrEqualTo(Boolean value) {
			addCriterion("b_iphone >=", value, "bIphone");
			return this;
		}

		public Criteria andBIphoneLessThan(Boolean value) {
			addCriterion("b_iphone <", value, "bIphone");
			return this;
		}

		public Criteria andBIphoneLessThanOrEqualTo(Boolean value) {
			addCriterion("b_iphone <=", value, "bIphone");
			return this;
		}

		public Criteria andBIphoneIn(List values) {
			addCriterion("b_iphone in", values, "bIphone");
			return this;
		}

		public Criteria andBIphoneNotIn(List values) {
			addCriterion("b_iphone not in", values, "bIphone");
			return this;
		}

		public Criteria andBIphoneBetween(Boolean value1, Boolean value2) {
			addCriterion("b_iphone between", value1, value2, "bIphone");
			return this;
		}

		public Criteria andBIphoneNotBetween(Boolean value1, Boolean value2) {
			addCriterion("b_iphone not between", value1, value2, "bIphone");
			return this;
		}

		public Criteria andBIpadIsNull() {
			addCriterion("b_ipad is null");
			return this;
		}

		public Criteria andBIpadIsNotNull() {
			addCriterion("b_ipad is not null");
			return this;
		}

		public Criteria andBIpadEqualTo(Boolean value) {
			addCriterion("b_ipad =", value, "bIpad");
			return this;
		}

		public Criteria andBIpadNotEqualTo(Boolean value) {
			addCriterion("b_ipad <>", value, "bIpad");
			return this;
		}

		public Criteria andBIpadGreaterThan(Boolean value) {
			addCriterion("b_ipad >", value, "bIpad");
			return this;
		}

		public Criteria andBIpadGreaterThanOrEqualTo(Boolean value) {
			addCriterion("b_ipad >=", value, "bIpad");
			return this;
		}

		public Criteria andBIpadLessThan(Boolean value) {
			addCriterion("b_ipad <", value, "bIpad");
			return this;
		}

		public Criteria andBIpadLessThanOrEqualTo(Boolean value) {
			addCriterion("b_ipad <=", value, "bIpad");
			return this;
		}

		public Criteria andBIpadIn(List values) {
			addCriterion("b_ipad in", values, "bIpad");
			return this;
		}

		public Criteria andBIpadNotIn(List values) {
			addCriterion("b_ipad not in", values, "bIpad");
			return this;
		}

		public Criteria andBIpadBetween(Boolean value1, Boolean value2) {
			addCriterion("b_ipad between", value1, value2, "bIpad");
			return this;
		}

		public Criteria andBIpadNotBetween(Boolean value1, Boolean value2) {
			addCriterion("b_ipad not between", value1, value2, "bIpad");
			return this;
		}

		public Criteria andBAndroidIsNull() {
			addCriterion("b_android is null");
			return this;
		}

		public Criteria andBAndroidIsNotNull() {
			addCriterion("b_android is not null");
			return this;
		}

		public Criteria andBAndroidEqualTo(Boolean value) {
			addCriterion("b_android =", value, "bAndroid");
			return this;
		}

		public Criteria andBAndroidNotEqualTo(Boolean value) {
			addCriterion("b_android <>", value, "bAndroid");
			return this;
		}

		public Criteria andBAndroidGreaterThan(Boolean value) {
			addCriterion("b_android >", value, "bAndroid");
			return this;
		}

		public Criteria andBAndroidGreaterThanOrEqualTo(Boolean value) {
			addCriterion("b_android >=", value, "bAndroid");
			return this;
		}

		public Criteria andBAndroidLessThan(Boolean value) {
			addCriterion("b_android <", value, "bAndroid");
			return this;
		}

		public Criteria andBAndroidLessThanOrEqualTo(Boolean value) {
			addCriterion("b_android <=", value, "bAndroid");
			return this;
		}

		public Criteria andBAndroidIn(List values) {
			addCriterion("b_android in", values, "bAndroid");
			return this;
		}

		public Criteria andBAndroidNotIn(List values) {
			addCriterion("b_android not in", values, "bAndroid");
			return this;
		}

		public Criteria andBAndroidBetween(Boolean value1, Boolean value2) {
			addCriterion("b_android between", value1, value2, "bAndroid");
			return this;
		}

		public Criteria andBAndroidNotBetween(Boolean value1, Boolean value2) {
			addCriterion("b_android not between", value1, value2, "bAndroid");
			return this;
		}

		public Criteria andBWebappIsNull() {
			addCriterion("b_webapp is null");
			return this;
		}

		public Criteria andBWebappIsNotNull() {
			addCriterion("b_webapp is not null");
			return this;
		}

		public Criteria andBWebappEqualTo(Boolean value) {
			addCriterion("b_webapp =", value, "bWebapp");
			return this;
		}

		public Criteria andBWebappNotEqualTo(Boolean value) {
			addCriterion("b_webapp <>", value, "bWebapp");
			return this;
		}

		public Criteria andBWebappGreaterThan(Boolean value) {
			addCriterion("b_webapp >", value, "bWebapp");
			return this;
		}

		public Criteria andBWebappGreaterThanOrEqualTo(Boolean value) {
			addCriterion("b_webapp >=", value, "bWebapp");
			return this;
		}

		public Criteria andBWebappLessThan(Boolean value) {
			addCriterion("b_webapp <", value, "bWebapp");
			return this;
		}

		public Criteria andBWebappLessThanOrEqualTo(Boolean value) {
			addCriterion("b_webapp <=", value, "bWebapp");
			return this;
		}

		public Criteria andBWebappIn(List values) {
			addCriterion("b_webapp in", values, "bWebapp");
			return this;
		}

		public Criteria andBWebappNotIn(List values) {
			addCriterion("b_webapp not in", values, "bWebapp");
			return this;
		}

		public Criteria andBWebappBetween(Boolean value1, Boolean value2) {
			addCriterion("b_webapp between", value1, value2, "bWebapp");
			return this;
		}

		public Criteria andBWebappNotBetween(Boolean value1, Boolean value2) {
			addCriterion("b_webapp not between", value1, value2, "bWebapp");
			return this;
		}

		public Criteria andDiskSpacePricingIdIsNull() {
			addCriterion("disk_space_pricing_id is null");
			return this;
		}

		public Criteria andDiskSpacePricingIdIsNotNull() {
			addCriterion("disk_space_pricing_id is not null");
			return this;
		}

		public Criteria andDiskSpacePricingIdEqualTo(Long value) {
			addCriterion("disk_space_pricing_id =", value, "diskSpacePricingId");
			return this;
		}

		public Criteria andDiskSpacePricingIdNotEqualTo(Long value) {
			addCriterion("disk_space_pricing_id <>", value,
					"diskSpacePricingId");
			return this;
		}

		public Criteria andDiskSpacePricingIdGreaterThan(Long value) {
			addCriterion("disk_space_pricing_id >", value, "diskSpacePricingId");
			return this;
		}

		public Criteria andDiskSpacePricingIdGreaterThanOrEqualTo(Long value) {
			addCriterion("disk_space_pricing_id >=", value,
					"diskSpacePricingId");
			return this;
		}

		public Criteria andDiskSpacePricingIdLessThan(Long value) {
			addCriterion("disk_space_pricing_id <", value, "diskSpacePricingId");
			return this;
		}

		public Criteria andDiskSpacePricingIdLessThanOrEqualTo(Long value) {
			addCriterion("disk_space_pricing_id <=", value,
					"diskSpacePricingId");
			return this;
		}

		public Criteria andDiskSpacePricingIdIn(List values) {
			addCriterion("disk_space_pricing_id in", values,
					"diskSpacePricingId");
			return this;
		}

		public Criteria andDiskSpacePricingIdNotIn(List values) {
			addCriterion("disk_space_pricing_id not in", values,
					"diskSpacePricingId");
			return this;
		}

		public Criteria andDiskSpacePricingIdBetween(Long value1, Long value2) {
			addCriterion("disk_space_pricing_id between", value1, value2,
					"diskSpacePricingId");
			return this;
		}

		public Criteria andDiskSpacePricingIdNotBetween(Long value1, Long value2) {
			addCriterion("disk_space_pricing_id not between", value1, value2,
					"diskSpacePricingId");
			return this;
		}

		public Criteria andEnabledIsNull() {
			addCriterion("enabled is null");
			return this;
		}

		public Criteria andEnabledIsNotNull() {
			addCriterion("enabled is not null");
			return this;
		}

		public Criteria andEnabledEqualTo(Boolean value) {
			addCriterion("enabled =", value, "enabled");
			return this;
		}

		public Criteria andEnabledNotEqualTo(Boolean value) {
			addCriterion("enabled <>", value, "enabled");
			return this;
		}

		public Criteria andEnabledGreaterThan(Boolean value) {
			addCriterion("enabled >", value, "enabled");
			return this;
		}

		public Criteria andEnabledGreaterThanOrEqualTo(Boolean value) {
			addCriterion("enabled >=", value, "enabled");
			return this;
		}

		public Criteria andEnabledLessThan(Boolean value) {
			addCriterion("enabled <", value, "enabled");
			return this;
		}

		public Criteria andEnabledLessThanOrEqualTo(Boolean value) {
			addCriterion("enabled <=", value, "enabled");
			return this;
		}

		public Criteria andEnabledIn(List values) {
			addCriterion("enabled in", values, "enabled");
			return this;
		}

		public Criteria andEnabledNotIn(List values) {
			addCriterion("enabled not in", values, "enabled");
			return this;
		}

		public Criteria andEnabledBetween(Boolean value1, Boolean value2) {
			addCriterion("enabled between", value1, value2, "enabled");
			return this;
		}

		public Criteria andEnabledNotBetween(Boolean value1, Boolean value2) {
			addCriterion("enabled not between", value1, value2, "enabled");
			return this;
		}
		/*manualy added*/
		/*
		public Criteria andStoreProductLimitIsNull() {
			addCriterion("storeproductlimit  is null");
			return this;
		}

		public Criteria andStoreProductLimitIsNotNull() {
			addCriterion("storeproductlimit  is not null");
			return this;
		}

		public Criteria andStoreProductLimitEqualTo(Long value) {
			addCriterion("storeproductlimit  =", value, "storeproductlimit ");
			return this;
		}

		public Criteria andStoreProductLimitNotEqualTo(Long value) {
			addCriterion("storeproductlimit  <>", value, "storeproductlimit ");
			return this;
		}

		public Criteria andStoreProductLimitGreaterThan(Long value) {
			addCriterion("storeproductlimit  >", value, "storeproductlimit ");
			return this;
		}

		public Criteria andStoreProductLimitGreaterThanOrEqualTo(Long value) {
			addCriterion("storeproductlimit  >=", value, "storeproductlimit ");
			return this;
		}

		public Criteria andStoreProductLimitLessThan(Long value) {
			addCriterion("storeproductlimit  <", value, "storeproductlimit ");
			return this;
		}

		public Criteria andStoreProductLimitLessThanOrEqualTo(Long value) {
			addCriterion("storeproductlimit  <=", value, "storeproductlimit ");
			return this;
		}

		public Criteria andStoreProductLimitIn(List values) {
			addCriterion("storeproductlimit  in", values, "storeproductlimit ");
			return this;
		}

		public Criteria andStoreProductLimitNotIn(List values) {
			addCriterion("storeproductlimit  not in", values, "storeproductlimit ");
			return this;
		}

		public Criteria andStoreProductLimitBetween(Long value1, Long value2) {
			addCriterion("storeproductlimit  between", value1, value2, "storeproductlimit ");
			return this;
		}

		public Criteria andStoreProductLimitNotBetween(Long value1, Long value2) {
			addCriterion("storeproductlimit  not between", value1, value2, "storeproductlimit ");
			return this;
		}

	*/	
	}
}