package com.mobicart.model;

import java.io.Serializable;
import java.util.Date;
import java.util.HashMap;

import com.mobicart.util.FileUtils;

public class User implements Serializable  {
 
	
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 2697824598834893718L;

	private String username;
	
	private Long id;
	
	private String password;
	
	private String sFirstName;
	
	private String sLastName;
	
	private Date dBirthday;
	
	private String sCompanyRegNo;
	
	private String sTaxRegNo;
	
	private String sCompanyLogo;
	
	private String sCompanyLogoWebsite;
	
	private String sPaypalAddress;
	
	private String sHeardFrom;
	
	private String sCouponCode;
	
	private String sAffiliateCode;
	
	private Date dJoinedOn;
	
	private Date dUpdatedOn;
	
	private String sActivationKey;
	
	private boolean bCustomCopyrightPage;
	
	
	private Long diskSpacePricingId;

	private boolean enabled;
	
	private String sCurrency;
	
	private Integer iProductCount;
	
	private String countryName;
	
	private Long storeId;
	
	private String sWebappUrlMapping;

	private String sWebappDomainName;

	private boolean bIphone;

	private boolean bIpad;
	
	private boolean bAndroid;

	private boolean bWebapp;

	private String storeName;
	private Integer storeProductLimit;
	private String phoneNo;
	
	private String orderReturnUrl;
	

	public String getOrderReturnUrl() {
		return orderReturnUrl;
	}


	public void setOrderReturnUrl(String orderReturnUrl) {
		this.orderReturnUrl = orderReturnUrl;
	}
	
	public String getPhoneNo() {
		if(phoneNo==null)
			phoneNo="";
		
		return phoneNo;
	}


	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}


	private HashMap<String, String> defaultLabelKeyValuesMap;
	
	


	/**
	 * This method returns the value of the database column users.username
	 * @return  the value of users.username
	 */
	public String getUsername() {
		return username;
	}


	public Long getDiskSpacePricingId() {
		return diskSpacePricingId;
	}


	public void setDiskSpacePricingId(Long diskSpacePricingId) {
		this.diskSpacePricingId = diskSpacePricingId;
	}


	public String getsCompanyLogoWebsite() {
		try{
			if(sCompanyLogo!=null)
				sCompanyLogoWebsite=FileUtils.stuffedFilename(sCompanyLogo, "_companyLogoWebsite");
			}catch(Exception e){
				sCompanyLogoWebsite=null;
			}

		return sCompanyLogoWebsite;
	}


	public void setsCompanyLogoWebsite(String sCompanyLogoWebsite) {
		this.sCompanyLogoWebsite = sCompanyLogoWebsite;
	}




	public User(){
	}
	
	
	public User(Long id) {
		super();
		this.id = id;
	}

	public User(String username){
		this.username=username;
	}
	
	
	public User(String username, String password, String sFirstName,
			String sLastName) {
		super();
		this.username = username;
		this.password = password;
		this.sFirstName = sFirstName;
		this.sLastName = sLastName;
	}

//
//	public void setAuthority(String authority) {
//		this.authority = authority;
//	}


	public String getStoreName() {
		return storeName;
	}


	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}


	public String getsCurrency() {
		return sCurrency;
	}


	public void setsCurrency(String sCurrency) {
		this.sCurrency = sCurrency;
	}


	public Integer getiProductCount() {
		return iProductCount;
	}


	public void setiProductCount(Integer iProductCount) {
		this.iProductCount = iProductCount;
	}


	public String getCountryName() {
		return countryName;
	}


	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	
	
	public Long getStoreId() {
		return storeId;
	}


	public void setStoreId(Long storeId) {
		this.storeId = storeId;
	}
	



	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column users.username
	 * @param username  the value for users.username
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column users.id
	 * @return  the value of users.id
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public Long getId() {
		return id;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column users.id
	 * @param id  the value for users.id
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public void setId(Long id) {
		this.id = id;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column users.password
	 * @return  the value of users.password
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public String getPassword() {
		return password;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column users.password
	 * @param password  the value for users.password
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column users.s_first_name
	 * @return  the value of users.s_first_name
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public String getsFirstName() {
		return sFirstName;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column users.s_first_name
	 * @param sFirstName  the value for users.s_first_name
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public void setsFirstName(String sFirstName) {
		this.sFirstName = sFirstName == null ? null : sFirstName.trim();
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column users.s_last_name
	 * @return  the value of users.s_last_name
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public String getsLastName() {
		return sLastName;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column users.s_last_name
	 * @param sLastName  the value for users.s_last_name
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public void setsLastName(String sLastName) {
		this.sLastName = sLastName == null ? null : sLastName.trim();
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column users.d_birthday
	 * @return  the value of users.d_birthday
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public Date getdBirthday() {
		return dBirthday;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column users.d_birthday
	 * @param dBirthday  the value for users.d_birthday
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public void setdBirthday(Date dBirthday) {
		this.dBirthday = dBirthday;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column users.s_company_reg_no
	 * @return  the value of users.s_company_reg_no
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public String getsCompanyRegNo() {
		return sCompanyRegNo;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column users.s_company_reg_no
	 * @param sCompanyRegNo  the value for users.s_company_reg_no
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public void setsCompanyRegNo(String sCompanyRegNo) {
		this.sCompanyRegNo = sCompanyRegNo == null ? null : sCompanyRegNo
				.trim();
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column users.s_tax_reg_no
	 * @return  the value of users.s_tax_reg_no
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public String getsTaxRegNo() {
		return sTaxRegNo;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column users.s_tax_reg_no
	 * @param sTaxRegNo  the value for users.s_tax_reg_no
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public void setsTaxRegNo(String sTaxRegNo) {
		this.sTaxRegNo = sTaxRegNo == null ? null : sTaxRegNo.trim();
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column users.s_company_logo
	 * @return  the value of users.s_company_logo
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public String getsCompanyLogo() {
		return sCompanyLogo;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column users.s_company_logo
	 * @param sCompanyLogo  the value for users.s_company_logo
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public void setsCompanyLogo(String sCompanyLogo) {
		this.sCompanyLogo = sCompanyLogo == null ? null : sCompanyLogo.trim();
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column users.s_paypal_address
	 * @return  the value of users.s_paypal_address
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public String getsPaypalAddress() {
		return sPaypalAddress;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column users.s_paypal_address
	 * @param sPaypalAddress  the value for users.s_paypal_address
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public void setsPaypalAddress(String sPaypalAddress) {
		this.sPaypalAddress = sPaypalAddress == null ? null : sPaypalAddress
				.trim();
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column users.s_heard_from
	 * @return  the value of users.s_heard_from
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public String getsHeardFrom() {
		return sHeardFrom;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column users.s_heard_from
	 * @param sHeardFrom  the value for users.s_heard_from
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public void setsHeardFrom(String sHeardFrom) {
		this.sHeardFrom = sHeardFrom == null ? null : sHeardFrom.trim();
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column users.s_coupon_code
	 * @return  the value of users.s_coupon_code
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public String getsCouponCode() {
		return sCouponCode;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column users.s_coupon_code
	 * @param sCouponCode  the value for users.s_coupon_code
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public void setsCouponCode(String sCouponCode) {
		this.sCouponCode = sCouponCode == null ? null : sCouponCode.trim();
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column users.s_affiliate_code
	 * @return  the value of users.s_affiliate_code
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public String getsAffiliateCode() {
		return sAffiliateCode;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column users.s_affiliate_code
	 * @param sAffiliateCode  the value for users.s_affiliate_code
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public void setsAffiliateCode(String sAffiliateCode) {
		this.sAffiliateCode = sAffiliateCode == null ? null : sAffiliateCode
				.trim();
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column users.d_joined_on
	 * @return  the value of users.d_joined_on
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public Date getdJoinedOn() {
		return dJoinedOn;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column users.d_joined_on
	 * @param dJoinedOn  the value for users.d_joined_on
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public void setdJoinedOn(Date dJoinedOn) {
		this.dJoinedOn = dJoinedOn;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column users.d_updated_on
	 * @return  the value of users.d_updated_on
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public Date getdUpdatedOn() {
		return dUpdatedOn;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column users.d_updated_on
	 * @param dUpdatedOn  the value for users.d_updated_on
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public void setdUpdatedOn(Date dUpdatedOn) {
		this.dUpdatedOn = dUpdatedOn;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column users.s_activation_key
	 * @return  the value of users.s_activation_key
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public String getsActivationKey() {
		return sActivationKey;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column users.s_activation_key
	 * @param sActivationKey  the value for users.s_activation_key
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public void setsActivationKey(String sActivationKey) {
		this.sActivationKey = sActivationKey == null ? null : sActivationKey
				.trim();
	}


	

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column users.s_webapp_url_mapping
	 * @return  the value of users.s_webapp_url_mapping
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public String getsWebappUrlMapping() {
		return sWebappUrlMapping;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column users.s_webapp_url_mapping
	 * @param sWebappUrlMapping  the value for users.s_webapp_url_mapping
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public void setsWebappUrlMapping(String sWebappUrlMapping) {
		this.sWebappUrlMapping = sWebappUrlMapping == null ? null
				: sWebappUrlMapping.trim();
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column users.s_webapp_domain_name
	 * @return  the value of users.s_webapp_domain_name
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public String getsWebappDomainName() {
		return sWebappDomainName;
	}


	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column users.s_webapp_domain_name
	 * @param sWebappDomainName  the value for users.s_webapp_domain_name
	 * @ibatorgenerated  Fri Jun 17 12:08:58 GMT+05:30 2011
	 */
	public void setsWebappDomainName(String sWebappDomainName) {
		this.sWebappDomainName = sWebappDomainName == null ? null
				: sWebappDomainName.trim();
	}


	public boolean isbCustomCopyrightPage() {
		return bCustomCopyrightPage;
	}


	public void setbCustomCopyrightPage(Boolean bCustomCopyrightPage) {
		this.bCustomCopyrightPage = bCustomCopyrightPage;
	}


	public boolean isEnabled() {
		return enabled;
	}


	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}


	public boolean isbIphone() {
		return bIphone;
	}


	public void setbIphone(Boolean bIphone) {
		this.bIphone = bIphone;
	}


	public boolean isbIpad() {
		return bIpad;
	}


	public void setbIpad(Boolean bIpad) {
		this.bIpad = bIpad;
	}


	public boolean isbAndroid() {
		return bAndroid;
	}


	public void setbAndroid(Boolean bAndroid) {
		this.bAndroid = bAndroid;
	}


	public boolean isbWebapp() {
		return bWebapp;
	}


	public void setbWebapp(Boolean bWebapp) {
		this.bWebapp = bWebapp;
	}

	public HashMap<String, String> getDefaultLabelKeyValuesMap() {
		return defaultLabelKeyValuesMap;
	}


	public void setDefaultLabelKeyValuesMap(
			HashMap<String, String> defaultLabelKeyValuesMap) {
		this.defaultLabelKeyValuesMap = defaultLabelKeyValuesMap;
	}


	public Integer getStoreProductLimit() {
		return storeProductLimit;
	}


	public void setStoreProductLimit(Integer storeProductLimit) {
		this.storeProductLimit = storeProductLimit;
	}



	

	
}