package com.mobicart.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class VideoExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table videos
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table videos
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table videos
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	public VideoExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table videos
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	protected VideoExample(VideoExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table videos
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table videos
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table videos
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table videos
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table videos
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table videos
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table videos
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table videos
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return this;
		}

		public Criteria andIdIn(List values) {
			addCriterion("id in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List values) {
			addCriterion("id not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return this;
		}

		public Criteria andUserIdEqualTo(Long value) {
			addCriterion("user_id =", value, "userId");
			return this;
		}

		public Criteria andUserIdNotEqualTo(Long value) {
			addCriterion("user_id <>", value, "userId");
			return this;
		}

		public Criteria andUserIdGreaterThan(Long value) {
			addCriterion("user_id >", value, "userId");
			return this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
			addCriterion("user_id >=", value, "userId");
			return this;
		}

		public Criteria andUserIdLessThan(Long value) {
			addCriterion("user_id <", value, "userId");
			return this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Long value) {
			addCriterion("user_id <=", value, "userId");
			return this;
		}

		public Criteria andUserIdIn(List values) {
			addCriterion("user_id in", values, "userId");
			return this;
		}

		public Criteria andUserIdNotIn(List values) {
			addCriterion("user_id not in", values, "userId");
			return this;
		}

		public Criteria andUserIdBetween(Long value1, Long value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return this;
		}

		public Criteria andUserIdNotBetween(Long value1, Long value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return this;
		}

		public Criteria andAppIdIsNull() {
			addCriterion("app_id is null");
			return this;
		}

		public Criteria andAppIdIsNotNull() {
			addCriterion("app_id is not null");
			return this;
		}

		public Criteria andAppIdEqualTo(Long value) {
			addCriterion("app_id =", value, "appId");
			return this;
		}

		public Criteria andAppIdNotEqualTo(Long value) {
			addCriterion("app_id <>", value, "appId");
			return this;
		}

		public Criteria andAppIdGreaterThan(Long value) {
			addCriterion("app_id >", value, "appId");
			return this;
		}

		public Criteria andAppIdGreaterThanOrEqualTo(Long value) {
			addCriterion("app_id >=", value, "appId");
			return this;
		}

		public Criteria andAppIdLessThan(Long value) {
			addCriterion("app_id <", value, "appId");
			return this;
		}

		public Criteria andAppIdLessThanOrEqualTo(Long value) {
			addCriterion("app_id <=", value, "appId");
			return this;
		}

		public Criteria andAppIdIn(List values) {
			addCriterion("app_id in", values, "appId");
			return this;
		}

		public Criteria andAppIdNotIn(List values) {
			addCriterion("app_id not in", values, "appId");
			return this;
		}

		public Criteria andAppIdBetween(Long value1, Long value2) {
			addCriterion("app_id between", value1, value2, "appId");
			return this;
		}

		public Criteria andAppIdNotBetween(Long value1, Long value2) {
			addCriterion("app_id not between", value1, value2, "appId");
			return this;
		}

		public Criteria andStoreIdIsNull() {
			addCriterion("store_id is null");
			return this;
		}

		public Criteria andStoreIdIsNotNull() {
			addCriterion("store_id is not null");
			return this;
		}

		public Criteria andStoreIdEqualTo(Long value) {
			addCriterion("store_id =", value, "storeId");
			return this;
		}

		public Criteria andStoreIdNotEqualTo(Long value) {
			addCriterion("store_id <>", value, "storeId");
			return this;
		}

		public Criteria andStoreIdGreaterThan(Long value) {
			addCriterion("store_id >", value, "storeId");
			return this;
		}

		public Criteria andStoreIdGreaterThanOrEqualTo(Long value) {
			addCriterion("store_id >=", value, "storeId");
			return this;
		}

		public Criteria andStoreIdLessThan(Long value) {
			addCriterion("store_id <", value, "storeId");
			return this;
		}

		public Criteria andStoreIdLessThanOrEqualTo(Long value) {
			addCriterion("store_id <=", value, "storeId");
			return this;
		}

		public Criteria andStoreIdIn(List values) {
			addCriterion("store_id in", values, "storeId");
			return this;
		}

		public Criteria andStoreIdNotIn(List values) {
			addCriterion("store_id not in", values, "storeId");
			return this;
		}

		public Criteria andStoreIdBetween(Long value1, Long value2) {
			addCriterion("store_id between", value1, value2, "storeId");
			return this;
		}

		public Criteria andStoreIdNotBetween(Long value1, Long value2) {
			addCriterion("store_id not between", value1, value2, "storeId");
			return this;
		}

		public Criteria andSTitleIsNull() {
			addCriterion("s_title is null");
			return this;
		}

		public Criteria andSTitleIsNotNull() {
			addCriterion("s_title is not null");
			return this;
		}

		public Criteria andSTitleEqualTo(String value) {
			addCriterion("s_title =", value, "sTitle");
			return this;
		}

		public Criteria andSTitleNotEqualTo(String value) {
			addCriterion("s_title <>", value, "sTitle");
			return this;
		}

		public Criteria andSTitleGreaterThan(String value) {
			addCriterion("s_title >", value, "sTitle");
			return this;
		}

		public Criteria andSTitleGreaterThanOrEqualTo(String value) {
			addCriterion("s_title >=", value, "sTitle");
			return this;
		}

		public Criteria andSTitleLessThan(String value) {
			addCriterion("s_title <", value, "sTitle");
			return this;
		}

		public Criteria andSTitleLessThanOrEqualTo(String value) {
			addCriterion("s_title <=", value, "sTitle");
			return this;
		}

		public Criteria andSTitleLike(String value) {
			addCriterion("s_title like", value, "sTitle");
			return this;
		}

		public Criteria andSTitleNotLike(String value) {
			addCriterion("s_title not like", value, "sTitle");
			return this;
		}

		public Criteria andSTitleIn(List values) {
			addCriterion("s_title in", values, "sTitle");
			return this;
		}

		public Criteria andSTitleNotIn(List values) {
			addCriterion("s_title not in", values, "sTitle");
			return this;
		}

		public Criteria andSTitleBetween(String value1, String value2) {
			addCriterion("s_title between", value1, value2, "sTitle");
			return this;
		}

		public Criteria andSTitleNotBetween(String value1, String value2) {
			addCriterion("s_title not between", value1, value2, "sTitle");
			return this;
		}

		public Criteria andSUrlIsNull() {
			addCriterion("s_url is null");
			return this;
		}

		public Criteria andSUrlIsNotNull() {
			addCriterion("s_url is not null");
			return this;
		}

		public Criteria andSUrlEqualTo(String value) {
			addCriterion("s_url =", value, "sUrl");
			return this;
		}

		public Criteria andSUrlNotEqualTo(String value) {
			addCriterion("s_url <>", value, "sUrl");
			return this;
		}

		public Criteria andSUrlGreaterThan(String value) {
			addCriterion("s_url >", value, "sUrl");
			return this;
		}

		public Criteria andSUrlGreaterThanOrEqualTo(String value) {
			addCriterion("s_url >=", value, "sUrl");
			return this;
		}

		public Criteria andSUrlLessThan(String value) {
			addCriterion("s_url <", value, "sUrl");
			return this;
		}

		public Criteria andSUrlLessThanOrEqualTo(String value) {
			addCriterion("s_url <=", value, "sUrl");
			return this;
		}

		public Criteria andSUrlLike(String value) {
			addCriterion("s_url like", value, "sUrl");
			return this;
		}

		public Criteria andSUrlNotLike(String value) {
			addCriterion("s_url not like", value, "sUrl");
			return this;
		}

		public Criteria andSUrlIn(List values) {
			addCriterion("s_url in", values, "sUrl");
			return this;
		}

		public Criteria andSUrlNotIn(List values) {
			addCriterion("s_url not in", values, "sUrl");
			return this;
		}

		public Criteria andSUrlBetween(String value1, String value2) {
			addCriterion("s_url between", value1, value2, "sUrl");
			return this;
		}

		public Criteria andSUrlNotBetween(String value1, String value2) {
			addCriterion("s_url not between", value1, value2, "sUrl");
			return this;
		}

		public Criteria andDAddedOnIsNull() {
			addCriterion("d_added_on is null");
			return this;
		}

		public Criteria andDAddedOnIsNotNull() {
			addCriterion("d_added_on is not null");
			return this;
		}

		public Criteria andDAddedOnEqualTo(Date value) {
			addCriterion("d_added_on =", value, "dAddedOn");
			return this;
		}

		public Criteria andDAddedOnNotEqualTo(Date value) {
			addCriterion("d_added_on <>", value, "dAddedOn");
			return this;
		}

		public Criteria andDAddedOnGreaterThan(Date value) {
			addCriterion("d_added_on >", value, "dAddedOn");
			return this;
		}

		public Criteria andDAddedOnGreaterThanOrEqualTo(Date value) {
			addCriterion("d_added_on >=", value, "dAddedOn");
			return this;
		}

		public Criteria andDAddedOnLessThan(Date value) {
			addCriterion("d_added_on <", value, "dAddedOn");
			return this;
		}

		public Criteria andDAddedOnLessThanOrEqualTo(Date value) {
			addCriterion("d_added_on <=", value, "dAddedOn");
			return this;
		}

		public Criteria andDAddedOnIn(List values) {
			addCriterion("d_added_on in", values, "dAddedOn");
			return this;
		}

		public Criteria andDAddedOnNotIn(List values) {
			addCriterion("d_added_on not in", values, "dAddedOn");
			return this;
		}

		public Criteria andDAddedOnBetween(Date value1, Date value2) {
			addCriterion("d_added_on between", value1, value2, "dAddedOn");
			return this;
		}

		public Criteria andDAddedOnNotBetween(Date value1, Date value2) {
			addCriterion("d_added_on not between", value1, value2, "dAddedOn");
			return this;
		}

		public Criteria andIWatchCountIsNull() {
			addCriterion("i_watch_count is null");
			return this;
		}

		public Criteria andIWatchCountIsNotNull() {
			addCriterion("i_watch_count is not null");
			return this;
		}

		public Criteria andIWatchCountEqualTo(Integer value) {
			addCriterion("i_watch_count =", value, "iWatchCount");
			return this;
		}

		public Criteria andIWatchCountNotEqualTo(Integer value) {
			addCriterion("i_watch_count <>", value, "iWatchCount");
			return this;
		}

		public Criteria andIWatchCountGreaterThan(Integer value) {
			addCriterion("i_watch_count >", value, "iWatchCount");
			return this;
		}

		public Criteria andIWatchCountGreaterThanOrEqualTo(Integer value) {
			addCriterion("i_watch_count >=", value, "iWatchCount");
			return this;
		}

		public Criteria andIWatchCountLessThan(Integer value) {
			addCriterion("i_watch_count <", value, "iWatchCount");
			return this;
		}

		public Criteria andIWatchCountLessThanOrEqualTo(Integer value) {
			addCriterion("i_watch_count <=", value, "iWatchCount");
			return this;
		}

		public Criteria andIWatchCountIn(List values) {
			addCriterion("i_watch_count in", values, "iWatchCount");
			return this;
		}

		public Criteria andIWatchCountNotIn(List values) {
			addCriterion("i_watch_count not in", values, "iWatchCount");
			return this;
		}

		public Criteria andIWatchCountBetween(Integer value1, Integer value2) {
			addCriterion("i_watch_count between", value1, value2, "iWatchCount");
			return this;
		}

		public Criteria andIWatchCountNotBetween(Integer value1, Integer value2) {
			addCriterion("i_watch_count not between", value1, value2,
					"iWatchCount");
			return this;
		}
	}
}