package com.mobicart.model;

import java.util.Date;

public class ApiPartner {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column api_partner.id
     *
     * @ibatorgenerated Wed Jan 18 18:43:27 IST 2012
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column api_partner.partner_name
     *
     * @ibatorgenerated Wed Jan 18 18:43:27 IST 2012
     */
    private String partnerName;
    
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column api_partner.partner_name
     *
     * @ibatorgenerated Wed Jan 18 18:43:27 IST 2012
     */
    private String partnerEmail;

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column api_partner.api_key
     *
     * @ibatorgenerated Wed Jan 18 18:43:27 IST 2012
     */
    private String apiKey;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column api_partner.date_of_joining
     *
     * @ibatorgenerated Wed Jan 18 18:43:27 IST 2012
     */
    private Date dateOfJoining;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column api_partner.id
     *
     * @return the value of api_partner.id
     *
     * @ibatorgenerated Wed Jan 18 18:43:27 IST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column api_partner.id
     *
     * @param id the value for api_partner.id
     *
     * @ibatorgenerated Wed Jan 18 18:43:27 IST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column api_partner.partner_name
     *
     * @return the value of api_partner.partner_name
     *
     * @ibatorgenerated Wed Jan 18 18:43:27 IST 2012
     */
    public String getPartnerName() {
        return partnerName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column api_partner.partner_name
     *
     * @param partnerName the value for api_partner.partner_name
     *
     * @ibatorgenerated Wed Jan 18 18:43:27 IST 2012
     */
    public void setPartnerName(String partnerName) {
        this.partnerName = partnerName == null ? null : partnerName.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column api_partner.api_key
     *
     * @return the value of api_partner.api_key
     *
     * @ibatorgenerated Wed Jan 18 18:43:27 IST 2012
     */
    public String getApiKey() {
        return apiKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column api_partner.api_key
     *
     * @param apiKey the value for api_partner.api_key
     *
     * @ibatorgenerated Wed Jan 18 18:43:27 IST 2012
     */
    public void setApiKey(String apiKey) {
        this.apiKey = apiKey == null ? null : apiKey.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column api_partner.date_of_joining
     *
     * @return the value of api_partner.date_of_joining
     *
     * @ibatorgenerated Wed Jan 18 18:43:27 IST 2012
     */
    public Date getDateOfJoining() {
        return dateOfJoining;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column api_partner.date_of_joining
     *
     * @param dateOfJoining the value for api_partner.date_of_joining
     *
     * @ibatorgenerated Wed Jan 18 18:43:27 IST 2012
     */
    public void setDateOfJoining(Date dateOfJoining) {
        this.dateOfJoining = dateOfJoining;
    }
    
    public String getPartnerEmail() {
		return partnerEmail;
	}

	public void setPartnerEmail(String partnerEmail) {
		this.partnerEmail = partnerEmail;
	}
}