package com.mobicart.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.springframework.web.multipart.commons.CommonsMultipartFile;

import com.mobicart.util.Constants;
import com.mobicart.util.FileUtils;

public class App {

	private Long id;
	private Long userId;
	private String sName;
	private String sTitle;
	private BigDecimal fPrice;
	private String sDescription;
	private String sCopyright;
	private String sIconImage;
	private String sIconImage57;
	private String sIconImage72x72;
	private String sLoaderImage;
	private String sLoaderImage768x1024;
	private String sPnCertificatePath;
	private String sPnPassword;
	private Long iDownloadCount;
	private Boolean bSubmissionToApple;
	private Date dCreatedOn;
	private Date dUpdatedOn;
	private Boolean bEnabled;
	private ColorScheme colorScheme;
	private List<Feature> features;
	private CommonsMultipartFile flIconImage;
	private CommonsMultipartFile flLoaderImage;
	private List<Territory> territories;
	private String companyLogo;
	private String companyLogoIpad;

	private String companyLogoAndroid3;
	private String companyLogoAndroid4;
	private String companyLogoAndroid6;
	private String companyLogoIpadNew;
	private String companyLogoIphone;
	private String companyLogoIphone4;

	private String iconImageAndroid3;
	private String iconImageAndroid4;
	private String iconImageAndroid6;
	private String iconImageIpad;
	private String iconImageIphone;
	private String iconImageIphone4;

	private String loaderImageAndroid3;
	private String loaderImageAndroid4;
	private String loaderImageAndroid6;
	private String loaderImageIpad;
	private String loaderImageIphone;
	private String loaderImageIphone4;

	private BigDecimal appSubmissionFee;
	private BigDecimal appSubmissionRecurringFee;
	private String sCurrency;
	private String appTerritoryIds;
	private double version;
	private String registeredAndroidUserEmail;
	private String registeredAndroidUserPass;
	
	
	
	
	public String getsPnPassword() {
		return sPnPassword;
	}

	public void setsPnPassword(String sPnPassword) {
		this.sPnPassword = sPnPassword;
	}

	/* for upload logo dunctionality in appearance tab */
	private CommonsMultipartFile companyLogoFile;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column app.id
	 * 
	 * @return the value of app.id
	 * @ibatorgenerated Sat Sep 11 20:50:28 IST 2010
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column app.id
	 * 
	 * @param id
	 *            the value for app.id
	 * @ibatorgenerated Sat Sep 11 20:50:28 IST 2010
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column app.user_id
	 * 
	 * @return the value of app.user_id
	 * @ibatorgenerated Sat Sep 11 20:50:28 IST 2010
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column app.user_id
	 * 
	 * @param userId
	 *            the value for app.user_id
	 * @ibatorgenerated Sat Sep 11 20:50:28 IST 2010
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column app.s_name
	 * 
	 * @return the value of app.s_name
	 * @ibatorgenerated Sat Sep 11 20:50:28 IST 2010
	 */
	public String getsName() {
		return sName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column app.s_name
	 * 
	 * @param sName
	 *            the value for app.s_name
	 * @ibatorgenerated Sat Sep 11 20:50:28 IST 2010
	 */
	public void setsName(String sName) {
		this.sName = sName == null ? null : sName.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column app.s_title
	 * 
	 * @return the value of app.s_title
	 * @ibatorgenerated Sat Sep 11 20:50:28 IST 2010
	 */
	public String getsTitle() {
		return sTitle;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column app.s_title
	 * 
	 * @param sTitle
	 *            the value for app.s_title
	 * @ibatorgenerated Sat Sep 11 20:50:28 IST 2010
	 */
	public void setsTitle(String sTitle) {
		this.sTitle = sTitle == null ? null : sTitle.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column app.f_price
	 * 
	 * @return the value of app.f_price
	 * @ibatorgenerated Sat Sep 11 20:50:28 IST 2010
	 */
	public BigDecimal getfPrice() {
		return fPrice;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column app.f_price
	 * 
	 * @param fPrice
	 *            the value for app.f_price
	 * @ibatorgenerated Sat Sep 11 20:50:28 IST 2010
	 */
	public void setfPrice(BigDecimal fPrice) {
		this.fPrice = fPrice;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column app.s_description
	 * 
	 * @return the value of app.s_description
	 * @ibatorgenerated Sat Sep 11 20:50:28 IST 2010
	 */
	public String getsDescription() {
		return sDescription;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column app.s_description
	 * 
	 * @param sDescription
	 *            the value for app.s_description
	 * @ibatorgenerated Sat Sep 11 20:50:28 IST 2010
	 */
	public void setsDescription(String sDescription) {
		this.sDescription = sDescription == null ? null : sDescription.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column app.s_copyright
	 * 
	 * @return the value of app.s_copyright
	 * @ibatorgenerated Sat Sep 11 20:50:28 IST 2010
	 */
	public String getsCopyright() {
		return sCopyright;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column app.s_copyright
	 * 
	 * @param sCopyright
	 *            the value for app.s_copyright
	 * @ibatorgenerated Sat Sep 11 20:50:28 IST 2010
	 */
	public void setsCopyright(String sCopyright) {
		this.sCopyright = sCopyright == null ? null : sCopyright.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column app.s_icon_image
	 * 
	 * @return the value of app.s_icon_image
	 * @ibatorgenerated Sat Sep 11 20:50:28 IST 2010
	 */
	public String getsIconImage() {
		return sIconImage;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column app.s_icon_image
	 * 
	 * @param sIconImage
	 *            the value for app.s_icon_image
	 * @ibatorgenerated Sat Sep 11 20:50:28 IST 2010
	 */
	public void setsIconImage(String sIconImage) {
		this.sIconImage = sIconImage == null ? null : sIconImage.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column app.s_loader_image
	 * 
	 * @return the value of app.s_loader_image
	 * @ibatorgenerated Sat Sep 11 20:50:28 IST 2010
	 */
	public String getsLoaderImage() {
		return sLoaderImage;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column app.s_loader_image
	 * 
	 * @param sLoaderImage
	 *            the value for app.s_loader_image
	 * @ibatorgenerated Sat Sep 11 20:50:28 IST 2010
	 */
	public void setsLoaderImage(String sLoaderImage) {
		this.sLoaderImage = sLoaderImage == null ? null : sLoaderImage.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column app.i_download_count
	 * 
	 * @return the value of app.i_download_count
	 * @ibatorgenerated Sat Sep 11 20:50:28 IST 2010
	 */
	public Long getiDownloadCount() {
		return iDownloadCount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column app.i_download_count
	 * 
	 * @param iDownloadCount
	 *            the value for app.i_download_count
	 * @ibatorgenerated Sat Sep 11 20:50:28 IST 2010
	 */
	public void setiDownloadCount(Long iDownloadCount) {
		this.iDownloadCount = iDownloadCount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column app.b_submission_to_apple
	 * 
	 * @return the value of app.b_submission_to_apple
	 * @ibatorgenerated Sat Sep 11 20:50:28 IST 2010
	 */
	public Boolean getbSubmissionToApple() {
		return bSubmissionToApple;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column app.b_submission_to_apple
	 * 
	 * @param bSubmissionToApple
	 *            the value for app.b_submission_to_apple
	 * @ibatorgenerated Sat Sep 11 20:50:28 IST 2010
	 */
	public void setbSubmissionToApple(Boolean bSubmissionToApple) {
		this.bSubmissionToApple = bSubmissionToApple;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column app.d_created_on
	 * 
	 * @return the value of app.d_created_on
	 * @ibatorgenerated Sat Sep 11 20:50:28 IST 2010
	 */
	public Date getdCreatedOn() {
		return dCreatedOn;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column app.d_created_on
	 * 
	 * @param dCreatedOn
	 *            the value for app.d_created_on
	 * @ibatorgenerated Sat Sep 11 20:50:28 IST 2010
	 */
	public void setdCreatedOn(Date dCreatedOn) {
		this.dCreatedOn = dCreatedOn;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column app.d_updated_on
	 * 
	 * @return the value of app.d_updated_on
	 * @ibatorgenerated Sat Sep 11 20:50:28 IST 2010
	 */
	public Date getdUpdatedOn() {
		return dUpdatedOn;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column app.d_updated_on
	 * 
	 * @param dUpdatedOn
	 *            the value for app.d_updated_on
	 * @ibatorgenerated Sat Sep 11 20:50:28 IST 2010
	 */
	public void setdUpdatedOn(Date dUpdatedOn) {
		this.dUpdatedOn = dUpdatedOn;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column app.b_enabled
	 * 
	 * @return the value of app.b_enabled
	 * @ibatorgenerated Sat Sep 11 20:50:28 IST 2010
	 */
	public Boolean getbEnabled() {
		return bEnabled;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column app.b_enabled
	 * 
	 * @param bEnabled
	 *            the value for app.b_enabled
	 * @ibatorgenerated Sat Sep 11 20:50:28 IST 2010
	 */
	public void setbEnabled(Boolean bEnabled) {
		this.bEnabled = bEnabled;
	}

	public App() {
	}

	public App(Long id) {
		this.id = id;
	}

	public List<Feature> getFeatures() {
		return features;
	}

	public void setFeatures(List<Feature> features) {
		this.features = features;
	}

	public CommonsMultipartFile getFlIconImage() {
		return flIconImage;
	}

	public void setFlIconImage(CommonsMultipartFile flIconImage) {
		this.flIconImage = flIconImage;
	}

	public CommonsMultipartFile getFlLoaderImage() {
		return flLoaderImage;
	}

	public void setFlLoaderImage(CommonsMultipartFile flLoaderImage) {
		this.flLoaderImage = flLoaderImage;
	}

	public ColorScheme getColorScheme() {
		return colorScheme;
	}

	public void setColorScheme(ColorScheme colorScheme) {
		this.colorScheme = colorScheme;
	}

	public List<Territory> getTerritories() {
		return territories;
	}

	public void setTerritories(List<Territory> territories) {
		this.territories = territories;
	}

	public String getCompanyLogo() {
		return companyLogo;
	}

	public void setCompanyLogo(String companyLogo) {
		this.companyLogo = companyLogo;
	}

	public String getsIconImage57() {
		try {
			if (sIconImage != null)
				sIconImage57 = FileUtils.stuffedFilename(sIconImage, "_icon");
		} catch (Exception e) {
			sIconImage57 = null;
		}
		return sIconImage57;
	}

	public void setsIconImage57(String sIconImage57) {
		this.sIconImage57 = sIconImage57;
	}

	public BigDecimal getAppSubmissionFee() {
		return appSubmissionFee;
	}

	public void setAppSubmissionFee(BigDecimal appSubmissionFee) {
		this.appSubmissionFee = appSubmissionFee;
	}

	public String getsCurrency() {
		return sCurrency;
	}

	public void setsCurrency(String sCurrency) {
		this.sCurrency = sCurrency;
	}

	public String getAppTerritoryIds() {
		StringBuffer appTerritoryIds = new StringBuffer();
		for (Territory territory : territories) {
			appTerritoryIds.append(territory.getId());
			appTerritoryIds.append(",");
		}
		this.appTerritoryIds = appTerritoryIds.toString();
		return this.appTerritoryIds;
	}

	public BigDecimal getAppSubmissionRecurringFee() {
		return appSubmissionRecurringFee;
	}

	public void setAppSubmissionRecurringFee(
			BigDecimal appSubmissionRecurringFee) {
		this.appSubmissionRecurringFee = appSubmissionRecurringFee;
	}

	public CommonsMultipartFile getCompanyLogoFile() {
		return companyLogoFile;
	}

	public void setCompanyLogoFile(CommonsMultipartFile companyLogoFile) {
		this.companyLogoFile = companyLogoFile;
	}

	public String getsPnCertificatePath() {
		return sPnCertificatePath;
	}

	public void setsPnCertificatePath(String sPnCertificatePath) {
		this.sPnCertificatePath = sPnCertificatePath;
	}

	
	
	
	public String getsIconImage72x72() {
		try {
			if (sIconImage != null)
				sIconImage72x72 = FileUtils.stuffedFilename(sIconImage,
						"_72x72");
		} catch (Exception e) {
			sIconImage72x72 = null;
		}
		return sIconImage72x72;
	}

	public String getsLoaderImage768x1024() {
		try {
			if (sLoaderImage != null)
				sLoaderImage768x1024 = FileUtils.stuffedFilename(sLoaderImage,
						"_768x1024");
		} catch (Exception e) {
			sLoaderImage768x1024 = null;
		}
		return sLoaderImage768x1024;
	}

	public String getCompanyLogoIpad() {
		try {
			if (companyLogo != null)
				companyLogoIpad = FileUtils.stuffedFilename(companyLogo,
						"_ipad");
		} catch (Exception e) {
			companyLogoIpad = null;
		}
		return companyLogoIpad;
	}

	public String getCompanyLogoAndroid3() {

		try {
			if (companyLogo != null)
				companyLogoAndroid3 = FileUtils.stuffedFilename(companyLogo,
						"_" + Constants.COMPANY_LOGO_ANDROID3_KEY);
		} catch (Exception e) {
			companyLogoAndroid3 = null;
		}

		return companyLogoAndroid3;
	}

	public String getCompanyLogoAndroid4() {
		try {
			if (companyLogo != null)
				companyLogoAndroid4 = FileUtils.stuffedFilename(companyLogo,
						"_" + Constants.COMPANY_LOGO_ANDROID4_KEY);
		} catch (Exception e) {
			companyLogoAndroid4 = null;
		}

		return companyLogoAndroid4;
	}

	
	
	
	
	
	public String getCompanyLogoAndroid6() {
		try {
			if (companyLogo != null)
				companyLogoAndroid6 = FileUtils.stuffedFilename(companyLogo,
						"_" + Constants.COMPANY_LOGO_ANDROID6_KEY);
		} catch (Exception e) {
			companyLogoAndroid6 = null;
		}
		return companyLogoAndroid6;
	}

	public String getCompanyLogoIpadNew() {
		
		try {
			if (companyLogo != null)
				companyLogoIpadNew = FileUtils.stuffedFilename(companyLogo,
						"_" + Constants.COMPANY_LOGO_IPAD_KEY);
		} catch (Exception e) {
			companyLogoIpadNew = null;
		}
		
		return companyLogoIpadNew;
	}

	public String getCompanyLogoIphone() {
		try {
			if (companyLogo != null)
				companyLogoIphone = FileUtils.stuffedFilename(companyLogo,
						"_" + Constants.COMPANY_LOGO_IPHONE_KEY);
		} catch (Exception e) {
			companyLogoIphone = null;
		}
		return companyLogoIphone;
	}

	
	
	
	
	public String getCompanyLogoIphone4() {
		
		try {
			if (companyLogo != null)
				companyLogoIphone4 = FileUtils.stuffedFilename(companyLogo,
						"_" + Constants.COMPANY_LOGO_IPHONE4_KEY);
		} catch (Exception e) {
			companyLogoIphone4 = null;
		}
		
		return companyLogoIphone4;
	}

	public void setCompanyLogoIphone4(String companyLogoIphone4) {
		this.companyLogoIphone4 = companyLogoIphone4;
	}

	public String getIconImageIphone4() {
		
		
		try {
			if(sIconImage!=null){
				iconImageIphone4=FileUtils.stuffedFilename(sIconImage, "_"+Constants.APP_ICON_IPHONE4_KEY);
			}
		} catch (Exception e) {
			iconImageIphone4 = null;
		}
		
		
		
		return iconImageIphone4;
	}

	public void setIconImageIphone4(String iconImageIphone4) {
		this.iconImageIphone4 = iconImageIphone4;
	}

	public String getLoaderImageIphone4() {
		
		try{
		if(sLoaderImage!=null){
			loaderImageIphone4=FileUtils.stuffedFilename(sLoaderImage, "_"+Constants.APP_LOADER_IPHONE4_KEY);
		}
		}
		catch (Exception e) {
			loaderImageIphone4=null;
		}
		
	
		return loaderImageIphone4;
	}

	public void setLoaderImageIphone4(String loaderImageIphone4) {
		this.loaderImageIphone4 = loaderImageIphone4;
	}

	public String getIconImageAndroid3() {
		
		try{
		if(sIconImage!=null){
			iconImageAndroid3=FileUtils.stuffedFilename(sIconImage, "_"+Constants.APP_ICON_ANDROID3_KEY);
		}}
		catch (Exception e) {
			iconImageAndroid3=null; 
		}
		return iconImageAndroid3;
	}

	public String getIconImageAndroid4() {
		try{
		if(sIconImage!=null){
			iconImageAndroid4=FileUtils.stuffedFilename(sIconImage, "_"+Constants.APP_ICON_ANDROID4_KEY);
		}}
		catch (Exception e) {
			iconImageAndroid4=null; 
		}
		return iconImageAndroid4;
	}

	public String getIconImageAndroid6() {
		try{
		if(sIconImage!=null){
			iconImageAndroid6=FileUtils.stuffedFilename(sIconImage, "_"+Constants.APP_ICON_ANDROID6_KEY);
		}}
		catch (Exception e) {
			iconImageAndroid6=null;
		}
		return iconImageAndroid6;
	}

	public String getIconImageIpad() {
		try{
		if(sIconImage!=null){
			iconImageIpad=FileUtils.stuffedFilename(sIconImage, "_"+Constants.APP_ICON_IPAD_KEY);
		}}
		catch (Exception e) {
			iconImageIpad=null;
		}
		return iconImageIpad;
	}

	public String getIconImageIphone() {
		try{
		if(sIconImage!=null){
			iconImageIphone=FileUtils.stuffedFilename(sIconImage, "_"+Constants.APP_ICON_IPHONE_KEY);
		}}
		catch (Exception e) {
			iconImageIphone=null;
		}
		return iconImageIphone;
	}

	
	public String getLoaderImageAndroid3() {
		try{
		if(sLoaderImage!=null){
			loaderImageAndroid3=FileUtils.stuffedFilename(sLoaderImage, "_"+Constants.APP_LOADER_ANDROID3_KEY);
		}}
		catch (Exception e) {
			loaderImageAndroid3=null;
		}
		return loaderImageAndroid3;
	}

	public String getLoaderImageAndroid4() {
		try{
		if(sLoaderImage!=null){
			loaderImageAndroid4=FileUtils.stuffedFilename(sLoaderImage, "_"+Constants.APP_LOADER_ANDROID4_KEY);
		}}
		catch (Exception e) {
			loaderImageAndroid4=null;
		}
		return loaderImageAndroid4;
	}

	public String getLoaderImageAndroid6() {
		try{
		if(sLoaderImage!=null){
			loaderImageAndroid6=FileUtils.stuffedFilename(sLoaderImage, "_"+Constants.APP_LOADER_ANDROID6_KEY);
		}}
		catch (Exception e) {
			loaderImageAndroid6=null;
		}
		return loaderImageAndroid6;
	}

	public String getLoaderImageIpad() {
		try{
		if(sLoaderImage!=null){
			loaderImageIpad=FileUtils.stuffedFilename(sLoaderImage, "_"+Constants.APP_LOADER_IPAD_KEY);
		}}
		catch (Exception e) {
			loaderImageIpad=null;
		}
		return loaderImageIpad;
	}

	public String getLoaderImageIphone() {
		try{
		if(sLoaderImage!=null){
			loaderImageIphone=FileUtils.stuffedFilename(sLoaderImage, "_"+Constants.APP_LOADER_IPHONE_KEY);
		}}
		catch (Exception e) {
			loaderImageIphone=null;
		}
		return loaderImageIphone;
	}
	
	
	

	public Double getVersion() {
		return version;
	}

	public void setVersion(Double version) {
		this.version = version;
	}
	

	public String getRegisteredAndroidUserEmail() {
		return registeredAndroidUserEmail;
	}

	public void setRegisteredAndroidUserEmail(String registeredAndroidUserEmail) {
		this.registeredAndroidUserEmail = registeredAndroidUserEmail;
	}

	public String getRegisteredAndroidUserPass() {
		return registeredAndroidUserPass;
	}

	public void setRegisteredAndroidUserPass(String registeredAndroidUserPass) {
		this.registeredAndroidUserPass = registeredAndroidUserPass;
	}

	@Override
	public String toString() {
		return "App [id=" + id + ", userId=" + userId + ", sName=" + sName+",sPnPassword="+sPnPassword
				+ "]";
	}

}
