package com.mobicart.model;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;

import org.apache.commons.httpclient.HttpClient;
import org.apache.commons.httpclient.HttpStatus;
import org.apache.commons.httpclient.methods.PostMethod;
import org.apache.commons.httpclient.methods.StringRequestEntity;

public class AppColorScheme {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column app_color_schemes.app_id
	 * @ibatorgenerated  Tue Aug 03 16:33:41 IST 2010
	 */
	private Long appId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column app_color_schemes.color_scheme_id
	 * @ibatorgenerated  Tue Aug 03 16:33:41 IST 2010
	 */
	private Long colorSchemeId;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column app_color_schemes.app_id
	 * @return  the value of app_color_schemes.app_id
	 * @ibatorgenerated  Tue Aug 03 16:33:41 IST 2010
	 */
	public Long getAppId() {
		return appId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column app_color_schemes.app_id
	 * @param appId  the value for app_color_schemes.app_id
	 * @ibatorgenerated  Tue Aug 03 16:33:41 IST 2010
	 */
	public void setAppId(Long appId) {
		this.appId = appId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column app_color_schemes.color_scheme_id
	 * @return  the value of app_color_schemes.color_scheme_id
	 * @ibatorgenerated  Tue Aug 03 16:33:41 IST 2010
	 */
	public Long getColorSchemeId() {
		return colorSchemeId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column app_color_schemes.color_scheme_id
	 * @param colorSchemeId  the value for app_color_schemes.color_scheme_id
	 * @ibatorgenerated  Tue Aug 03 16:33:41 IST 2010
	 */
	public void setColorSchemeId(Long colorSchemeId) {
		this.colorSchemeId = colorSchemeId;
	}
	
	
	 
	
	
}