package com.mobicart.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AppExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app
     *
     * @mbggenerated Wed Jul 13 11:47:38 GMT+05:30 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app
     *
     * @mbggenerated Wed Jul 13 11:47:38 GMT+05:30 2011
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app
     *
     * @mbggenerated Wed Jul 13 11:47:38 GMT+05:30 2011
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbggenerated Wed Jul 13 11:47:38 GMT+05:30 2011
     */
    public AppExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbggenerated Wed Jul 13 11:47:38 GMT+05:30 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbggenerated Wed Jul 13 11:47:38 GMT+05:30 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbggenerated Wed Jul 13 11:47:38 GMT+05:30 2011
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbggenerated Wed Jul 13 11:47:38 GMT+05:30 2011
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbggenerated Wed Jul 13 11:47:38 GMT+05:30 2011
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbggenerated Wed Jul 13 11:47:38 GMT+05:30 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbggenerated Wed Jul 13 11:47:38 GMT+05:30 2011
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbggenerated Wed Jul 13 11:47:38 GMT+05:30 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbggenerated Wed Jul 13 11:47:38 GMT+05:30 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app
     *
     * @mbggenerated Wed Jul 13 11:47:38 GMT+05:30 2011
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app
     *
     * @mbggenerated Wed Jul 13 11:47:38 GMT+05:30 2011
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andSNameIsNull() {
            addCriterion("s_name is null");
            return (Criteria) this;
        }

        public Criteria andSNameIsNotNull() {
            addCriterion("s_name is not null");
            return (Criteria) this;
        }

        public Criteria andSNameEqualTo(String value) {
            addCriterion("s_name =", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameNotEqualTo(String value) {
            addCriterion("s_name <>", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameGreaterThan(String value) {
            addCriterion("s_name >", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameGreaterThanOrEqualTo(String value) {
            addCriterion("s_name >=", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameLessThan(String value) {
            addCriterion("s_name <", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameLessThanOrEqualTo(String value) {
            addCriterion("s_name <=", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameLike(String value) {
            addCriterion("s_name like", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameNotLike(String value) {
            addCriterion("s_name not like", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameIn(List<String> values) {
            addCriterion("s_name in", values, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameNotIn(List<String> values) {
            addCriterion("s_name not in", values, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameBetween(String value1, String value2) {
            addCriterion("s_name between", value1, value2, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameNotBetween(String value1, String value2) {
            addCriterion("s_name not between", value1, value2, "sName");
            return (Criteria) this;
        }

        public Criteria andSTitleIsNull() {
            addCriterion("s_title is null");
            return (Criteria) this;
        }

        public Criteria andSTitleIsNotNull() {
            addCriterion("s_title is not null");
            return (Criteria) this;
        }

        public Criteria andSTitleEqualTo(String value) {
            addCriterion("s_title =", value, "sTitle");
            return (Criteria) this;
        }

        public Criteria andSTitleNotEqualTo(String value) {
            addCriterion("s_title <>", value, "sTitle");
            return (Criteria) this;
        }

        public Criteria andSTitleGreaterThan(String value) {
            addCriterion("s_title >", value, "sTitle");
            return (Criteria) this;
        }

        public Criteria andSTitleGreaterThanOrEqualTo(String value) {
            addCriterion("s_title >=", value, "sTitle");
            return (Criteria) this;
        }

        public Criteria andSTitleLessThan(String value) {
            addCriterion("s_title <", value, "sTitle");
            return (Criteria) this;
        }

        public Criteria andSTitleLessThanOrEqualTo(String value) {
            addCriterion("s_title <=", value, "sTitle");
            return (Criteria) this;
        }

        public Criteria andSTitleLike(String value) {
            addCriterion("s_title like", value, "sTitle");
            return (Criteria) this;
        }

        public Criteria andSTitleNotLike(String value) {
            addCriterion("s_title not like", value, "sTitle");
            return (Criteria) this;
        }

        public Criteria andSTitleIn(List<String> values) {
            addCriterion("s_title in", values, "sTitle");
            return (Criteria) this;
        }

        public Criteria andSTitleNotIn(List<String> values) {
            addCriterion("s_title not in", values, "sTitle");
            return (Criteria) this;
        }

        public Criteria andSTitleBetween(String value1, String value2) {
            addCriterion("s_title between", value1, value2, "sTitle");
            return (Criteria) this;
        }

        public Criteria andSTitleNotBetween(String value1, String value2) {
            addCriterion("s_title not between", value1, value2, "sTitle");
            return (Criteria) this;
        }

        public Criteria andFPriceIsNull() {
            addCriterion("f_price is null");
            return (Criteria) this;
        }

        public Criteria andFPriceIsNotNull() {
            addCriterion("f_price is not null");
            return (Criteria) this;
        }

        public Criteria andFPriceEqualTo(BigDecimal value) {
            addCriterion("f_price =", value, "fPrice");
            return (Criteria) this;
        }

        public Criteria andFPriceNotEqualTo(BigDecimal value) {
            addCriterion("f_price <>", value, "fPrice");
            return (Criteria) this;
        }

        public Criteria andFPriceGreaterThan(BigDecimal value) {
            addCriterion("f_price >", value, "fPrice");
            return (Criteria) this;
        }

        public Criteria andFPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("f_price >=", value, "fPrice");
            return (Criteria) this;
        }

        public Criteria andFPriceLessThan(BigDecimal value) {
            addCriterion("f_price <", value, "fPrice");
            return (Criteria) this;
        }

        public Criteria andFPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("f_price <=", value, "fPrice");
            return (Criteria) this;
        }

        public Criteria andFPriceIn(List<BigDecimal> values) {
            addCriterion("f_price in", values, "fPrice");
            return (Criteria) this;
        }

        public Criteria andFPriceNotIn(List<BigDecimal> values) {
            addCriterion("f_price not in", values, "fPrice");
            return (Criteria) this;
        }

        public Criteria andFPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("f_price between", value1, value2, "fPrice");
            return (Criteria) this;
        }

        public Criteria andFPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("f_price not between", value1, value2, "fPrice");
            return (Criteria) this;
        }

        public Criteria andSIconImageIsNull() {
            addCriterion("s_icon_image is null");
            return (Criteria) this;
        }

        public Criteria andSIconImageIsNotNull() {
            addCriterion("s_icon_image is not null");
            return (Criteria) this;
        }

        public Criteria andSIconImageEqualTo(String value) {
            addCriterion("s_icon_image =", value, "sIconImage");
            return (Criteria) this;
        }

        public Criteria andSIconImageNotEqualTo(String value) {
            addCriterion("s_icon_image <>", value, "sIconImage");
            return (Criteria) this;
        }

        public Criteria andSIconImageGreaterThan(String value) {
            addCriterion("s_icon_image >", value, "sIconImage");
            return (Criteria) this;
        }

        public Criteria andSIconImageGreaterThanOrEqualTo(String value) {
            addCriterion("s_icon_image >=", value, "sIconImage");
            return (Criteria) this;
        }

        public Criteria andSIconImageLessThan(String value) {
            addCriterion("s_icon_image <", value, "sIconImage");
            return (Criteria) this;
        }

        public Criteria andSIconImageLessThanOrEqualTo(String value) {
            addCriterion("s_icon_image <=", value, "sIconImage");
            return (Criteria) this;
        }

        public Criteria andSIconImageLike(String value) {
            addCriterion("s_icon_image like", value, "sIconImage");
            return (Criteria) this;
        }

        public Criteria andSIconImageNotLike(String value) {
            addCriterion("s_icon_image not like", value, "sIconImage");
            return (Criteria) this;
        }

        public Criteria andSIconImageIn(List<String> values) {
            addCriterion("s_icon_image in", values, "sIconImage");
            return (Criteria) this;
        }

        public Criteria andSIconImageNotIn(List<String> values) {
            addCriterion("s_icon_image not in", values, "sIconImage");
            return (Criteria) this;
        }

        public Criteria andSIconImageBetween(String value1, String value2) {
            addCriterion("s_icon_image between", value1, value2, "sIconImage");
            return (Criteria) this;
        }

        public Criteria andSIconImageNotBetween(String value1, String value2) {
            addCriterion("s_icon_image not between", value1, value2, "sIconImage");
            return (Criteria) this;
        }

        public Criteria andSLoaderImageIsNull() {
            addCriterion("s_loader_image is null");
            return (Criteria) this;
        }

        public Criteria andSLoaderImageIsNotNull() {
            addCriterion("s_loader_image is not null");
            return (Criteria) this;
        }

        public Criteria andSLoaderImageEqualTo(String value) {
            addCriterion("s_loader_image =", value, "sLoaderImage");
            return (Criteria) this;
        }

        public Criteria andSLoaderImageNotEqualTo(String value) {
            addCriterion("s_loader_image <>", value, "sLoaderImage");
            return (Criteria) this;
        }

        public Criteria andSLoaderImageGreaterThan(String value) {
            addCriterion("s_loader_image >", value, "sLoaderImage");
            return (Criteria) this;
        }

        public Criteria andSLoaderImageGreaterThanOrEqualTo(String value) {
            addCriterion("s_loader_image >=", value, "sLoaderImage");
            return (Criteria) this;
        }

        public Criteria andSLoaderImageLessThan(String value) {
            addCriterion("s_loader_image <", value, "sLoaderImage");
            return (Criteria) this;
        }

        public Criteria andSLoaderImageLessThanOrEqualTo(String value) {
            addCriterion("s_loader_image <=", value, "sLoaderImage");
            return (Criteria) this;
        }

        public Criteria andSLoaderImageLike(String value) {
            addCriterion("s_loader_image like", value, "sLoaderImage");
            return (Criteria) this;
        }

        public Criteria andSLoaderImageNotLike(String value) {
            addCriterion("s_loader_image not like", value, "sLoaderImage");
            return (Criteria) this;
        }

        public Criteria andSLoaderImageIn(List<String> values) {
            addCriterion("s_loader_image in", values, "sLoaderImage");
            return (Criteria) this;
        }

        public Criteria andSLoaderImageNotIn(List<String> values) {
            addCriterion("s_loader_image not in", values, "sLoaderImage");
            return (Criteria) this;
        }

        public Criteria andSLoaderImageBetween(String value1, String value2) {
            addCriterion("s_loader_image between", value1, value2, "sLoaderImage");
            return (Criteria) this;
        }

        public Criteria andSLoaderImageNotBetween(String value1, String value2) {
            addCriterion("s_loader_image not between", value1, value2, "sLoaderImage");
            return (Criteria) this;
        }

        public Criteria andSPnCertificatePathIsNull() {
            addCriterion("s_pn_certificate_path is null");
            return (Criteria) this;
        }

        public Criteria andSPnCertificatePathIsNotNull() {
            addCriterion("s_pn_certificate_path is not null");
            return (Criteria) this;
        }

        public Criteria andSPnCertificatePathEqualTo(String value) {
            addCriterion("s_pn_certificate_path =", value, "sPnCertificatePath");
            return (Criteria) this;
        }

        public Criteria andSPnCertificatePathNotEqualTo(String value) {
            addCriterion("s_pn_certificate_path <>", value, "sPnCertificatePath");
            return (Criteria) this;
        }

        public Criteria andSPnCertificatePathGreaterThan(String value) {
            addCriterion("s_pn_certificate_path >", value, "sPnCertificatePath");
            return (Criteria) this;
        }

        public Criteria andSPnCertificatePathGreaterThanOrEqualTo(String value) {
            addCriterion("s_pn_certificate_path >=", value, "sPnCertificatePath");
            return (Criteria) this;
        }

        public Criteria andSPnCertificatePathLessThan(String value) {
            addCriterion("s_pn_certificate_path <", value, "sPnCertificatePath");
            return (Criteria) this;
        }

        public Criteria andSPnCertificatePathLessThanOrEqualTo(String value) {
            addCriterion("s_pn_certificate_path <=", value, "sPnCertificatePath");
            return (Criteria) this;
        }

        public Criteria andSPnCertificatePathLike(String value) {
            addCriterion("s_pn_certificate_path like", value, "sPnCertificatePath");
            return (Criteria) this;
        }

        public Criteria andSPnCertificatePathNotLike(String value) {
            addCriterion("s_pn_certificate_path not like", value, "sPnCertificatePath");
            return (Criteria) this;
        }

        public Criteria andSPnCertificatePathIn(List<String> values) {
            addCriterion("s_pn_certificate_path in", values, "sPnCertificatePath");
            return (Criteria) this;
        }

        public Criteria andSPnCertificatePathNotIn(List<String> values) {
            addCriterion("s_pn_certificate_path not in", values, "sPnCertificatePath");
            return (Criteria) this;
        }

        public Criteria andSPnCertificatePathBetween(String value1, String value2) {
            addCriterion("s_pn_certificate_path between", value1, value2, "sPnCertificatePath");
            return (Criteria) this;
        }

        public Criteria andSPnCertificatePathNotBetween(String value1, String value2) {
            addCriterion("s_pn_certificate_path not between", value1, value2, "sPnCertificatePath");
            return (Criteria) this;
        }

        public Criteria andIDownloadCountIsNull() {
            addCriterion("i_download_count is null");
            return (Criteria) this;
        }

        public Criteria andIDownloadCountIsNotNull() {
            addCriterion("i_download_count is not null");
            return (Criteria) this;
        }

        public Criteria andIDownloadCountEqualTo(Long value) {
            addCriterion("i_download_count =", value, "iDownloadCount");
            return (Criteria) this;
        }

        public Criteria andIDownloadCountNotEqualTo(Long value) {
            addCriterion("i_download_count <>", value, "iDownloadCount");
            return (Criteria) this;
        }

        public Criteria andIDownloadCountGreaterThan(Long value) {
            addCriterion("i_download_count >", value, "iDownloadCount");
            return (Criteria) this;
        }

        public Criteria andIDownloadCountGreaterThanOrEqualTo(Long value) {
            addCriterion("i_download_count >=", value, "iDownloadCount");
            return (Criteria) this;
        }

        public Criteria andIDownloadCountLessThan(Long value) {
            addCriterion("i_download_count <", value, "iDownloadCount");
            return (Criteria) this;
        }

        public Criteria andIDownloadCountLessThanOrEqualTo(Long value) {
            addCriterion("i_download_count <=", value, "iDownloadCount");
            return (Criteria) this;
        }

        public Criteria andIDownloadCountIn(List<Long> values) {
            addCriterion("i_download_count in", values, "iDownloadCount");
            return (Criteria) this;
        }

        public Criteria andIDownloadCountNotIn(List<Long> values) {
            addCriterion("i_download_count not in", values, "iDownloadCount");
            return (Criteria) this;
        }

        public Criteria andIDownloadCountBetween(Long value1, Long value2) {
            addCriterion("i_download_count between", value1, value2, "iDownloadCount");
            return (Criteria) this;
        }

        public Criteria andIDownloadCountNotBetween(Long value1, Long value2) {
            addCriterion("i_download_count not between", value1, value2, "iDownloadCount");
            return (Criteria) this;
        }

        public Criteria andBSubmissionToAppleIsNull() {
            addCriterion("b_submission_to_apple is null");
            return (Criteria) this;
        }

        public Criteria andBSubmissionToAppleIsNotNull() {
            addCriterion("b_submission_to_apple is not null");
            return (Criteria) this;
        }

        public Criteria andBSubmissionToAppleEqualTo(Boolean value) {
            addCriterion("b_submission_to_apple =", value, "bSubmissionToApple");
            return (Criteria) this;
        }

        public Criteria andBSubmissionToAppleNotEqualTo(Boolean value) {
            addCriterion("b_submission_to_apple <>", value, "bSubmissionToApple");
            return (Criteria) this;
        }

        public Criteria andBSubmissionToAppleGreaterThan(Boolean value) {
            addCriterion("b_submission_to_apple >", value, "bSubmissionToApple");
            return (Criteria) this;
        }

        public Criteria andBSubmissionToAppleGreaterThanOrEqualTo(Boolean value) {
            addCriterion("b_submission_to_apple >=", value, "bSubmissionToApple");
            return (Criteria) this;
        }

        public Criteria andBSubmissionToAppleLessThan(Boolean value) {
            addCriterion("b_submission_to_apple <", value, "bSubmissionToApple");
            return (Criteria) this;
        }

        public Criteria andBSubmissionToAppleLessThanOrEqualTo(Boolean value) {
            addCriterion("b_submission_to_apple <=", value, "bSubmissionToApple");
            return (Criteria) this;
        }

        public Criteria andBSubmissionToAppleIn(List<Boolean> values) {
            addCriterion("b_submission_to_apple in", values, "bSubmissionToApple");
            return (Criteria) this;
        }

        public Criteria andBSubmissionToAppleNotIn(List<Boolean> values) {
            addCriterion("b_submission_to_apple not in", values, "bSubmissionToApple");
            return (Criteria) this;
        }

        public Criteria andBSubmissionToAppleBetween(Boolean value1, Boolean value2) {
            addCriterion("b_submission_to_apple between", value1, value2, "bSubmissionToApple");
            return (Criteria) this;
        }

        public Criteria andBSubmissionToAppleNotBetween(Boolean value1, Boolean value2) {
            addCriterion("b_submission_to_apple not between", value1, value2, "bSubmissionToApple");
            return (Criteria) this;
        }

        public Criteria andDCreatedOnIsNull() {
            addCriterion("d_created_on is null");
            return (Criteria) this;
        }

        public Criteria andDCreatedOnIsNotNull() {
            addCriterion("d_created_on is not null");
            return (Criteria) this;
        }

        public Criteria andDCreatedOnEqualTo(Date value) {
            addCriterion("d_created_on =", value, "dCreatedOn");
            return (Criteria) this;
        }

        public Criteria andDCreatedOnNotEqualTo(Date value) {
            addCriterion("d_created_on <>", value, "dCreatedOn");
            return (Criteria) this;
        }

        public Criteria andDCreatedOnGreaterThan(Date value) {
            addCriterion("d_created_on >", value, "dCreatedOn");
            return (Criteria) this;
        }

        public Criteria andDCreatedOnGreaterThanOrEqualTo(Date value) {
            addCriterion("d_created_on >=", value, "dCreatedOn");
            return (Criteria) this;
        }

        public Criteria andDCreatedOnLessThan(Date value) {
            addCriterion("d_created_on <", value, "dCreatedOn");
            return (Criteria) this;
        }

        public Criteria andDCreatedOnLessThanOrEqualTo(Date value) {
            addCriterion("d_created_on <=", value, "dCreatedOn");
            return (Criteria) this;
        }

        public Criteria andDCreatedOnIn(List<Date> values) {
            addCriterion("d_created_on in", values, "dCreatedOn");
            return (Criteria) this;
        }

        public Criteria andDCreatedOnNotIn(List<Date> values) {
            addCriterion("d_created_on not in", values, "dCreatedOn");
            return (Criteria) this;
        }

        public Criteria andDCreatedOnBetween(Date value1, Date value2) {
            addCriterion("d_created_on between", value1, value2, "dCreatedOn");
            return (Criteria) this;
        }

        public Criteria andDCreatedOnNotBetween(Date value1, Date value2) {
            addCriterion("d_created_on not between", value1, value2, "dCreatedOn");
            return (Criteria) this;
        }

        public Criteria andDUpdatedOnIsNull() {
            addCriterion("d_updated_on is null");
            return (Criteria) this;
        }

        public Criteria andDUpdatedOnIsNotNull() {
            addCriterion("d_updated_on is not null");
            return (Criteria) this;
        }

        public Criteria andDUpdatedOnEqualTo(Date value) {
            addCriterion("d_updated_on =", value, "dUpdatedOn");
            return (Criteria) this;
        }

        public Criteria andDUpdatedOnNotEqualTo(Date value) {
            addCriterion("d_updated_on <>", value, "dUpdatedOn");
            return (Criteria) this;
        }

        public Criteria andDUpdatedOnGreaterThan(Date value) {
            addCriterion("d_updated_on >", value, "dUpdatedOn");
            return (Criteria) this;
        }

        public Criteria andDUpdatedOnGreaterThanOrEqualTo(Date value) {
            addCriterion("d_updated_on >=", value, "dUpdatedOn");
            return (Criteria) this;
        }

        public Criteria andDUpdatedOnLessThan(Date value) {
            addCriterion("d_updated_on <", value, "dUpdatedOn");
            return (Criteria) this;
        }

        public Criteria andDUpdatedOnLessThanOrEqualTo(Date value) {
            addCriterion("d_updated_on <=", value, "dUpdatedOn");
            return (Criteria) this;
        }

        public Criteria andDUpdatedOnIn(List<Date> values) {
            addCriterion("d_updated_on in", values, "dUpdatedOn");
            return (Criteria) this;
        }

        public Criteria andDUpdatedOnNotIn(List<Date> values) {
            addCriterion("d_updated_on not in", values, "dUpdatedOn");
            return (Criteria) this;
        }

        public Criteria andDUpdatedOnBetween(Date value1, Date value2) {
            addCriterion("d_updated_on between", value1, value2, "dUpdatedOn");
            return (Criteria) this;
        }

        public Criteria andDUpdatedOnNotBetween(Date value1, Date value2) {
            addCriterion("d_updated_on not between", value1, value2, "dUpdatedOn");
            return (Criteria) this;
        }

        public Criteria andBEnabledIsNull() {
            addCriterion("b_enabled is null");
            return (Criteria) this;
        }

        public Criteria andBEnabledIsNotNull() {
            addCriterion("b_enabled is not null");
            return (Criteria) this;
        }

        public Criteria andBEnabledEqualTo(Boolean value) {
            addCriterion("b_enabled =", value, "bEnabled");
            return (Criteria) this;
        }

        public Criteria andBEnabledNotEqualTo(Boolean value) {
            addCriterion("b_enabled <>", value, "bEnabled");
            return (Criteria) this;
        }

        public Criteria andBEnabledGreaterThan(Boolean value) {
            addCriterion("b_enabled >", value, "bEnabled");
            return (Criteria) this;
        }

        public Criteria andBEnabledGreaterThanOrEqualTo(Boolean value) {
            addCriterion("b_enabled >=", value, "bEnabled");
            return (Criteria) this;
        }

        public Criteria andBEnabledLessThan(Boolean value) {
            addCriterion("b_enabled <", value, "bEnabled");
            return (Criteria) this;
        }

        public Criteria andBEnabledLessThanOrEqualTo(Boolean value) {
            addCriterion("b_enabled <=", value, "bEnabled");
            return (Criteria) this;
        }

        public Criteria andBEnabledIn(List<Boolean> values) {
            addCriterion("b_enabled in", values, "bEnabled");
            return (Criteria) this;
        }

        public Criteria andBEnabledNotIn(List<Boolean> values) {
            addCriterion("b_enabled not in", values, "bEnabled");
            return (Criteria) this;
        }

        public Criteria andBEnabledBetween(Boolean value1, Boolean value2) {
            addCriterion("b_enabled between", value1, value2, "bEnabled");
            return (Criteria) this;
        }

        public Criteria andBEnabledNotBetween(Boolean value1, Boolean value2) {
            addCriterion("b_enabled not between", value1, value2, "bEnabled");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 13 11:47:38 GMT+05:30 2011
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app
     *
     * @mbggenerated Wed Jul 13 11:47:38 GMT+05:30 2011
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}