package com.mobicart.model;

public class Authority {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column authorities.username
	 * @ibatorgenerated  Tue Sep 28 16:26:53 IST 2010
	 */
	private String username;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column authorities.authority
	 * @ibatorgenerated  Tue Sep 28 16:26:53 IST 2010
	 */
	private String authority;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column authorities.b_users
	 * @ibatorgenerated  Tue Sep 28 16:26:53 IST 2010
	 */
	private Boolean bUsers;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column authorities.b_orders
	 * @ibatorgenerated  Tue Sep 28 16:26:53 IST 2010
	 */
	private Boolean bOrders;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column authorities.b_payment
	 * @ibatorgenerated  Tue Sep 28 16:26:53 IST 2010
	 */
	private Boolean bPayment;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column authorities.b_content
	 * @ibatorgenerated  Tue Sep 28 16:26:53 IST 2010
	 */
	private Boolean bContent;

	
	
	public Authority() {
		super();
	}

	public Authority(Boolean bUsers, Boolean bOrders, Boolean bPayment,
			Boolean bContent) {
		super();
		this.bUsers = bUsers;
		this.bOrders = bOrders;
		this.bPayment = bPayment;
		this.bContent = bContent;
	}

	
	
	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column authorities.username
	 * @return  the value of authorities.username
	 * @ibatorgenerated  Tue Sep 28 16:26:53 IST 2010
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column authorities.username
	 * @param username  the value for authorities.username
	 * @ibatorgenerated  Tue Sep 28 16:26:53 IST 2010
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column authorities.authority
	 * @return  the value of authorities.authority
	 * @ibatorgenerated  Tue Sep 28 16:26:53 IST 2010
	 */
	public String getAuthority() {
		return authority;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column authorities.authority
	 * @param authority  the value for authorities.authority
	 * @ibatorgenerated  Tue Sep 28 16:26:53 IST 2010
	 */
	public void setAuthority(String authority) {
		this.authority = authority == null ? null : authority.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column authorities.b_users
	 * @return  the value of authorities.b_users
	 * @ibatorgenerated  Tue Sep 28 16:26:53 IST 2010
	 */
	public Boolean getbUsers() {
		return bUsers;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column authorities.b_users
	 * @param bUsers  the value for authorities.b_users
	 * @ibatorgenerated  Tue Sep 28 16:26:53 IST 2010
	 */
	public void setbUsers(Boolean bUsers) {
		this.bUsers = bUsers;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column authorities.b_orders
	 * @return  the value of authorities.b_orders
	 * @ibatorgenerated  Tue Sep 28 16:26:53 IST 2010
	 */
	public Boolean getbOrders() {
		return bOrders;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column authorities.b_orders
	 * @param bOrders  the value for authorities.b_orders
	 * @ibatorgenerated  Tue Sep 28 16:26:53 IST 2010
	 */
	public void setbOrders(Boolean bOrders) {
		this.bOrders = bOrders;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column authorities.b_payment
	 * @return  the value of authorities.b_payment
	 * @ibatorgenerated  Tue Sep 28 16:26:53 IST 2010
	 */
	public Boolean getbPayment() {
		return bPayment;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column authorities.b_payment
	 * @param bPayment  the value for authorities.b_payment
	 * @ibatorgenerated  Tue Sep 28 16:26:53 IST 2010
	 */
	public void setbPayment(Boolean bPayment) {
		this.bPayment = bPayment;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column authorities.b_content
	 * @return  the value of authorities.b_content
	 * @ibatorgenerated  Tue Sep 28 16:26:53 IST 2010
	 */
	public Boolean getbContent() {
		return bContent;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column authorities.b_content
	 * @param bContent  the value for authorities.b_content
	 * @ibatorgenerated  Tue Sep 28 16:26:53 IST 2010
	 */
	public void setbContent(Boolean bContent) {
		this.bContent = bContent;
	}
}