package com.mobicart.model;

import java.util.List;


import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.annotations.XStreamOmitField;

@XStreamAlias("SubDepartment")
public class Category {
    
	
	@XStreamAlias("subDepartmentId")
	private Long id;
	@XStreamAlias("departmentId")
    private Long departmentId;
	@XStreamAlias("parentSubDepartmentId")
    private Long parentCategoryId=0L;
	@XStreamAlias("name")
    private String sName;
    @XStreamAlias("status")
    private String sStatus;
    
    private Long storeId;
    private Long userId;
    
    
	@XStreamOmitField
    private List<Product> products;
    @XStreamAlias("productCount")
    private Integer iProductCount;
    private int iCategoryCount;
    public int getiCategoryCount() {
		return iCategoryCount;
	}



    

	public void setiCategoryCount(int iCategoryCount) {
		this.iCategoryCount = iCategoryCount;
	}




	@XStreamAlias("SubDepartmentList")
    private List<Category> categories;
    

	public Category() {
		super();
	}
    
    
    

	public Category(Long id) {
		super();
		this.id = id;
	}




	/**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column categories.id
     *
     * @return the value of categories.id
     *
     * @ibatorgenerated Thu Aug 12 11:31:32 IST 2010
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column categories.id
     *
     * @param id the value for categories.id
     *
     * @ibatorgenerated Thu Aug 12 11:31:32 IST 2010
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column categories.department_id
     *
     * @return the value of categories.department_id
     *
     * @ibatorgenerated Thu Aug 12 11:31:32 IST 2010
     */
    public Long getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column categories.department_id
     *
     * @param departmentId the value for categories.department_id
     *
     * @ibatorgenerated Thu Aug 12 11:31:32 IST 2010
     */
    public void setDepartmentId(Long departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column categories.s_name
     *
     * @return the value of categories.s_name
     *
     * @ibatorgenerated Thu Aug 12 11:31:32 IST 2010
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column categories.s_name
     *
     * @param sName the value for categories.s_name
     *
     * @ibatorgenerated Thu Aug 12 11:31:32 IST 2010
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column categories.s_status
     *
     * @return the value of categories.s_status
     *
     * @ibatorgenerated Thu Aug 12 11:31:32 IST 2010
     */
    public String getsStatus() {
        return sStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column categories.s_status
     *
     * @param sStatus the value for categories.s_status
     *
     * @ibatorgenerated Thu Aug 12 11:31:32 IST 2010
     */
    public void setsStatus(String sStatus) {
        this.sStatus = sStatus == null ? null : sStatus.trim();
    }
    
    

    public List<Product> getProducts() {
		return products;
	}


	public void setProducts(List<Product> products) {
		this.products = products;
	}




	public Integer getiProductCount() {
		return iProductCount;
	}




	public void setiProductCount(Integer iProductCount) {
		this.iProductCount = iProductCount;
	}




	public Long getParentCategoryId() {
		return parentCategoryId;
	}




	public void setParentCategoryId(Long parentCategoryId) {
		this.parentCategoryId = parentCategoryId;
	}




	public List<Category> getCategories() {
		return categories;
	}




	public void setCategories(List<Category> categories) {
		this.categories =categories;
	}

    
	
	
	
	public Long getStoreId() {
		return storeId;
	}




	public void setStoreId(Long storeId) {
		this.storeId = storeId;
	}




	public Long getUserId() {
		return userId;
	}




	public void setUserId(Long userId) {
		this.userId = userId;
	}

    
    
    



	
}
