package com.mobicart.model;

import java.util.Date;

import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotEmpty;

public class Contact {

	private Long id;
	
	@NotEmpty
    private String sName;

    @NotEmpty
    @Email
    private String sEmail;
    
    private String sPhone;
    private String sHeardFrom;
    private Date dSentOn;
    private String sMessage;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column contacts.id
     *
     * @return the value of contacts.id
     *
     * @ibatorgenerated Fri Oct 01 20:29:55 IST 2010
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column contacts.id
     *
     * @param id the value for contacts.id
     *
     * @ibatorgenerated Fri Oct 01 20:29:55 IST 2010
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column contacts.s_name
     *
     * @return the value of contacts.s_name
     *
     * @ibatorgenerated Fri Oct 01 20:29:55 IST 2010
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column contacts.s_name
     *
     * @param sName the value for contacts.s_name
     *
     * @ibatorgenerated Fri Oct 01 20:29:55 IST 2010
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column contacts.s_email
     *
     * @return the value of contacts.s_email
     *
     * @ibatorgenerated Fri Oct 01 20:29:55 IST 2010
     */
    public String getsEmail() {
        return sEmail;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column contacts.s_email
     *
     * @param sEmail the value for contacts.s_email
     *
     * @ibatorgenerated Fri Oct 01 20:29:55 IST 2010
     */
    public void setsEmail(String sEmail) {
        this.sEmail = sEmail == null ? null : sEmail.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column contacts.s_phone
     *
     * @return the value of contacts.s_phone
     *
     * @ibatorgenerated Fri Oct 01 20:29:55 IST 2010
     */
    public String getsPhone() {
        return sPhone;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column contacts.s_phone
     *
     * @param sPhone the value for contacts.s_phone
     *
     * @ibatorgenerated Fri Oct 01 20:29:55 IST 2010
     */
    public void setsPhone(String sPhone) {
        this.sPhone = sPhone;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column contacts.s_heard_from
     *
     * @return the value of contacts.s_heard_from
     *
     * @ibatorgenerated Fri Oct 01 20:29:55 IST 2010
     */
    public String getsHeardFrom() {
        return sHeardFrom;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column contacts.s_heard_from
     *
     * @param sHeardFrom the value for contacts.s_heard_from
     *
     * @ibatorgenerated Fri Oct 01 20:29:55 IST 2010
     */
    public void setsHeardFrom(String sHeardFrom) {
        this.sHeardFrom = sHeardFrom == null ? null : sHeardFrom.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column contacts.d_sent_on
     *
     * @return the value of contacts.d_sent_on
     *
     * @ibatorgenerated Fri Oct 01 20:29:55 IST 2010
     */
    public Date getdSentOn() {
        return dSentOn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column contacts.d_sent_on
     *
     * @param dSentOn the value for contacts.d_sent_on
     *
     * @ibatorgenerated Fri Oct 01 20:29:55 IST 2010
     */
    public void setdSentOn(Date dSentOn) {
        this.dSentOn = dSentOn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column contacts.s_message
     *
     * @return the value of contacts.s_message
     *
     * @ibatorgenerated Fri Oct 01 20:29:55 IST 2010
     */
    public String getsMessage() {
        return sMessage;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column contacts.s_message
     *
     * @param sMessage the value for contacts.s_message
     *
     * @ibatorgenerated Fri Oct 01 20:29:55 IST 2010
     */
    public void setsMessage(String sMessage) {
        this.sMessage = sMessage == null ? null : sMessage.trim();
    }
}