package com.mobicart.model;

import java.text.DateFormat;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;

import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.web.multipart.commons.CommonsMultipartFile;

import com.mobicart.dto.FeedDto;
import com.mobicart.util.FeedParserUtils;
import com.mobicart.util.validators.Feed;

public class News {
	
	

	private Long id;
	private Long storeId;
	private Long appId;
	@NotEmpty
	private String sTitle;
	private String sImage;
	@Feed
	private String sFeedUrl;
	private String sTwitterUsername;
	private Boolean bFeedStatus;
	private Boolean bTwitterStatus;
	private String sType;
	private String sBody;
	private Date dDate;
	private Date dDate2;
	private CommonsMultipartFile fNewsImage;
    
    private List<FeedDto> feedItems=new ArrayList<FeedDto>();
	   
	   
	public void setFeedItems(List<FeedDto> feedItems) {
		this.feedItems = feedItems;
	}

	public News() {
		super();
	}

	public News(Long id) {
		super();
		this.id = id;
	}




	public Long getId() {
        return id;
    }

    public void setfNewsImage(CommonsMultipartFile fNewsImage) {
		this.fNewsImage = fNewsImage;
	}

	public CommonsMultipartFile getfNewsImage() {
		return fNewsImage;
	}

		/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column news.id
	 * @param id  the value for news.id
	 * @ibatorgenerated  Thu Oct 28 15:41:40 IST 2010
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column news.store_id
	 * @return  the value of news.store_id
	 * @ibatorgenerated  Thu Oct 28 15:41:40 IST 2010
	 */
	public Long getStoreId() {
		return storeId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column news.store_id
	 * @param storeId  the value for news.store_id
	 * @ibatorgenerated  Thu Oct 28 15:41:40 IST 2010
	 */
	public void setStoreId(Long storeId) {
		this.storeId = storeId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column news.app_id
	 * @return  the value of news.app_id
	 * @ibatorgenerated  Thu Oct 28 15:41:40 IST 2010
	 */
	public Long getAppId() {
		return appId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column news.app_id
	 * @param appId  the value for news.app_id
	 * @ibatorgenerated  Thu Oct 28 15:41:40 IST 2010
	 */
	public void setAppId(Long appId) {
		this.appId = appId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column news.s_title
	 * @return  the value of news.s_title
	 * @ibatorgenerated  Thu Oct 28 15:41:40 IST 2010
	 */
	public String getsTitle() {
		return sTitle;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column news.s_title
	 * @param sTitle  the value for news.s_title
	 * @ibatorgenerated  Thu Oct 28 15:41:40 IST 2010
	 */
	public void setsTitle(String sTitle) {
		this.sTitle = sTitle == null ? null : sTitle.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column news.s_image
	 * @return  the value of news.s_image
	 * @ibatorgenerated  Thu Oct 28 15:41:40 IST 2010
	 */
	public String getsImage() {
		return sImage;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column news.s_image
	 * @param sImage  the value for news.s_image
	 * @ibatorgenerated  Thu Oct 28 15:41:40 IST 2010
	 */
	public void setsImage(String sImage) {
		this.sImage = sImage == null ? null : sImage.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column news.s_feed_url
	 * @return  the value of news.s_feed_url
	 * @ibatorgenerated  Thu Oct 28 15:41:40 IST 2010
	 */
	public String getsFeedUrl() {
		return sFeedUrl;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column news.s_feed_url
	 * @param sFeedUrl  the value for news.s_feed_url
	 * @ibatorgenerated  Thu Oct 28 15:41:40 IST 2010
	 */
	public void setsFeedUrl(String sFeedUrl) {
		this.sFeedUrl = sFeedUrl == null ? null : sFeedUrl.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column news.s_twitter_username
	 * @return  the value of news.s_twitter_username
	 * @ibatorgenerated  Thu Oct 28 15:41:40 IST 2010
	 */
	public String getsTwitterUsername() {
		return sTwitterUsername;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column news.s_twitter_username
	 * @param sTwitterUsername  the value for news.s_twitter_username
	 * @ibatorgenerated  Thu Oct 28 15:41:40 IST 2010
	 */
	public void setsTwitterUsername(String sTwitterUsername) {
		this.sTwitterUsername = sTwitterUsername == null ? null
				: sTwitterUsername.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column news.b_feed_status
	 * @return  the value of news.b_feed_status
	 * @ibatorgenerated  Thu Oct 28 15:41:40 IST 2010
	 */
	public Boolean getbFeedStatus() {
		return bFeedStatus;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column news.b_feed_status
	 * @param bFeedStatus  the value for news.b_feed_status
	 * @ibatorgenerated  Thu Oct 28 15:41:40 IST 2010
	 */
	public void setbFeedStatus(Boolean bFeedStatus) {
		this.bFeedStatus = bFeedStatus;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column news.b_twitter_status
	 * @return  the value of news.b_twitter_status
	 * @ibatorgenerated  Thu Oct 28 15:41:40 IST 2010
	 */
	public Boolean getbTwitterStatus() {
		return bTwitterStatus;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column news.b_twitter_status
	 * @param bTwitterStatus  the value for news.b_twitter_status
	 * @ibatorgenerated  Thu Oct 28 15:41:40 IST 2010
	 */
	public void setbTwitterStatus(Boolean bTwitterStatus) {
		this.bTwitterStatus = bTwitterStatus;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column news.s_type
	 * @return  the value of news.s_type
	 * @ibatorgenerated  Thu Oct 28 15:41:40 IST 2010
	 */
	public String getsType() {
		return sType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column news.s_type
	 * @param sType  the value for news.s_type
	 * @ibatorgenerated  Thu Oct 28 15:41:40 IST 2010
	 */
	public void setsType(String sType) {
		this.sType = sType == null ? null : sType.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column news.d_date
	 * @return  the value of news.d_date
	 * @ibatorgenerated  Thu Oct 28 15:41:40 IST 2010
	 */
	public Date getdDate() {
		return dDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column news.d_date
	 * @param dDate  the value for news.d_date
	 * @ibatorgenerated  Thu Oct 28 15:41:40 IST 2010
	 */
	public void setdDate(Date dDate) {
		this.dDate = dDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column news.s_body
	 * @return  the value of news.s_body
	 * @ibatorgenerated  Thu Oct 28 15:41:40 IST 2010
	 */
	public String getsBody() {
		return sBody;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column news.s_body
	 * @param sBody  the value for news.s_body
	 * @ibatorgenerated  Thu Oct 28 15:41:40 IST 2010
	 */
	public void setsBody(String sBody) {
		this.sBody = sBody == null ? null : sBody.trim();
	}

	
	
	public List<FeedDto> getFeedItems() {
		if(sType.equals("feed") && bFeedStatus){
			feedItems=FeedParserUtils.getFeedPosts(sFeedUrl);
		}
		return feedItems;
	}

	
	@SuppressWarnings("deprecation")
	public String getdDate2() {
		java.sql.Timestamp tuimesatmp= new java.sql.Timestamp(dDate.getTime());
		java.sql.Timestamp ts = tuimesatmp;
		java.util.GregorianCalendar cal = (GregorianCalendar) Calendar.getInstance();
		cal.setTime(ts);
		
		
		
		Format formatter = new SimpleDateFormat("E, dd MMM yyyy HH:mm:ss Z");
		String s  = formatter.format(cal.getTime());
		 
		 
	return s;
	}

	@Override
	public String toString() {
		return "News [id=" + id + ", storeId=" + storeId + ", appId=" + appId
				+ ", sTitle=" + sTitle + ", sImage=" + sImage + ", sBody="
				+ sBody + ", sFeedUrl=" + sFeedUrl + ", sType=" + sType
				+ ", fNewsImage=" + fNewsImage + "]";
	}
	
	
	
	
}