package com.mobicart.model;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.math.BigDecimal;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;


public class ProductOrder {
	/**
	 * Logger for this class
	 */
	private static final Logger logger = LoggerFactory.getLogger(ProductOrder.class);
    
	private Long id;
	
	private Long merchantId;
	
	private Long storeId;
	
	private Long appId;
	
	private String sMerchantPaypalEmail;
	
	private BigDecimal fAmount;
	
	private BigDecimal fShippingAmount;
	
	private BigDecimal fTaxAmount;
	
	private BigDecimal fTotalAmount;
	
	private String sBuyerName;
	
	private String sBuyerEmail;
	
	private Long iBuyerPhone;
	
	private String sShippingStreet;
	
	private String sShippingCity;
	
	private String sShippingState;
	
	private String sShippingPostalCode;
	
	private String sShippingCountry;
	
	private String sBillingStreet;
	
	private String sBillingCity;
	
	private String sBillingState;
	
	private String sBillingPostalCode;
	
	private String sBillingCountry;
	
	private String sStatus;
	
	private Date dOrderDate;

	List<ProductOrderItem> productOrderItems; 
	
	private String formattedOrderDate;
	
	private Boolean isShippingAddressDifferent;
	
	public String getFormattedOrderDate() {
		if (logger.isDebugEnabled()) {
			logger.debug("getFormattedOrderDate() - start"); //$NON-NLS-1$
		}

		Format formatter = new SimpleDateFormat("dd MMM yyyy HH:mm:ss");
		try{
		formattedOrderDate = formatter.format(dOrderDate); // Tue, 09 Jan 2002 22:14:02 -0500
		}catch(Exception e){
			logger.warn("getFormattedOrderDate() - exception ignored", e); //$NON-NLS-1$
			
		}

		
		return formattedOrderDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column product_orders.id
	 * @return  the value of product_orders.id
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column product_orders.id
	 * @param id  the value for product_orders.id
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column product_orders.merchant_id
	 * @return  the value of product_orders.merchant_id
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public Long getMerchantId() {
		return merchantId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column product_orders.merchant_id
	 * @param merchantId  the value for product_orders.merchant_id
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public void setMerchantId(Long merchantId) {
		this.merchantId = merchantId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column product_orders.store_id
	 * @return  the value of product_orders.store_id
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public Long getStoreId() {
		return storeId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column product_orders.store_id
	 * @param storeId  the value for product_orders.store_id
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public void setStoreId(Long storeId) {
		this.storeId = storeId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column product_orders.app_id
	 * @return  the value of product_orders.app_id
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public Long getAppId() {
		return appId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column product_orders.app_id
	 * @param appId  the value for product_orders.app_id
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public void setAppId(Long appId) {
		this.appId = appId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column product_orders.s_merchant_paypal_email
	 * @return  the value of product_orders.s_merchant_paypal_email
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public String getsMerchantPaypalEmail() {
		return sMerchantPaypalEmail;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column product_orders.s_merchant_paypal_email
	 * @param sMerchantPaypalEmail  the value for product_orders.s_merchant_paypal_email
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public void setsMerchantPaypalEmail(String sMerchantPaypalEmail) {
		this.sMerchantPaypalEmail = sMerchantPaypalEmail == null ? null
				: sMerchantPaypalEmail.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column product_orders.f_amount
	 * @return  the value of product_orders.f_amount
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public BigDecimal getfAmount() {
		return fAmount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column product_orders.f_amount
	 * @param fAmount  the value for product_orders.f_amount
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public void setfAmount(BigDecimal fAmount) {
		this.fAmount = fAmount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column product_orders.f_shipping_amount
	 * @return  the value of product_orders.f_shipping_amount
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public BigDecimal getfShippingAmount() {
		return fShippingAmount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column product_orders.f_shipping_amount
	 * @param fShippingAmount  the value for product_orders.f_shipping_amount
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public void setfShippingAmount(BigDecimal fShippingAmount) {
		this.fShippingAmount = fShippingAmount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column product_orders.f_tax_amount
	 * @return  the value of product_orders.f_tax_amount
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public BigDecimal getfTaxAmount() {
		return fTaxAmount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column product_orders.f_tax_amount
	 * @param fTaxAmount  the value for product_orders.f_tax_amount
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public void setfTaxAmount(BigDecimal fTaxAmount) {
		this.fTaxAmount = fTaxAmount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column product_orders.f_total_amount
	 * @return  the value of product_orders.f_total_amount
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public BigDecimal getfTotalAmount() {
		return fTotalAmount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column product_orders.f_total_amount
	 * @param fTotalAmount  the value for product_orders.f_total_amount
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public void setfTotalAmount(BigDecimal fTotalAmount) {
		this.fTotalAmount = fTotalAmount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column product_orders.s_buyer_name
	 * @return  the value of product_orders.s_buyer_name
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public String getsBuyerName() {
		return sBuyerName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column product_orders.s_buyer_name
	 * @param sBuyerName  the value for product_orders.s_buyer_name
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public void setsBuyerName(String sBuyerName) {
		this.sBuyerName = sBuyerName == null ? null : sBuyerName.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column product_orders.s_buyer_email
	 * @return  the value of product_orders.s_buyer_email
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public String getsBuyerEmail() {
		return sBuyerEmail;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column product_orders.s_buyer_email
	 * @param sBuyerEmail  the value for product_orders.s_buyer_email
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public void setsBuyerEmail(String sBuyerEmail) {
		this.sBuyerEmail = sBuyerEmail == null ? null : sBuyerEmail.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column product_orders.i_buyer_phone
	 * @return  the value of product_orders.i_buyer_phone
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public Long getiBuyerPhone() {
		return iBuyerPhone;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column product_orders.i_buyer_phone
	 * @param iBuyerPhone  the value for product_orders.i_buyer_phone
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public void setiBuyerPhone(Long iBuyerPhone) {
		this.iBuyerPhone = iBuyerPhone;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column product_orders.s_shipping_street
	 * @return  the value of product_orders.s_shipping_street
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public String getsShippingStreet() {
		return sShippingStreet;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column product_orders.s_shipping_street
	 * @param sShippingStreet  the value for product_orders.s_shipping_street
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public void setsShippingStreet(String sShippingStreet) {
		this.sShippingStreet = sShippingStreet == null ? null : sShippingStreet
				.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column product_orders.s_shipping_city
	 * @return  the value of product_orders.s_shipping_city
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public String getsShippingCity() {
		return sShippingCity;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column product_orders.s_shipping_city
	 * @param sShippingCity  the value for product_orders.s_shipping_city
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public void setsShippingCity(String sShippingCity) {
		this.sShippingCity = sShippingCity == null ? null : sShippingCity
				.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column product_orders.s_shipping_state
	 * @return  the value of product_orders.s_shipping_state
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public String getsShippingState() {
		return sShippingState;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column product_orders.s_shipping_state
	 * @param sShippingState  the value for product_orders.s_shipping_state
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public void setsShippingState(String sShippingState) {
		this.sShippingState = sShippingState == null ? null : sShippingState
				.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column product_orders.s_shipping_postal_code
	 * @return  the value of product_orders.s_shipping_postal_code
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public String getsShippingPostalCode() {
		return sShippingPostalCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column product_orders.s_shipping_postal_code
	 * @param sShippingPostalCode  the value for product_orders.s_shipping_postal_code
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public void setsShippingPostalCode(String sShippingPostalCode) {
		this.sShippingPostalCode = sShippingPostalCode == null ? null
				: sShippingPostalCode.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column product_orders.s_shipping_country
	 * @return  the value of product_orders.s_shipping_country
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public String getsShippingCountry() {
		return sShippingCountry;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column product_orders.s_shipping_country
	 * @param sShippingCountry  the value for product_orders.s_shipping_country
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public void setsShippingCountry(String sShippingCountry) {
		this.sShippingCountry = sShippingCountry == null ? null
				: sShippingCountry.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column product_orders.s_billing_street
	 * @return  the value of product_orders.s_billing_street
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public String getsBillingStreet() {
		return sBillingStreet;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column product_orders.s_billing_street
	 * @param sBillingStreet  the value for product_orders.s_billing_street
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public void setsBillingStreet(String sBillingStreet) {
		this.sBillingStreet = sBillingStreet == null ? null : sBillingStreet
				.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column product_orders.s_billing_city
	 * @return  the value of product_orders.s_billing_city
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public String getsBillingCity() {
		return sBillingCity;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column product_orders.s_billing_city
	 * @param sBillingCity  the value for product_orders.s_billing_city
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public void setsBillingCity(String sBillingCity) {
		this.sBillingCity = sBillingCity == null ? null : sBillingCity.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column product_orders.s_billing_state
	 * @return  the value of product_orders.s_billing_state
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public String getsBillingState() {
		return sBillingState;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column product_orders.s_billing_state
	 * @param sBillingState  the value for product_orders.s_billing_state
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public void setsBillingState(String sBillingState) {
		this.sBillingState = sBillingState == null ? null : sBillingState
				.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column product_orders.s_billing_postal_code
	 * @return  the value of product_orders.s_billing_postal_code
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public String getsBillingPostalCode() {
		return sBillingPostalCode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column product_orders.s_billing_postal_code
	 * @param sBillingPostalCode  the value for product_orders.s_billing_postal_code
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public void setsBillingPostalCode(String sBillingPostalCode) {
		this.sBillingPostalCode = sBillingPostalCode == null ? null
				: sBillingPostalCode.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column product_orders.s_billing_country
	 * @return  the value of product_orders.s_billing_country
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public String getsBillingCountry() {
		return sBillingCountry;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column product_orders.s_billing_country
	 * @param sBillingCountry  the value for product_orders.s_billing_country
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public void setsBillingCountry(String sBillingCountry) {
		this.sBillingCountry = sBillingCountry == null ? null : sBillingCountry
				.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column product_orders.s_status
	 * @return  the value of product_orders.s_status
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public String getsStatus() {
		return sStatus;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column product_orders.s_status
	 * @param sStatus  the value for product_orders.s_status
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public void setsStatus(String sStatus) {
		this.sStatus = sStatus == null ? null : sStatus.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column product_orders.d_order_date
	 * @return  the value of product_orders.d_order_date
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public Date getdOrderDate() {
		return dOrderDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column product_orders.d_order_date
	 * @param dOrderDate  the value for product_orders.d_order_date
	 * @ibatorgenerated  Tue Oct 05 12:13:44 IST 2010
	 */
	public void setdOrderDate(Date dOrderDate) {
		this.dOrderDate = dOrderDate;
	}

	
	
	
	public List<ProductOrderItem> getProductOrderItems() {
		return productOrderItems;
	}

	public void setProductOrderItems(List<ProductOrderItem> productOrderItems) {
		this.productOrderItems = productOrderItems;
	}

	
	
	
	

	public void setFormattedOrderDate(String formattedOrderDate) {
		this.formattedOrderDate = formattedOrderDate;
	}

	public Boolean getIsShippingAddressDifferent() {
		try{
		if(sShippingStreet.equals(sBillingStreet) && sShippingCity.equals(sBillingCity) && sShippingState.equals(sBillingState) && sShippingCountry.equals(sBillingCountry) &&  sShippingPostalCode.equals(sBillingPostalCode) ){
			isShippingAddressDifferent=false;
		}else{
			isShippingAddressDifferent=true;
		}
		}catch (Exception e) {
			// TODO: handle exception
		}
		return isShippingAddressDifferent;
	}

	public void setIsShippingAddressDifferent(Boolean isShippingAddressDifferent) {
		this.isShippingAddressDifferent = isShippingAddressDifferent;
	}

	
	public String getBillingAddress() {
		return "[Street=" + sBillingStreet
				+ ", City=" + sBillingCity + ", State="
				+ sBillingState + ", PostalCode=" + sBillingPostalCode
				+ ", Country=" + sBillingCountry + "]";
	}
	
	public String getBillingAddressFormatted() {
		/*return "Street : " + sBillingStreet + "<br/>"
				+ "City : " + sBillingCity + "<br/>" + "State : "
				+ sBillingState + "<br/>" + "PostalCode : " + sBillingPostalCode + "<br/>"
				+ "Country : " + sBillingCountry;*/
		return sBillingStreet + "<br/>"	+ sBillingCity + "<br/>"
		+ sBillingState + "<br/>" + sBillingPostalCode + "<br/>" + sBillingCountry;
	}

	
	public String toShippingAddress() {
		return sShippingStreet + "<br/>" + sShippingCity + "<br/>"
				+ sShippingState + "<br/>"
				+ sShippingPostalCode + "<br/>"
				+ sShippingCountry;
	}

	@Override
	public String toString() {
		return "ProductOrder [id=" + id + ", merchantId=" + merchantId
				+ ", storeId=" + storeId + ", appId=" + appId
				+ ", sMerchantPaypalEmail=" + sMerchantPaypalEmail
				+ ", fAmount=" + fAmount + ", fShippingAmount="
				+ fShippingAmount + ", fTaxAmount=" + fTaxAmount
				+ ", fTotalAmount=" + fTotalAmount + ", sBuyerName="
				+ sBuyerName + ", sBuyerEmail=" + sBuyerEmail
				+ ", iBuyerPhone=" + iBuyerPhone + ", "
				+ "dOrderDate=" + dOrderDate
				+ ", formattedOrderDate=" + formattedOrderDate
				+ ", items=" + productOrderItems
				+ "]";
	}

	


	
	
	
	
	
   
}