package com.mobicart.model;

import java.util.Date;

public class PushNotification {
	
	
	 /**
     * This field corresponds to the database column push_notification.id
     */
    private Long id;

    /**
     * This field corresponds to the database column push_notification.app_id
     */
    private Long appId;

    /**
     * This field corresponds to the database column push_notification.message
     */
    private String message;
    
    /**
     * title of the message
     */
    private String title;
    /**
     * Set default to All users
     */
    private String sendTo="A";
    
    /**
     * zipcode
     */
    private String zipcode;
    
    /**
     * radius
     */
    private int radius;
    
    /**
     * units kms or miles
     */
    private String units;

    /**
     * This field corresponds to the database column push_notification.date
     */
    private Date date;

    /**
     * This field corresponds to the database column push_notification.status
     */
    private String status;

    /**
     * This field corresponds to the database column push_notification.notified_count
     */
    private Integer notifiedCount;

	
	
	public PushNotification(){
	
	}
	
	public PushNotification(Long id){
		 this.id = id;
	}
	
	
   
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column push_notification.id
     *
     * @return the value of push_notification.id
     *
     * @ibatorgenerated Thu Feb 24 10:25:32 IST 2011
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column push_notification.id
     *
     * @param id the value for push_notification.id
     *
     * @ibatorgenerated Thu Feb 24 10:25:32 IST 2011
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column push_notification.app_id
     *
     * @return the value of push_notification.app_id
     *
     * @ibatorgenerated Thu Feb 24 10:25:32 IST 2011
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column push_notification.app_id
     *
     * @param appId the value for push_notification.app_id
     *
     * @ibatorgenerated Thu Feb 24 10:25:32 IST 2011
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column push_notification.message
     *
     * @return the value of push_notification.message
     *
     * @ibatorgenerated Thu Feb 24 10:25:32 IST 2011
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column push_notification.message
     *
     * @param message the value for push_notification.message
     *
     * @ibatorgenerated Thu Feb 24 10:25:32 IST 2011
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getSendTo() {
		return sendTo;
	}

	public void setSendTo(String sendTo) {
		this.sendTo = sendTo;
	}

	public String getZipcode() {
		return zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	public Integer getRadius() {
		return radius;
	}

	public void setRadius(Integer radius) {
		this.radius = radius;
	}

	public String getUnits() {
		return units;
	}

	public void setUnits(String units) {
		this.units = units;
	}

	/**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column push_notification.date
     *
     * @return the value of push_notification.date
     *
     * @ibatorgenerated Thu Feb 24 10:25:32 IST 2011
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column push_notification.date
     *
     * @param date the value for push_notification.date
     *
     * @ibatorgenerated Thu Feb 24 10:25:32 IST 2011
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column push_notification.status
     *
     * @return the value of push_notification.status
     *
     * @ibatorgenerated Thu Feb 24 10:25:32 IST 2011
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column push_notification.status
     *
     * @param status the value for push_notification.status
     *
     * @ibatorgenerated Thu Feb 24 10:25:32 IST 2011
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
 
     *
     * @return the value of push_notification.notified_count
     *
     */
    public Integer getNotifiedCount() {
        return notifiedCount;
    }

    /**
     * This method sets the value of the database column push_notification.notified_count
     *
     * @param notifiedCount the value for push_notification.notified_count
     *
     */
    public void setNotifiedCount(Integer notifiedCount) {
        this.notifiedCount = notifiedCount;
    }

	@Override
	public String toString() {
		return "PushNotification [id=" + id + ", appId=" + appId + ", message="
				+ message + ", title=" + title + ", sendTo=" + sendTo
				+ ", zipcode=" + zipcode + ", radius=" + radius + ", units="
				+ units + ", date=" + date + ", status=" + status
				+ ", notifiedCount=" + notifiedCount + "]";
	}
    
    
    
    
    
}