package com.mobicart.model;

import java.util.Comparator;


public class StaticPage {

	
	
	private Long id;
	
	private Long featureId;
	
	private Long userId;

	private Long appId;

	private String sName;

	private String sTitle;

	private Boolean bEnabled;

	private String sDescription;

	private Boolean bCustomCopyrightPage;
	
	private Integer PRIORITY;
	

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column static_pages.id
	 * @return  the value of static_pages.id
	 * @ibatorgenerated  Tue Oct 12 12:00:28 IST 2010
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column static_pages.id
	 * @param id  the value for static_pages.id
	 * @ibatorgenerated  Tue Oct 12 12:00:28 IST 2010
	 */
	public void setId(Long id) {
		this.id = id;
	}

	public Long getFeatureId() {
		return featureId;
	}

	public void setFeatureId(Long featureId) {
		this.featureId = featureId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column static_pages.user_id
	 * @return  the value of static_pages.user_id
	 * @ibatorgenerated  Tue Oct 12 12:00:28 IST 2010
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column static_pages.user_id
	 * @param userId  the value for static_pages.user_id
	 * @ibatorgenerated  Tue Oct 12 12:00:28 IST 2010
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column static_pages.app_id
	 * @return  the value of static_pages.app_id
	 * @ibatorgenerated  Tue Oct 12 12:00:28 IST 2010
	 */
	public Long getAppId() {
		return appId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column static_pages.app_id
	 * @param appId  the value for static_pages.app_id
	 * @ibatorgenerated  Tue Oct 12 12:00:28 IST 2010
	 */
	public void setAppId(Long appId) {
		this.appId = appId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column static_pages.s_name
	 * @return  the value of static_pages.s_name
	 * @ibatorgenerated  Tue Oct 12 12:00:28 IST 2010
	 */
	public String getsName() {
		return sName;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column static_pages.s_name
	 * @param sName  the value for static_pages.s_name
	 * @ibatorgenerated  Tue Oct 12 12:00:28 IST 2010
	 */
	public void setsName(String sName) {
		this.sName = sName == null ? null : sName.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column static_pages.s_title
	 * @return  the value of static_pages.s_title
	 * @ibatorgenerated  Tue Oct 12 12:00:28 IST 2010
	 */
	public String getsTitle() {
		return sTitle;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column static_pages.s_title
	 * @param sTitle  the value for static_pages.s_title
	 * @ibatorgenerated  Tue Oct 12 12:00:28 IST 2010
	 */
	public void setsTitle(String sTitle) {
		this.sTitle = sTitle == null ? null : sTitle.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column static_pages.b_enabled
	 * @return  the value of static_pages.b_enabled
	 * @ibatorgenerated  Tue Oct 12 12:00:28 IST 2010
	 */
	public Boolean getbEnabled() {
		return bEnabled;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column static_pages.b_enabled
	 * @param bEnabled  the value for static_pages.b_enabled
	 * @ibatorgenerated  Tue Oct 12 12:00:28 IST 2010
	 */
	public void setbEnabled(Boolean bEnabled) {
		this.bEnabled = bEnabled;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column static_pages.s_description
	 * @return  the value of static_pages.s_description
	 * @ibatorgenerated  Tue Oct 12 12:00:28 IST 2010
	 */
	public String getsDescription() {
		return sDescription;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column static_pages.s_description
	 * @param sDescription  the value for static_pages.s_description
	 * @ibatorgenerated  Tue Oct 12 12:00:28 IST 2010
	 */
	public void setsDescription(String sDescription) {
		this.sDescription = sDescription == null ? null : sDescription.trim();
	}

	
	
	
	public StaticPage() {
		super();
	
	}

	public StaticPage(Long id) {
		super();
		this.id = id;
	}

	
	public StaticPage(String sName, String sTitle) {
		super();
		this.sName = sName;
		this.sTitle = sTitle;
	}

	
	public StaticPage(Long featureId,Long userId, Long appId, String sName, String sTitle) {
		super();
		this.featureId=featureId;
		this.userId = userId;
		this.appId = appId;
		this.sName = sName;
		this.sTitle = sTitle;
	}

	
	public Boolean getbCustomCopyrightPage() {
		return bCustomCopyrightPage;
	}

	public void setbCustomCopyrightPage(Boolean bCustomCopyrightPage) {
		this.bCustomCopyrightPage = bCustomCopyrightPage;
	}

	@Override
	public String toString() {
		return "StaticPage [id=" + id + ", userId=" + userId + ", appId="
				+ appId + ", sName=" + sName + ", sTitle=" + sTitle
				+ ", sDescription=" + sDescription + "]";
	}
	
	
	





	public Integer getPRIORITY() {
		
		if(sName.equals("about"))
			PRIORITY=1; 
		if(sName.equals("contact"))
			PRIORITY=2; 
		if(sName.equals("terms"))
			PRIORITY=3;
		if(sName.equals("privacy"))
			PRIORITY=4;
		if(sName.equals("page1"))
			PRIORITY=5;
		if(sName.equals("page2"))
			PRIORITY=6;
		if(sName.equals("copyright"))
			PRIORITY=7;
		return PRIORITY;
		
	}

	public void setPRIORITY(Integer pRIORITY) {
		PRIORITY = pRIORITY;
	}


	public static final Comparator<StaticPage> PRIORITY_ORDER =
        new Comparator<StaticPage>() {
		public int compare(StaticPage p1, StaticPage p2) {
				return p1.getPRIORITY().compareTo(p2.getPRIORITY());
		}
	};
	
	
	
}