package com.mobicart.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class StateExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table states
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table states
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table states
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	public StateExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table states
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	protected StateExample(StateExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table states
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table states
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table states
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table states
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table states
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table states
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table states
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table states
	 * @ibatorgenerated  Tue Dec 07 12:34:44 IST 2010
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return this;
		}

		public Criteria andIdIn(List values) {
			addCriterion("id in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List values) {
			addCriterion("id not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return this;
		}

		public Criteria andTerritoryIdIsNull() {
			addCriterion("territory_id is null");
			return this;
		}

		public Criteria andTerritoryIdIsNotNull() {
			addCriterion("territory_id is not null");
			return this;
		}

		public Criteria andTerritoryIdEqualTo(Long value) {
			addCriterion("territory_id =", value, "territoryId");
			return this;
		}

		public Criteria andTerritoryIdNotEqualTo(Long value) {
			addCriterion("territory_id <>", value, "territoryId");
			return this;
		}

		public Criteria andTerritoryIdGreaterThan(Long value) {
			addCriterion("territory_id >", value, "territoryId");
			return this;
		}

		public Criteria andTerritoryIdGreaterThanOrEqualTo(Long value) {
			addCriterion("territory_id >=", value, "territoryId");
			return this;
		}

		public Criteria andTerritoryIdLessThan(Long value) {
			addCriterion("territory_id <", value, "territoryId");
			return this;
		}

		public Criteria andTerritoryIdLessThanOrEqualTo(Long value) {
			addCriterion("territory_id <=", value, "territoryId");
			return this;
		}

		public Criteria andTerritoryIdIn(List values) {
			addCriterion("territory_id in", values, "territoryId");
			return this;
		}

		public Criteria andTerritoryIdNotIn(List values) {
			addCriterion("territory_id not in", values, "territoryId");
			return this;
		}

		public Criteria andTerritoryIdBetween(Long value1, Long value2) {
			addCriterion("territory_id between", value1, value2, "territoryId");
			return this;
		}

		public Criteria andTerritoryIdNotBetween(Long value1, Long value2) {
			addCriterion("territory_id not between", value1, value2,
					"territoryId");
			return this;
		}

		public Criteria andSNameIsNull() {
			addCriterion("s_name is null");
			return this;
		}

		public Criteria andSNameIsNotNull() {
			addCriterion("s_name is not null");
			return this;
		}

		public Criteria andSNameEqualTo(String value) {
			addCriterion("s_name =", value, "sName");
			return this;
		}

		public Criteria andSNameNotEqualTo(String value) {
			addCriterion("s_name <>", value, "sName");
			return this;
		}

		public Criteria andSNameGreaterThan(String value) {
			addCriterion("s_name >", value, "sName");
			return this;
		}

		public Criteria andSNameGreaterThanOrEqualTo(String value) {
			addCriterion("s_name >=", value, "sName");
			return this;
		}

		public Criteria andSNameLessThan(String value) {
			addCriterion("s_name <", value, "sName");
			return this;
		}

		public Criteria andSNameLessThanOrEqualTo(String value) {
			addCriterion("s_name <=", value, "sName");
			return this;
		}

		public Criteria andSNameLike(String value) {
			addCriterion("s_name like", value, "sName");
			return this;
		}

		public Criteria andSNameNotLike(String value) {
			addCriterion("s_name not like", value, "sName");
			return this;
		}

		public Criteria andSNameIn(List values) {
			addCriterion("s_name in", values, "sName");
			return this;
		}

		public Criteria andSNameNotIn(List values) {
			addCriterion("s_name not in", values, "sName");
			return this;
		}

		public Criteria andSNameBetween(String value1, String value2) {
			addCriterion("s_name between", value1, value2, "sName");
			return this;
		}

		public Criteria andSNameNotBetween(String value1, String value2) {
			addCriterion("s_name not between", value1, value2, "sName");
			return this;
		}

		public Criteria andSCodeIsNull() {
			addCriterion("s_code is null");
			return this;
		}

		public Criteria andSCodeIsNotNull() {
			addCriterion("s_code is not null");
			return this;
		}

		public Criteria andSCodeEqualTo(String value) {
			addCriterion("s_code =", value, "sCode");
			return this;
		}

		public Criteria andSCodeNotEqualTo(String value) {
			addCriterion("s_code <>", value, "sCode");
			return this;
		}

		public Criteria andSCodeGreaterThan(String value) {
			addCriterion("s_code >", value, "sCode");
			return this;
		}

		public Criteria andSCodeGreaterThanOrEqualTo(String value) {
			addCriterion("s_code >=", value, "sCode");
			return this;
		}

		public Criteria andSCodeLessThan(String value) {
			addCriterion("s_code <", value, "sCode");
			return this;
		}

		public Criteria andSCodeLessThanOrEqualTo(String value) {
			addCriterion("s_code <=", value, "sCode");
			return this;
		}

		public Criteria andSCodeLike(String value) {
			addCriterion("s_code like", value, "sCode");
			return this;
		}

		public Criteria andSCodeNotLike(String value) {
			addCriterion("s_code not like", value, "sCode");
			return this;
		}

		public Criteria andSCodeIn(List values) {
			addCriterion("s_code in", values, "sCode");
			return this;
		}

		public Criteria andSCodeNotIn(List values) {
			addCriterion("s_code not in", values, "sCode");
			return this;
		}

		public Criteria andSCodeBetween(String value1, String value2) {
			addCriterion("s_code between", value1, value2, "sCode");
			return this;
		}

		public Criteria andSCodeNotBetween(String value1, String value2) {
			addCriterion("s_code not between", value1, value2, "sCode");
			return this;
		}

		public Criteria andBCustomIsNull() {
			addCriterion("b_custom is null");
			return this;
		}

		public Criteria andBCustomIsNotNull() {
			addCriterion("b_custom is not null");
			return this;
		}

		public Criteria andBCustomEqualTo(Boolean value) {
			addCriterion("b_custom =", value, "bCustom");
			return this;
		}

		public Criteria andBCustomNotEqualTo(Boolean value) {
			addCriterion("b_custom <>", value, "bCustom");
			return this;
		}

		public Criteria andBCustomGreaterThan(Boolean value) {
			addCriterion("b_custom >", value, "bCustom");
			return this;
		}

		public Criteria andBCustomGreaterThanOrEqualTo(Boolean value) {
			addCriterion("b_custom >=", value, "bCustom");
			return this;
		}

		public Criteria andBCustomLessThan(Boolean value) {
			addCriterion("b_custom <", value, "bCustom");
			return this;
		}

		public Criteria andBCustomLessThanOrEqualTo(Boolean value) {
			addCriterion("b_custom <=", value, "bCustom");
			return this;
		}

		public Criteria andBCustomIn(List values) {
			addCriterion("b_custom in", values, "bCustom");
			return this;
		}

		public Criteria andBCustomNotIn(List values) {
			addCriterion("b_custom not in", values, "bCustom");
			return this;
		}

		public Criteria andBCustomBetween(Boolean value1, Boolean value2) {
			addCriterion("b_custom between", value1, value2, "bCustom");
			return this;
		}

		public Criteria andBCustomNotBetween(Boolean value1, Boolean value2) {
			addCriterion("b_custom not between", value1, value2, "bCustom");
			return this;
		}
	}
}