package com.mobicart.model;

import java.util.Date;

public class Video {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column videos.id
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	private Long id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column videos.user_id
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	private Long userId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column videos.app_id
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	private Long appId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column videos.store_id
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	private Long storeId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column videos.s_title
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	private String sTitle;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column videos.s_url
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	private String sUrl;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column videos.d_added_on
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	private Date dAddedOn;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column videos.i_watch_count
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	private Integer iWatchCount;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column videos.id
	 * @return  the value of videos.id
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column videos.id
	 * @param id  the value for videos.id
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column videos.user_id
	 * @return  the value of videos.user_id
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column videos.user_id
	 * @param userId  the value for videos.user_id
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column videos.app_id
	 * @return  the value of videos.app_id
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	public Long getAppId() {
		return appId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column videos.app_id
	 * @param appId  the value for videos.app_id
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	public void setAppId(Long appId) {
		this.appId = appId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column videos.store_id
	 * @return  the value of videos.store_id
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	public Long getStoreId() {
		return storeId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column videos.store_id
	 * @param storeId  the value for videos.store_id
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	public void setStoreId(Long storeId) {
		this.storeId = storeId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column videos.s_title
	 * @return  the value of videos.s_title
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	public String getsTitle() {
		return sTitle;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column videos.s_title
	 * @param sTitle  the value for videos.s_title
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	public void setsTitle(String sTitle) {
		this.sTitle = sTitle == null ? null : sTitle.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column videos.s_url
	 * @return  the value of videos.s_url
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	public String getsUrl() {
		return sUrl;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column videos.s_url
	 * @param sUrl  the value for videos.s_url
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	public void setsUrl(String sUrl) {
		this.sUrl = sUrl == null ? null : sUrl.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column videos.d_added_on
	 * @return  the value of videos.d_added_on
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	public Date getdAddedOn() {
		return dAddedOn;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column videos.d_added_on
	 * @param dAddedOn  the value for videos.d_added_on
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	public void setdAddedOn(Date dAddedOn) {
		this.dAddedOn = dAddedOn;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column videos.i_watch_count
	 * @return  the value of videos.i_watch_count
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	public Integer getiWatchCount() {
		return iWatchCount;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column videos.i_watch_count
	 * @param iWatchCount  the value for videos.i_watch_count
	 * @ibatorgenerated  Mon Aug 16 19:46:37 IST 2010
	 */
	public void setiWatchCount(Integer iWatchCount) {
		this.iWatchCount = iWatchCount;
	}
}