package com.mobicart.dao.impl;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.mobicart.model.ApiPartner;
import com.mobicart.model.ApiPartnerExample;
import com.mobicart.util.Pager;

import java.sql.SQLException;
import java.util.List;

public class ApiPartnerDAOImpl implements ApiPartnerDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table api_partner
     *
     * @ibatorgenerated Wed Jan 18 18:43:27 IST 2012
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table api_partner
     *
     * @ibatorgenerated Wed Jan 18 18:43:27 IST 2012
     */
    public ApiPartnerDAOImpl(SqlMapClient sqlMapClient) {
        this();
        this.sqlMapClient = sqlMapClient;
    }
    
    public ApiPartnerDAOImpl() {
        super();
        
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table api_partner
     *
     * @ibatorgenerated Wed Jan 18 18:43:27 IST 2012
     */
    public int countApiPartnerByExample(ApiPartnerExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("api_partner.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table api_partner
     *
     * @ibatorgenerated Wed Jan 18 18:43:27 IST 2012
     */
    public int deleteApiPartnerByExample(ApiPartnerExample example) throws SQLException {
        int rows = sqlMapClient.delete("api_partner.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table api_partner
     *
     * @ibatorgenerated Wed Jan 18 18:43:27 IST 2012
     */
    public int deleteApiPartnerByPrimaryKey(Integer id) throws SQLException {
        ApiPartner key = new ApiPartner();
        key.setId(id);
        int rows = sqlMapClient.delete("api_partner.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table api_partner
     *
     * @ibatorgenerated Wed Jan 18 18:43:27 IST 2012
     */
    public void insertApiPartner(ApiPartner record) throws SQLException {
        sqlMapClient.insert("api_partner.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table api_partner
     *
     * @ibatorgenerated Wed Jan 18 18:43:27 IST 2012
     */
    public Integer insertApiPartnerSelective(ApiPartner record) throws SQLException {
        return (Integer)sqlMapClient.insert("api_partner.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table api_partner
     *
     * @ibatorgenerated Wed Jan 18 18:43:27 IST 2012
     */
    public List selectApiPartnerByExample(ApiPartnerExample example) throws SQLException {
        List list = sqlMapClient.queryForList("api_partner.ibatorgenerated_selectByExample", example);
        return list;
    }
    
    public SqlMapClient getSqlMapClient() {
		return sqlMapClient;
	}

	public void setSqlMapClient(SqlMapClient sqlMapClient) {
		this.sqlMapClient = sqlMapClient;
	}

	/**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table api_partner
     *
     * @ibatorgenerated Wed Jan 18 18:43:27 IST 2012
     */
    public List findAll(Pager pager) throws SQLException {
        List list = sqlMapClient.queryForList("api_partner.ibatorgenerated_selectAll");
        return list;
    }
    
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table api_partner
     *
     * @ibatorgenerated Wed Jan 18 18:43:27 IST 2012
     */
    public List findAll() throws SQLException {
        List list = sqlMapClient.queryForList("api_partner.ibatorgenerated_selectAll");
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table api_partner
     *
     * @ibatorgenerated Wed Jan 18 18:43:27 IST 2012
     */
    public ApiPartner selectApiPartnerByPrimaryKey(Integer id) throws SQLException {
        ApiPartner key = new ApiPartner();
        key.setId(id);
        ApiPartner record = (ApiPartner) sqlMapClient.queryForObject("api_partner.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table api_partner
     *
     * @ibatorgenerated Wed Jan 18 18:43:27 IST 2012
     */
    public int updateApiPartnerByExampleSelective(ApiPartner record, ApiPartnerExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("api_partner.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table api_partner
     *
     * @ibatorgenerated Wed Jan 18 18:43:27 IST 2012
     */
    public int updateApiPartnerByExample(ApiPartner record, ApiPartnerExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("api_partner.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table api_partner
     *
     * @ibatorgenerated Wed Jan 18 18:43:27 IST 2012
     */
    public int updateApiPartnerByPrimaryKeySelective(ApiPartner record) throws SQLException {
        int rows = sqlMapClient.update("api_partner.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table api_partner
     *
     * @ibatorgenerated Wed Jan 18 18:43:27 IST 2012
     */
    public int updateApiPartnerByPrimaryKey(ApiPartner record) throws SQLException {
        int rows = sqlMapClient.update("api_partner.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table api_partner
     *
     * @ibatorgenerated Wed Jan 18 18:43:27 IST 2012
     */
    private static class UpdateByExampleParms extends ApiPartnerExample {
        private Object record;

        public UpdateByExampleParms(Object record, ApiPartnerExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}