package com.mobicart.dao.impl;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.mobicart.model.MerchantPartner;
import com.mobicart.model.MerchantPartnerExample;
import java.sql.SQLException;
import java.util.List;

public class MerchantPartnerDAOImpl implements MerchantPartnerDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table merchant_partner
     *
     * @ibatorgenerated Thu Jan 19 19:29:57 IST 2012
     */
    private SqlMapClient sqlMapClient;

    public MerchantPartnerDAOImpl(){}
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table merchant_partner
     *
     * @ibatorgenerated Thu Jan 19 19:29:57 IST 2012
     */
    public MerchantPartnerDAOImpl(SqlMapClient sqlMapClient) {
        this();
        this.sqlMapClient = sqlMapClient;
    }

    public SqlMapClient getSqlMapClient() {
		return sqlMapClient;
	}
	public void setSqlMapClient(SqlMapClient sqlMapClient) {
		this.sqlMapClient = sqlMapClient;
	}
	/**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table merchant_partner
     *
     * @ibatorgenerated Thu Jan 19 19:29:57 IST 2012
     */
    public int countMerchantPartnerByExample(MerchantPartnerExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("merchant_partner.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table merchant_partner
     *
     * @ibatorgenerated Thu Jan 19 19:29:57 IST 2012
     */
    public int deleteMerchantPartnerByExample(MerchantPartnerExample example) throws SQLException {
        int rows = sqlMapClient.delete("merchant_partner.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table merchant_partner
     *
     * @ibatorgenerated Thu Jan 19 19:29:57 IST 2012
     */
    public int deleteMerchantPartnerByPrimaryKey(Integer id) throws SQLException {
        MerchantPartner key = new MerchantPartner();
        key.setId(id);
        int rows = sqlMapClient.delete("merchant_partner.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table merchant_partner
     *
     * @ibatorgenerated Thu Jan 19 19:29:57 IST 2012
     */
    public void insertMerchantPartner(MerchantPartner record) throws SQLException {
        sqlMapClient.insert("merchant_partner.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table merchant_partner
     *
     * @ibatorgenerated Thu Jan 19 19:29:57 IST 2012
     */
    public Integer insertMerchantPartnerSelective(MerchantPartner record) throws SQLException {
        return (Integer)sqlMapClient.insert("merchant_partner.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table merchant_partner
     *
     * @ibatorgenerated Thu Jan 19 19:29:57 IST 2012
     */
    public List<MerchantPartner> selectMerchantPartnerByExample(MerchantPartnerExample example) throws SQLException {
        List<MerchantPartner> list = (List<MerchantPartner>)sqlMapClient.queryForList("merchant_partner.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table merchant_partner
     *
     * @ibatorgenerated Thu Jan 19 19:29:57 IST 2012
     */
    public MerchantPartner selectMerchantPartnerByPrimaryKey(Integer id) throws SQLException {
        MerchantPartner key = new MerchantPartner();
        key.setId(id);
        MerchantPartner record = (MerchantPartner) sqlMapClient.queryForObject("merchant_partner.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table merchant_partner
     *
     * @ibatorgenerated Thu Jan 19 19:29:57 IST 2012
     */
    public int updateMerchantPartnerByExampleSelective(MerchantPartner record, MerchantPartnerExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("merchant_partner.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table merchant_partner
     *
     * @ibatorgenerated Thu Jan 19 19:29:57 IST 2012
     */
    public int updateMerchantPartnerByExample(MerchantPartner record, MerchantPartnerExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("merchant_partner.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table merchant_partner
     *
     * @ibatorgenerated Thu Jan 19 19:29:57 IST 2012
     */
    public int updateMerchantPartnerByPrimaryKeySelective(MerchantPartner record) throws SQLException {
        int rows = sqlMapClient.update("merchant_partner.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table merchant_partner
     *
     * @ibatorgenerated Thu Jan 19 19:29:57 IST 2012
     */
    public int updateMerchantPartnerByPrimaryKey(MerchantPartner record) throws SQLException {
        int rows = sqlMapClient.update("merchant_partner.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table merchant_partner
     *
     * @ibatorgenerated Thu Jan 19 19:29:57 IST 2012
     */
    private static class UpdateByExampleParms extends MerchantPartnerExample {
        private Object record;

        public UpdateByExampleParms(Object record, MerchantPartnerExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}