package com.mobicart.dao.impl;

import com.mobicart.model.MerchantPartner;
import com.mobicart.model.MerchantPartnerExample;
import java.sql.SQLException;
import java.util.List;

public interface MerchantPartnerDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table merchant_partner
     *
     * @ibatorgenerated Thu Jan 19 19:29:57 IST 2012
     */
    int countMerchantPartnerByExample(MerchantPartnerExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table merchant_partner
     *
     * @ibatorgenerated Thu Jan 19 19:29:57 IST 2012
     */
    int deleteMerchantPartnerByExample(MerchantPartnerExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table merchant_partner
     *
     * @ibatorgenerated Thu Jan 19 19:29:57 IST 2012
     */
    int deleteMerchantPartnerByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table merchant_partner
     *
     * @ibatorgenerated Thu Jan 19 19:29:57 IST 2012
     */
    void insertMerchantPartner(MerchantPartner record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table merchant_partner
     *
     * @ibatorgenerated Thu Jan 19 19:29:57 IST 2012
     */
    Integer insertMerchantPartnerSelective(MerchantPartner record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table merchant_partner
     *
     * @ibatorgenerated Thu Jan 19 19:29:57 IST 2012
     */
    List<MerchantPartner> selectMerchantPartnerByExample(MerchantPartnerExample merchantPartnerExample) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table merchant_partner
     *
     * @ibatorgenerated Thu Jan 19 19:29:57 IST 2012
     */
    MerchantPartner selectMerchantPartnerByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table merchant_partner
     *
     * @ibatorgenerated Thu Jan 19 19:29:57 IST 2012
     */
    int updateMerchantPartnerByExampleSelective(MerchantPartner record, MerchantPartnerExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table merchant_partner
     *
     * @ibatorgenerated Thu Jan 19 19:29:57 IST 2012
     */
    int updateMerchantPartnerByExample(MerchantPartner record, MerchantPartnerExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table merchant_partner
     *
     * @ibatorgenerated Thu Jan 19 19:29:57 IST 2012
     */
    int updateMerchantPartnerByPrimaryKeySelective(MerchantPartner record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table merchant_partner
     *
     * @ibatorgenerated Thu Jan 19 19:29:57 IST 2012
     */
    int updateMerchantPartnerByPrimaryKey(MerchantPartner record) throws SQLException;
}